### ISSUE TITLE
Size of control

### ISSUE THREAD

**Issue by pantonis** [CuppaLabs/angular2-multiselect-dropdown#1]
Hi,

In the multi [examples](https://cuppalabs.github.io/angular2-multiselect-dropdown/) only 2-3 chips are added in the input when selected. If you select more they are not being shown but instead only a number is shown which is increasing. Is there any way to show all? It is a very nice control maybe the best I found for angular 2 and showing only some of them makes it unusable.

Thanks

**Comment by CuppaLabs** [comment]
Hi, Thank your for providing the feedback. I would add a new configuration option to limit the number of chips to show in input which would take a value as a number and if the option is not set it would be defaulted to show all chips.  In next few days you should be getting it. Hope this would help you use the component.

**Comment by pantonis** [comment]
Perfect

**Comment by CuppaLabs** [comment]
By default now it would show all the selected badges in the input. New config option 'badgeShowLimit' is now available to limit the number of badges to show in the input field. If this property is not set in the settings object, by default all the selected badges will be show. Hope this resolves your issue.
