### ISSUE TITLE
Not able to Customize UI for angular2-multiselect-dropdown

### ISSUE THREAD

**Issue by muraliakepati** [CuppaLabs/angular2-multiselect-dropdown#102]
I was trying to set width,height, itemslist height, selected panel list height width. But i am not able to do that as in angular 2 everything was present in node modules.

Could you please help me with how to give our own custom stylings for angular2-multiselect-dropdown.
i have attached the screenshot as well regarding my issue.

[angular 2 dropdown issue.docx](https://github.com/CuppaLabs/angular2-multiselect-dropdown/files/1511447/angular.2.dropdown.issue.docx)

**Comment by CuppaLabs** [comment]
Please refer to this demo for customized CSS . https://cuppalabs.github.io/angular2-multiselect-dropdown/#/styling
Similar to the color property you can add your own styles of any property using this approach

**Comment by muraliakepati** [comment]
This is not working i just tried what is there in link still not getting . i want to set width of dropdown and downarro button is misplacing. So could you pls suggest some other solution?

**Comment by CuppaLabs** [comment]
refer to examples at  https://cuppalabs.github.io/angular2-multiselect-dropdown

**Comment by SwethaBurra** [comment]
I am unable to change the background color of c-token class. Followed this link  https://cuppalabs.github.io/angular2-multiselect-dropdown/#/styling  but still no results.

**Comment by Zeeshan0201** [comment]
@CuppaLabs Thanks For Given Examples With Elaboration.

**Comment by aishwaryardandi** [comment]
@CuppaLabs tried your example, but it doesnt work for me!

**Comment by sukhveersingh** [comment]
just overwrite css classes of multiselect dropdown. Add these classes in your style.css file or any css file which you are linking in index page.



.selected-list{
  border:1px solid #ced4da;
  border-radius:5px;
}

.pure-checkbox input[type=checkbox]+label:before {
  color: #0079fe;
  border: 1px solid #0079fe;
}

.list-area {
    border: 1px solid #ccc;
    border-radius: 3px;
    background: #fff;
    margin: 0;
}

**Comment by SasikalaGanapathy** [comment]
How to Set height of the **angular2-multiselect** dropdown as bootstrap dropdown height. Since the textbox I have used is taking bootstrap's height and angular2-multiselect dropdown is quite bigger than regular bootstrap dropdown

Please help me.

**Comment by sukhveersingh** [comment]
add this css in your style.css file which is inside src

.c-btn {
  display: inline-block;
  border-width: 1px;
  line-height: 1.25;
  border-radius: 3px;
  font-size: .85rem;
  padding: 5px 10px;
  cursor: pointer;
  align-items: center;
  min-height: 38px;
  border: 1px solid #fb9f40 !important;
  padding: 14px !important;
  
}

**Comment by sukhveersingh** [comment]
> How to Set height of the **angular2-multiselect** dropdown as bootstrap dropdown height. Since the textbox I have used is taking bootstrap's height and angular2-multiselect dropdown is quite bigger than regular bootstrap dropdown
> 
> Please help me.

add this css in your style.css file which is inside src

.c-btn {
display: inline-block;
border-width: 1px;
line-height: 1.25;
border-radius: 3px;
font-size: .85rem;
padding: 5px 10px;
cursor: pointer;
align-items: center;
min-height: 38px;
border: 1px solid #fb9f40 !important;
padding: 14px !important;

}
