### ISSUE TITLE
disable AfterViewInit

### ISSUE THREAD

**Issue by judge2k** [CuppaLabs/angular2-multiselect-dropdown#103]
Hi,

i can enable/disable the dropdown once on ngInit.

But, i have a situation where i must change this later.

The form should start with the control enabled,
but disable it later, based on a value that i will receive from my backend.

Just changing the 'disabled' setting from 'false' to 'true', doesn't seem to work.

is there any way to do that ?

**Comment by CuppaLabs** [comment]
Instead of changin only one property of the config object, create a new object of the config with the new values. That will work. Hence closing the issue.

**Comment by judge2k** [comment]
Yeap.
That did the trick.

Thank you very much!
