### ISSUE TITLE
selection on subscribe data list is not properly

### ISSUE THREAD

**Issue by rajshivkumar** [CuppaLabs/angular2-multiselect-dropdown#106]
When i get the data from mongodb through service and subscribe the same in your code, we got the list but having the following issues:

1. property name is not shown
2. when i clicked one item, it will select all but save only one selected item.

Please guide me to remove these issues...

**Comment by CuppaLabs** [comment]
Well, this is something related to the data structure you have been providing to the component. Definitely  I am going to help you on this, but not here. Please write a personal mail to me. Would be closing this issue here, as it does not highlight an issue in the component. Thank you !!
