### ISSUE TITLE
After applying group by, I need to Display only that group by item which is belong from search item.

### ISSUE THREAD

**Issue by priyankaahire** [CuppaLabs/angular2-multiselect-dropdown#107]
Hello
Really good component
issues.
Search not working as expected after applying group by.
https://cuppalabs.github.io/angular2-multiselect-dropdown/#/groupby
If I am search for "sw" then only display **Europe->Sweden**. But it is display  **Europe->Sweden** **with Asia** & **Asia Pacific**. Is this bug?

Thanks
Priyanka Ahire

**Comment by CuppaLabs** [comment]
fixed. Fix available in v2.3.0
