### ISSUE TITLE
Search seems not be working properly

### ISSUE THREAD

**Issue by sundertinwar** [CuppaLabs/angular2-multiselect-dropdown#108]
Hey,

Nice control providing good customization's. I was trying to play around with control and found below issues.

1. Search not working as expected.
https://cuppalabs.github.io/angular2-multiselect-dropdown/#/templating
Search for Ottawa. Just play around and you would see it not working. Is this a bug?

2. I integrated the control in my test project. I am not getting dropdown arrow ('^') and not getting any errors also in console. What should be issue here?

3. Can we set bootstrap select theme on this control? It looks bit wired with other bootstrap control.

Thanks,
Shyam

**Comment by CuppaLabs** [comment]
search works only for the itemName property. Will generalize in next release.

**Comment by CuppaLabs** [comment]
Fixed. v2.2.0. Mesh search is available. Searches text in all properties of item.

**Comment by t-pankajkumar** [comment]
why itemName was hardcoded instead of configurable field?
This should be fixed asap.

**Comment by CuppaLabs** [comment]
@t-pankajkumar You should read the documentation carefully get that there are 2 generic cases. 
Case 1 - User needs only label and a check box. itemName can be hardcoded and filter works on the itemName.
Case 2 - User can have more properties for each item. In this case the user needs to use the templateMode to have more properties in one menu item. See https://cuppalabs.github.io/angular2-multiselect-dropdown/#/templating. In this example, if you search , it works on all properties of the list items.
Please read the documentation and explore the examples carefully before raising questions or making nay demands on the code.
