### ISSUE TITLE
display like a dropup

### ISSUE THREAD

**Issue by chelaruc** [CuppaLabs/angular2-multiselect-dropdown#109]
Hi! Thank you for the good work! Do you have a setting for displaying the elements on top? Something like in this image:
![screen shot 2017-12-05 at 16 14 27](https://user-images.githubusercontent.com/22840626/33611542-6a19ae24-d9d7-11e7-97ee-68f3f7a75082.png)

Thanks

**Comment by kiransalian91** [comment]
Hi. did you find any solution? i'm facing same issue.

**Comment by CuppaLabs** [comment]
Available in latest release. Use settings propert 'position'

**Comment by senthil1690** [comment]
Is that possible for "append to body" option for dropdown list ?

**Comment by Local9** [comment]
Apped to body would fix a lot of common problems, only need to change how the element is being added to the body. Either it does appendChild of the Element to the body of the document or it just ignores it and works as it currently does.

```
@Input() appendTo: any;

constructor (private el: Element) {}

ngAfterViewInit() {
  if(this.appendTo) {
    if(this.appendTo === 'body') {
      document.body.appendChild(this.el.nativeElement);
    } else {
      this.appendTo.appendChild(this.el.nativeElement);
    }
  }
}

ngOnDestroy() {
  if (this.appendTo && this.appendTo === 'body') {
    document.body.removeChild(this.el.nativeElement);
  }
}
```

Add something like this in @CuppaLabs and I'll love you (well by you a coffee).

**Comment by senthil1690** [comment]
@Local9 thank you

**Comment by Local9** [comment]
Sorry @senthil1690 I just updated my code above, it was ElementRef not Element.
