### ISSUE TITLE
Hangs for a while if more data

### ISSUE THREAD

**Issue by ivarkrs** [CuppaLabs/angular2-multiselect-dropdown#110]
Hi, It's one of the beautiful component have come across.
If I have more than 100 numbers of data, it hangs for a while before displays the list. If have like 30-40 displays quickly.
Could you please help on this?
Is it a defect or I am doing something wrong...

**Comment by CuppaLabs** [comment]
Any heavy DOM manipulations will cause a delay. Since the for loop is used to render list items, any increase in number of list items will cause this delay. We are implementing lazy loading feature in next release. That should fix your issue.. Please stay tuned.

**Comment by CuppaLabs** [comment]
related to #90

**Comment by CuppaLabs** [comment]
fixed. New feature lazy loading available in v2.3.0
