### ISSUE TITLE
Automatically focus on Search field when opening dropdown

### ISSUE THREAD

**Issue by colinturner** [CuppaLabs/angular2-multiselect-dropdown#111]
When you click on a dropdown, it would be great if the Search field would automatically focus so that a user can start searching without having to click a second time.

Is there already a way to add this functionality in the dropdown's settings?

**Comment by CuppaLabs** [comment]
Good suggestion. Thank you. Will take it as enhancement for next release.

**Comment by CuppaLabs** [comment]
fixed. Available in v2.2.0. new config property searchAutofocus is available.
