### ISSUE TITLE
Capture event when user blurs the dropdown

### ISSUE THREAD

**Issue by Nelladel** [CuppaLabs/angular2-multiselect-dropdown#113]
I was wondering if there's a way to capture the event of an _**"end of selection"**_ phase. i.e: 
- User clicks on the dropdown
- Selects item 1
- Selects item 2
- Selects item 5
- Clicks anywhere else in the page
- `Event is fired`

I was hoping to achieve this through a `(blur)` event on the dropdown, but it isn't working... Any chance I could capture the event when the user is DONE selecting items?

**Comment by CuppaLabs** [comment]
Good suggestion. Thank you. Will take as an enhancement for next release.

**Comment by CuppaLabs** [comment]
Fixed. available in v2.2.0. Two new events onOpen() and onClose() are available. That should solve.
