### ISSUE TITLE
Bug: Error when trying to focus a non-existent search filter.

### ISSUE THREAD

**Issue by Nelladel** [CuppaLabs/angular2-multiselect-dropdown#116]
Using package version: 2.2.0

---
A error appears when the settings have been set to:
`enableSearchFilter` = `false`

and the component is toggled. The function `toggleDropdown()` (line `221` of `multiselect.component.ts`) automatically focuses the search filter component once the dropdown is toggled, but doesn't take into account when there has been no filter instantiation. 

I'm assuming the fix would go something like: 
Before: 
```ts
toggleDropdown(evt: any) {
        if (this.settings.disabled) {
            return false;
        }
        this.isActive = !this.isActive;
        if (this.isActive) {
            if (this.settings.searchAutofocus) {
                setTimeout(() => {
                    this.searchInput.nativeElement.focus();
                }, 0);
            }
            this.onOpen.emit(true);
        }
        else {
            this.onClose.emit(false);
        }
        evt.preventDefault();
    }
```
After:
```ts
toggleDropdown(evt: any) {
        if (this.settings.disabled) {
            return false;
        }
        this.isActive = !this.isActive;
        if (this.isActive) {
            if (this.settings.searchAutofocus) {
                setTimeout(() => {
                    if (this.settings.enableSearchFilter)
                        this.searchInput.nativeElement.focus();
                }, 0);
            }
            this.onOpen.emit(true);
        }
        else {
            this.onClose.emit(false);
        }
        evt.preventDefault();
    }
```
Whereby the settings for the instantiation of the `searchInput` are checked before trying to focus the HTML element. 

---

This is the error the app outputs: 
![image](https://user-images.githubusercontent.com/28733300/34081418-955c306a-e34c-11e7-87b2-d15d22fabe1d.png)

Thanks for the awesome component :)

**Comment by CuppaLabs** [comment]
fixed. Please use v2.2.1
