### ISSUE TITLE
Dropdowns remains open on IE10

### ISSUE THREAD

**Issue by Mridul16** [CuppaLabs/angular2-multiselect-dropdown#120]
I have used angular2-multiselect dropdown in my application and it works fine on all the browsers except IE10 or below.
In IE10, when the page loads, the dropdown is open by default and even after selection or outside click, it does not close.

Please help

**Comment by CuppaLabs** [comment]
no support for IE as of now

**Comment by dduft** [comment]
Button-click toggles hidden and hidden is unknown attribute in IE9/10: https://github.com/angular/angular/issues/5774
Possible solution is here: https://github.com/angular/angular/issues/5774#issuecomment-209397018
