### ISSUE TITLE
showing warning when using with angular 4

### ISSUE THREAD

**Issue by shivamgupta211** [CuppaLabs/angular2-multiselect-dropdown#121]
WARNING in 
/modules/admin-starter/~/angular2-multiselect-dropdown/clickOutside.js

(Emitted value instead of an instance of Error) Cannot find source file '../tmp/src-inlined/clickOutside.ts': Error: Can't resolve '../tmp/src-inlined/clickOutside.ts' in '/modules/admin-starter/node_modules/angular2-multiselect-dropdown'\n @ /modules/admin-starter/~/angular2-multiselect-dropdown/angular2-multiselect-dropdown.js 2:0-55\n @ /modules/admin-starter/src/book-manager/book-manager.module.ts\n @ ./src async\n @ ./~/@angular/core/@angular/core.es5.js\n @ ./src/main.ts\n @ multi webpack-dev-server/client?http://127.0.0.1:9000 webpack/hot/dev-server ./src/main.ts

WARNING in /modules/admin-starter/~/angular2-multiselect-dropdown/multiselect.component.js

(Emitted value instead of an instance of Error) Cannot find source file '../tmp/src-inlined/multiselect.component.ts': Error: Can't resolve '../tmp/src-inlined/multiselect.component.ts' in '/modules/admin-starter/node_modules/angular2-multiselect-dropdown'\n @ //modules/admin-starter/~/angular2-multiselect-dropdown/angular2-multiselect-dropdown.js 1:0-61 6:0-67\n @ /modules/admin-starter/src/book-manager/book-manager.module.ts\n @ ./src async\n @ ./~/@angular/core/@angular/core.es5.js\n @ ./src/main.ts\n @ multi webpack-dev-server/client?http://127.0.0.1:9000 webpack/hot/dev-server ./src/main.ts

**Comment by CuppaLabs** [comment]
working as expected. Please refer to package.json for the version on which the component is developed.
