### ISSUE TITLE
tick-boxes disappear when dynamically changing disabled setting from true to false

### ISSUE THREAD

**Issue by Hatish** [CuppaLabs/angular2-multiselect-dropdown#124]
I have a scenario where a user has to click a button, and the multi-select must change from a disabled state, to an enabled state. 

First approach, I update the relevant setting object, change disabled from true to false, and nothing happens.

Second approach, I replace the setting object with a new object, with the same values as previously, except for the disabled status now being different. This changes the ui correctly (the dropdown is now enabled), but the tickboxes (and ticks within the boxes) are gone. The select-box at the top shows the correctly selected values, and you can select/unselect values correctly. So the drop-down is fully functional, but does not display correctly.

Please investigate. If there is a correct way to change a setting dynamically which I have completely missed, I am happy to make changes accordingly.

**Comment by CuppaLabs** [comment]
Fixed. Fix available in v2.3.0
