### ISSUE TITLE
Close dropdown on select

### ISSUE THREAD

**Issue by psenechal** [CuppaLabs/angular2-multiselect-dropdown#126]
Hello...great component! I have a question regarding using this component as a single select dropdown. It works great and I'm using it primarily for the search/filter feature because the list has about 80 items in it.

Is there a way when using the dropdown as a single select, to force the dropdown to close when an item is selected? I see there is a method in the source code for "closeDropdown()". I figured the easiest thing to do would be to add something to my itemSelected callback function to execute this method, but I can't seem to find out how to get reference to the component object in order to execute this method on it.

Any ideas on how this could be achieved? Thanks!

**Comment by psenechal** [comment]
UPDATE: I figured it out. I was able to create a @ViewChild of type AngularMultiSelect and execute the method in my selected callback.

**Comment by Luis16287** [comment]
My code is like this

```
other imports...
import { AngularMultiSelect } from 'angular2-multiselect-dropdown';
export class FuseLogin2Component implements OnInit
{
    @ViewChild('angularMultiSelect') angularMultiSelect: AngularMultiSelect;

...

onDropdownEvent(event: any) {
        this.isUnselectedOrganization = false;
        this.angularMultiSelect.closeDropdown();
    }
}
```


But when I run I get the following error:  **_"ERROR TypeError: Can not read property 'closeDropdown' of undefined
    at ... this.angularMultiSelect.closeDropdown (); "_**

**Comment by balajun01** [comment]
can you share the code how can i achive the things.

**Comment by psenechal** [comment]
HTML
`
<angular2-multiselect [data]="dropdownList" [(ngModel)]="selectedItems" [settings]="dropdownSettings" (onSelect)="varietalSelected($event)" (onDeSelect)="varietalDeselected($event)" name="batch.varietal" #varietal="ngModel" required></angular2-multiselect>
`
TYPESCRIPT
`
@ViewChild(AngularMultiSelect) varietalDropdown: AngularMultiSelect;
dropdownList = [];
selectedItems = [];
dropdownSettings = {
    singleSelection: true,
    text: 'Select',
    enableSearchFilter: true
};
`
`
public varietalSelected(item: any) {
    const varietalsSelected = this.varietals.filter(varietal => varietal.id = item.id);

    if (varietalsSelected && varietalsSelected.length > 0) {
        this.batch.varietal = varietalsSelected[0];
    }

    this.varietalDropdown.closeDropdown();
}

public varietalDeselected(item: any) {
    this.batch.varietal = null;
    this.varietalDropdown.closeDropdown();
}
`

**Comment by balajun01** [comment]
Thank you @psenechal. 

I have one more question. suppose multiple dropdown using in my form  same i have implemented but close functionality not working the second dropdown.

**Comment by psenechal** [comment]
The ViewChild declaration in the component is element specific. So in your HTML, configure each element with a different ID. In my example, #varietal is the element ID.

Then you'll need to configure a ViewChild entry for each unique element.

Then you should be able to close them individually using the "this.???.closeDropdown()" where ??? is the name you give the ViewChild reference for each element.

**Comment by amantarento** [comment]
@psenechal  I am using  multiple dropdown in my web app close functionality not working the second dropdown.

**Comment by balajun01** [comment]
@psenechal  same issue facing myself also, Please provide code if it is possible .

**Comment by balajun01** [comment]
@psenechal  here have my code,

<angular2-multiselect [data]="environmentList" name="environment" [(ngModel)]="environmentSelected" [settings]="environmentDropdownsettings"
 formControlName="environment" id="environment" (onSelect)="onEnvironmentSelect($event)" (onDeSelect)="OnEnvironmentDeSelect($event)" aria-required="true"> 									</angular2-multiselect>

@ViewChild(AngularMultiSelect) environmentDropdown: AngularMultiSelect;
onEnvironmentSelect(environment: any) {
    this.environmentDropdown.closeDropdown();
  }

<angular2-multiselect [data]="subEnvironmentList" name="subEnvironment" [(ngModel)]="subEnvironmentSelected" [settings]="subEnvironmentDropdownsettings"
 formControlName="subEnvironment" id="subEnvironment" Select)="onSubEnvironmentSelect($event)" (onDeSelect)="OnSubEnvironmentDeSelect($event)"  aria-required="true">						</angular2-multiselect>

@ViewChild(AngularMultiSelect) subEnvironmentDropdown: AngularMultiSelect;
onSubEnvironmentSelect(subEnvironment: any) {
    this.subEnvironmentDropdown.closeDropdown();
  }

The first dropdown can able to close but not in second one .
