### ISSUE TITLE
Issue while assigning data list with id other than number

### ISSUE THREAD

**Issue by sajagekar** [CuppaLabs/angular2-multiselect-dropdown#128]
I have data with example
{
"key" : "CBZ",
"value" : "CARBAMAZEPINE"}

So how do I map this data to list Item which is of type 
export declare class ListItem {
    id: Number;
    itemName: String;
}
Please change it **any** so that We can assign any value to it.

**Comment by CuppaLabs** [comment]
id property is mandatory. Other properties can be any properties.

**Comment by sajagekar** [comment]
thats ok, My problem is type of id should be of type any. So that I can assign any value to it

**Comment by sajagekar** [comment]
Now found the solution as, Please correct me if I am doing wrong

I am assigning [data]  with fixed param as id and itemName and also passing key along with this 
e.g
data = [{"id":1, itemName:"description", "key":"abc"}]

after submitting I am getting same values back, now I am able to find the key.
