### ISSUE TITLE
Allow the component to get focus so it's easy to navigate between elements in page

### ISSUE THREAD

**Issue by gastonelhordoy** [CuppaLabs/angular2-multiselect-dropdown#129]
Hey, amazing work, thanks for sharing it!

I was wondering if it would be possible to modify the internal structure in the component so it can get the focus when navigating with the Tab key.

**Comment by APatsariya** [comment]
Even i need this feature to be implemented very soon along with the navigation using up down arrow. When can we have this?

**Comment by CuppaLabs** [comment]
focus is enabled in the latest version. Please use v3.0.0
