### ISSUE TITLE
Move all console.log calls to wrapper with possibility disable

### ISSUE THREAD

**Issue by AkunaMatata** [CuppaLabs/angular2-multiselect-dropdown#135]
Hello. Could you please add a wrapper for  calling console.log() method ?
 For instance change 
        **console.log(this.chunkArray);**
to
 **if(this.settings.consoleEnable){
     console.log(this.chunkArray);
}**
Many thanks

**Comment by roeir** [comment]
+1

**Comment by CuppaLabs** [comment]
not required. removed.
