### ISSUE TITLE
Not able to use any other key except itemName

### ISSUE THREAD

**Issue by chaudharydeepshikha** [CuppaLabs/angular2-multiselect-dropdown#140]
I'm trying to implement multi-select dropdown but I'm not able to use any key apart from itemName. For example I want to use 'name' instead of the 'itemName'.

**Comment by CuppaLabs** [comment]
Please use the templating feature to use custom property name. Refer to https://cuppalabs.github.io/angular2-multiselect-dropdown/#/templating for this example. If you use templating feature the search filter will also be a mesh search and will search all the properties in the list. For custom property names templating feature is a must. happy coding :)

**Comment by chaudharydeepshikha** [comment]
I implemented using templating feature but when I select options from the dropdown it doesn't display at the top only cross is coming without the selected item name as it's looking for 'itemName' but my json response is having 'name' only.

**Comment by nigelalford** [comment]
I'm having the same issue in Reactive forms. I can't implement the dropdown using a custom property name. Do you have a working example to reference?
