### ISSUE TITLE
console log when scrolling

### ISSUE THREAD

**Issue by SayingsOlly** [CuppaLabs/angular2-multiselect-dropdown#142]
Version 2.3.0
In multiselect.component.js 
`    AngularMultiSelect.prototype.renderChunk = function (fromPos, howMany) {
        this.chunkArray = [];
        this.chunkIndex = [];
        var finalItem = fromPos + howMany;
        if (finalItem > this.totalRows)
            finalItem = this.totalRows;
        for (var i = fromPos; i < finalItem; i++) {
            this.chunkIndex.push((i * this.itemHeight) + 'px');
            this.chunkArray.push(this.data[i]);
        }
        console.log(this.chunkArray);
    };
`
This code is called by scrolling, so it will log the list of select options on the console?

Any chance you guys accidentally left this? any suggestion that I can avoid this?

**Comment by KevinCarnaille** [comment]
I can see they've commit something about these console logs 
https://github.com/CuppaLabs/angular2-multiselect-dropdown/commit/fde8d4ab4dab05247271492dc19e2f3cd3cb3048

Same issue here :)

**Comment by CuppaLabs** [comment]
Please wait for the next deployment this weekend. Happy coding :)

**Comment by CuppaLabs** [comment]
removed
