### ISSUE TITLE
How to implement templating example..

### ISSUE THREAD

**Issue by Vicksdev** [CuppaLabs/angular2-multiselect-dropdown#143]
I have a problem with c-item. Templating is not working. I need to customize the options list in dropdown but its not working. throwing "'c-item' is not a known element" error in console.
Implementing This example
![image](https://user-images.githubusercontent.com/34940881/35136153-e6ca0efc-fd07-11e7-92da-e5887b010e1f.png)

I have this error:
![image](https://user-images.githubusercontent.com/34940881/35136207-2ae7d1a0-fd08-11e7-9ada-81651e8e8225.png)

**Comment by CuppaLabs** [comment]
https://cuppalabs.github.io/angular2-multiselect-dropdown/#/templating. Please take the latest npm version. Tested working as expected.
