### ISSUE TITLE
Multiple Select box width needs to be configured

### ISSUE THREAD

**Issue by Ekta29yadav** [CuppaLabs/angular2-multiselect-dropdown#145]
There is nothing to adjust of width of multiple select box which is need to be auto set not 100%.

I tried to apply the width through CSS using max-width but the dropdown width looks small and the options in dropdown is breaking into lines.

**Comment by CuppaLabs** [comment]
There is a way you can overwrite the css of dropdown without conflict. Please refer to angular documentation to apply global css.
