### ISSUE TITLE
groupBy option is not working for changed data

### ISSUE THREAD

**Issue by Sneha1993-MS** [CuppaLabs/angular2-multiselect-dropdown#147]
First time it is binding data. but next time if i change the data based on some condition,it is not binding, it is displaying old data itself

**Comment by CuppaLabs** [comment]
please refer to https://cuppalabs.github.io/angular2-multiselect-dropdown/#/groupby
working as expected. Example updated to load data dynamically. happy coding :)

**Comment by mandeeps1** [comment]
groupby source/html not visible at https://cuppalabs.github.io/angular2-multiselect-dropdown/#/groupby

**Comment by jjjackpeterson** [comment]
groupby does not woking for dyamic data

Scenario 1. without groupby
I pass dynamic data which is from rest response and doing some data manipulation and assign to the array its working fine.
--------------------------------------------
Scenario 2. with groupby
same above scenario along with groupby its not working showing blank in the dropdown
