### ISSUE TITLE
Show id or other details on Hover.

### ISSUE THREAD

**Issue by makkars** [CuppaLabs/angular2-multiselect-dropdown#150]
Thank you for your remarkable work. 
I am new to Angular and new to your library. 

Is it possible to show certain details on hover? 
Scenario :  You may have two employees having same name but different email address -> 
[{ name : jane doe, email : jane.doe@company.com }, 
{ name : jane doe, email : jane.doe.1@company.com }]

In this case, before selection user can choose between the two of them by their email address.

**Comment by CuppaLabs** [comment]
feature not supported yet.

**Comment by makkars** [comment]
Is this feature is align with your upcoming lib release plan?
If not, we can contribute to it as an enhancement?
