### ISSUE TITLE
Reactive form using multiple selection

### ISSUE THREAD

**Issue by cristianofromagio** [CuppaLabs/angular2-multiselect-dropdown#151]
Is there an example addressing how to implement multiple selection and reactive form? In my case, I'm trying to set the selected items (retrieved async from firebase database) on the multiselect-dropdown, it will update the items displayed (the view), but it throws this error...

```
ERROR TypeError: control.registerOnChange is not a function
    at setUpModelChangePipeline (forms.js:2372)
    at setUpControl (forms.js:2290)
    at eval (forms.js:6796)
    at Array.forEach (<anonymous>)
    at FormGroupDirective._updateDomValue (forms.js:6791)
    at FormGroup.eval [as _onCollectionChange] (forms.js:6810)
    at FormGroup.setControl (forms.js:4406)
    at SafeSubscriber.eval [as _next] (store.component.ts:163)
    at SafeSubscriber.__tryOrUnsub (Subscriber.js:240)
    at SafeSubscriber.next (Subscriber.js:187)
```

...and don't reflect/insert the values in the form control.

More info:
- Line 163 from `store.component.ts` is where I try to update with selected items:
`this.storeForm.setControl('storeSegments', this.fb.array(this.selectedSegments || []));`

- The form creation:

```javascript

  buildForm(): void {

    this.storeForm = this.fb.group({
      // other fields (...)
      storeSegments: [[], [Validators.required]]
    });

    this.subscriptions.add(this.storeForm.valueChanges.subscribe(data => this.onValueChanged(data)));
    this.onValueChanged();
  }

  // validation stuff
  onValueChanged(data?: any) {
    if (!this.storeForm) { return; }
    const form = this.storeForm;
    for (const field of Object.keys(this.formErrors)) {
      this.formErrors[field] = '';
      const control = form.get(field);
      if (control && control.dirty && !control.valid) {
        const messages = this.validationMessages[field];
        for (const key of Object.keys(control.errors)) {
          this.formErrors[field] += messages[key] + ' ';
        }
      }
    }
  }
```

- mutiselect-dropdown in `store.component.html` (if I try to wire ngModel with the selectedSegments array, it will just clear the selectedSegments, as expected, because storeForm.storeSegments length would be 0)

```html
<angular2-multiselect
    [data]="segmentsList"
    [settings]="multiSelectSettings"
    formControlName="storeSegments">
</angular2-multiselect>
```

- Error when trying to select another option
![image](https://user-images.githubusercontent.com/16294559/35471176-132fb0ec-033d-11e8-98c1-255a88e82e10.png)

Did anyone get this to work? To set multiple selected items using reactive forms? Or am I missing something?

**Comment by makkars** [comment]
Hi cristianofromagio
To answer your question!, yes it worked for me like this:
html: 


`          <angular2-multiselect [data]="myOwnOptions" [(ngModel)]="selectedItems" 
                                [settings]="settings" 
                                (onSelect)="onItemSelect($event)"
                                (onDeSelect)="OnItemDeSelect($event)" 
                                (onSelectAll)="onSelectAll($event)" 
                                (onDeSelectAll)="onDeSelectAll($event)" formControlName="own">
          </angular2-multiselect>


        <button type="submit" [disabled]="!userForm.valid" class="btn btn-success btn-block">Submit</button>`

code:
 ` userForm: FormGroup;
  myOwnOptions = [];  // Set your option list
  selectedItems = [];
  settings = {};

    this.settings = {
      limitSelection: 3,
      enableSearchFilter: true,
      text: "Select Students",
      selectAllText: 'Select All',
      unSelectAllText: 'UnSelect All',
      classes: "myclass custom-class"
    };

  createForm() {
    this.userForm = this.fb.group({
      own: [[], Validators.required]
    });
  }

submitForm(f) {
f.own.forEach((item) =>{
console.log(item.id + " " + item.itemName) //anything you want to do.
})
`

**Comment by CuppaLabs** [comment]
Hi, please refer to this example https://cuppalabs.github.io/angular2-multiselect-dropdown/#/usinginreactiveform

**Comment by bogadopedro** [comment]
Hi @cristianofromagio Did you find a solution? I have the same issue
Thanks
