### ISSUE TITLE
Not able to see selected item only cross icon is visible using templating feature.

### ISSUE THREAD

**Issue by chaudharydeepshikha** [CuppaLabs/angular2-multiselect-dropdown#152]
This is in reference with the issue number #140. I implemented using templating feature but when I select options from the dropdown it doesn't display at the selected list, only cross icon is coming, as it's looking for 'itemName' but my json response is having 'name' only.

**Comment by oomz** [comment]
I have the same issue when. Selected items do not display in the dropdown field, only close buttons are displayed.

**Comment by johannesMatevosyan** [comment]
Me also have the same issue. I changed "itemName" property to "username" and the value does not visible any more.

**Comment by CuppaLabs** [comment]
No you can template the selected item badge with v2.5.0. Also, can use custom property names to render the selected badges and the menu items. Please use templating feature to use custom properties. Available in v2.5.0

**Comment by macpatel** [comment]
@CuppaLabs  dosen't seem to work for me @2.9.0 
Replicated->
https://stackblitz.com/edit/angular2-multiselect-dropdown-yebsl5

**Comment by macpatel** [comment]
@chaudharydeepshikha @oomz  @johannesMatevosyan  Can you help ? Check above comment of mine
