### ISSUE TITLE
Templating Badges dynamically based on c-token content

### ISSUE THREAD

**Issue by colinturner** [CuppaLabs/angular2-multiselect-dropdown#155]
I'd like to create a custom badge without touching anything about the menu template. For example, if a user selects "India" from the menu, then a badge should display "India" with the Indian flag to the left of the text in the badge.

I know that you can implement a custom template for the dropdown menu using c-item, but that doesn't seem to help with templating badges (which is what I'm really interested in doing). Also, adding a general class to c-token in the settings is not enough, because I have to dynamically create the class name (e.g. " class='flag-india' ") for each badge in order to get the correct country's flag in each badge.

Is it already possible to template the badges? Thanks!

**Comment by CuppaLabs** [comment]
Hi, please wait for the upcoming release in a week.

**Comment by CuppaLabs** [comment]
done !! new template tag <c-badge> to have custom html in the badge selected item. available in v2.5.0

**Comment by colinturner** [comment]
Thank you!
