### ISSUE TITLE
Constant label text

### ISSUE THREAD

**Issue by JohnnyTriangles** [CuppaLabs/angular2-multiselect-dropdown#156]
I would like the option to have the title text of the dropdown not change to a list of selected inputs when inputs have been selected.

**Comment by gentle9** [comment]
This feature would be nice. And it would be nice to have a icon instead of a title text too. So it would be possible to use the dropdown as a icon button.

**Comment by CuppaLabs** [comment]
Will loose the very meaning of multiselect usage. However having an icon onload instead of test can be applied. Lets think over it and see.
