### ISSUE TITLE
Change the "Search" placeholder text with option

### ISSUE THREAD

**Issue by maximelafarie** [CuppaLabs/angular2-multiselect-dropdown#16]
Allow to customize the placeholder value in the options.

Example : 
![image](https://user-images.githubusercontent.com/5319267/28261903-6facf2fc-6ae1-11e7-99a6-69365ae68fcb.png)

I need to change the value for translation purposes, so it could be useful 😉 

Awesome plugin btw, thank you!

**Comment by CuppaLabs** [comment]
Hey, now this feature is available with v1.1.6. Thanks.
