### ISSUE TITLE
Several instances with singleSelection=true break

### ISSUE THREAD

**Issue by Shemahmforash** [CuppaLabs/angular2-multiselect-dropdown#165]
If we have several instances of the dropdown in the same component with `singleSelection=true` we always get an empty list from all those dropdowns even after selecting a result. It works well and as expected for dropdowns in the same component but without `singleSelection=true`.

**Comment by CuppaLabs** [comment]
working as expected. See example http://localhost:4200/#/multipledropdowns and add the single selection setting
