### ISSUE TITLE
Lazy Loading Throwing Errors when used with groupBy

### ISSUE THREAD

**Issue by vgogov** [CuppaLabs/angular2-multiselect-dropdown#166]
Currently in my ngOnInit() I have:

```
this.dropdownList = [];
this.myService.myArray.forEach(result => {
      this.dropdownList.push(result)
    })
this.dropdownSettings = {
      singleSelection: false,
      text: "Select Fields",
      selectAllText: 'Select All',
      unSelectAllText: 'UnSelect All',
      searchPlaceholderText: 'Search Fields',
      enableSearchFilter: true,
      lazyLoading: true,
      badgeShowLimit: 5,
      groupBy: "category"
    };
```
One the page loads it throws the error of:

> core.es5.js:1084 ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'addEventListener' of undefined
> TypeError: Cannot read property 'addEventListener' of undefined
>     at AngularMultiSelect.webpackJsonp.1351.AngularMultiSelect.ngAfterViewInit

If I remove the 

> groupBy: "category"

It works then.

**Comment by PauloBTX** [comment]
+1

**Comment by cooljeffro** [comment]
+1

**Comment by CuppaLabs** [comment]
Fixed. Please use v3.1.0
