### ISSUE TITLE
Drop Down Not Rendering When Used With ngIf

### ISSUE THREAD

**Issue by slylos** [CuppaLabs/angular2-multiselect-dropdown#167]
We're attempting to use this drop down on a project, and we hide the drop down until some other condition is true (we hide the drop down using *ngIf and e.g. using the drop down in a filter section for a table and only displaying the drop down unless the user adds a secondary filter).  The issue we're seeing is when that condition is true, the drop down appears but the element is only partially rendered until we click somewhere on the page.  

I get the feeling it has something to do with the click-outside directive but I am still debugging; any ideas?

Here's how we're initializing the drop down:

`<div class="col-lg-11 col-md-11 col-sm-10 col-xs-10" *ngIf="filter?.filter?.propertyId == 'states'">
                                <angular2-multiselect class="form-control cls-width-100" name="filterValue{{i}}"
                                                      [data]="dropdownList" [(ngModel)]="filter.values"
                                                      [settings]="dropdownSettings"
                                                      [required]="!filter.isOptional" #filterValue="ngModel">
                                </angular2-multiselect>
                            </div>`

**Comment by monalipatwa** [comment]
Hi @slylos,
I had same issue with ngIf.. then I replace ngIf with [hidden] element instead. Please try these and let me know.. Was it useful or not..

**Comment by CuppaLabs** [comment]
please use [hidden] for rendering logic.

**Comment by srikanthrapolu** [comment]
hidden in place *ngIf does not help in case of ngForm where multiselect is required and hidden, until we select values for multiselect the form wont get valid state
