### ISSUE TITLE
changed default "itemName" into custom property name

### ISSUE THREAD

**Issue by srigar** [CuppaLabs/angular2-multiselect-dropdown#176]
All the object will not contain "itemName". Need to provide an option to choose a custom name. If I used the custom template the number of lines of code gets increased for small changes.
For that, I gave merge request, kindly validate and merge it ASAP. We are using in our project.

Branch Name: **"Custom property name instead of predefined itemName"**
![image](https://user-images.githubusercontent.com/20384652/36710607-10c2dafc-1ba5-11e8-9236-80cba4862695.png)

**Comment by srigar** [comment]
Already I gave merge request.

**Comment by thaoula** [comment]
Can this be further expanded to allow customisation of both the Id field and the ItemName?

Also, will pull request be merged?

**Comment by srigar** [comment]
Still, it is not merged. Waiting for that. Of course, we can expand for ID also.

**Comment by manjurulcis** [comment]
This is useful feature and should be merged as soon as possible

**Comment by CuppaLabs** [comment]
Fixed. Will be available in next release
