### ISSUE TITLE
Lazy loading search returns duplicate items

### ISSUE THREAD

**Issue by SagarJagodra** [CuppaLabs/angular2-multiselect-dropdown#177]
In lazy loading when we search something, the same record gets displayed multiple times,

![screenshot from 2018-02-27 15-31-58](https://user-images.githubusercontent.com/11570300/36722510-b7029b18-1bd3-11e8-9611-8a640b58d115.png)

**Comment by CuppaLabs** [comment]
The example tht you are referring to, the mock data has the same label as it is randomized. Test with your real data. if issue persiste reopen this issue.
