### ISSUE TITLE
detox issue while running react-native test cases with jest framework

### ISSUE THREAD

**Issue by policz** [CuppaLabs/angular2-multiselect-dropdown#178]
__tests__\index.android.js
  ● Test suite failed to run

    Cannot find module 'detox' from 'setup.js'

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:191:17)
      at Object.<anonymous> (jest/setup.js:5:33)

# my packet.json detox script

    	"detox": {
		"configurations": {
			"ios.sim.debug": {
				"binaryPath": "ios/build/Build/Products/Debug-iphonesimulator/EHS.app",
				"build": "xcodebuild -project ios/EHS.xcodeproj -scheme EHS-dev -configuration 
                                 Debug -sdk iphonesimulator -derivedDataPath ios/build",
				"type": "ios.simulator",
				"name": "iPhone 7"
			}
		}
	}

**Comment by CuppaLabs** [comment]
not related to this component.
