### ISSUE TITLE
Data filter should work to get data from server

### ISSUE THREAD

**Issue by nrbokade** [CuppaLabs/angular2-multiselect-dropdown#186]
Hello,
I have used multiselect-dropdown in many forms, where I need to get data filtered by server,
I does not get any Emitted method to handle such event in AngularMultiSelectModule.

Thanks in advance.

**Comment by CuppaLabs** [comment]
feature available in v2.9.0 . refer example https://cuppalabs.github.io/angular2-multiselect-dropdown/#/customSearchAPI
