### ISSUE TITLE
Not able to see the cross icon on the item.

### ISSUE THREAD

**Issue by satinsanghi** [CuppaLabs/angular2-multiselect-dropdown#187]
Did everything correctly according to instructions. Also have the font awesome dependency (not pro version) included in the angular project but still cannot see the cross icon to remove the selected item.

I added the reference to font awesome in my index.html file as follows:
<script defer src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>

Is there anything else that I need to do?

**Comment by rahulFortunekit** [comment]
I have same problem,i just installed the plugin and used it in my prject but it does not showing close icon after selecting multiple item

**Comment by CuppaLabs** [comment]
You need to include font-awesome css in angular-cli.json file as follows
 "styles": [
        "styles.css","main.css","../node_modules/font-awesome/css/font-awesome.min.css",
        "../node_modules/primeng/resources/themes/omega/theme.css",
        "../node_modules/primeng/resources/primeng.min.css"
      ]
