### ISSUE TITLE
Change default 'id' field

### ISSUE THREAD

**Issue by victorlm125** [CuppaLabs/angular2-multiselect-dropdown#188]
I have a complex database so I can't named 'id' for all primary keys. I need use different id's to work with. Exemple: IdGroup, IdCenter, etc..

I can't use these primary keys as identificators in the multiselect control because it only understand 'id' as identificator.

**Comment by shaolinshaosson** [comment]
+1

**Comment by mrsuel** [comment]
+1

**Comment by jbaan** [comment]
+1

**Comment by pratik97** [comment]
+1

**Comment by dhavalpatel7** [comment]
+1

**Comment by CuppaLabs** [comment]
feature available in v2.8.0. Please use primaryKey property in settings.
