### ISSUE TITLE
Position dropdown like bootstrap is behaving

### ISSUE THREAD

**Issue by jbaan** [CuppaLabs/angular2-multiselect-dropdown#190]
In bootstrap 4 the dropdow is positioning according the space available. So in case below the multiselect not enough space is there, then the dropdown will open on top of the input area. I'm expecting this behavior also for this multiselect dropdown, how can this be reached?

**Comment by CuppaLabs** [comment]
Please implement this enhancement and raise a pull request.

**Comment by jbaan** [comment]
@CuppaLabs  Please find the solution in pull request #250
