### ISSUE TITLE
Search box does not clear when exiting dropdownlist when lazy loading is enabled.

### ISSUE THREAD

**Issue by SeanVSpr** [CuppaLabs/angular2-multiselect-dropdown#197]
I have a fairly large amount of queryable items so I opted in using lazy loading with the dropdownlist.
However when you enable both Lazyloading and Searchfilter the search box does not clear after clicking outside of the dropdown. Whereas it does with lazy loading disabled.
Config:
{
      text: "Click here to select items",
      enableCheckAll: false,
      enableSearchFilter: true,
      lazyLoading: true
 };

This issue is also noticeable in the lazy loading demo section:
https://cuppalabs.github.io/angular2-multiselect-dropdown/#/lazyloading

e.g. Type "li" in the search box then select an item and click outside of it. When you then click later on the dropdown it will still have "li" in the search field and the list will only be the filtered list. 

What is to be expected is that the search box clears like it does when lazy loading is disabled. This is similar to #44

**Comment by CuppaLabs** [comment]
fixed available in latest version

**Comment by prasanna-ui** [comment]
search bar space and result of that is not getting cleared when lazy loading is enabled.
