### ISSUE TITLE
Observable of Settings

### ISSUE THREAD

**Issue by kshkrao3** [CuppaLabs/angular2-multiselect-dropdown#199]
Is it possible to update the `settings` dynamically? I tried by providing `Observable.of({....})` and with `async` pipe on `[settings]` but it was not updating. This request arise when I had to dynamically disable the `select dropdown` based on one of the `checkbox` value of `formcontrol`. Or it will be good if we move `disabled` attribute outside the `settings`

**Comment by CuppaLabs** [comment]
Please refer to https://cuppalabs.github.io/angular2-multiselect-dropdown/#/disablemode. New setting object can be created and re-assigned. As of now you can do this way, to get you going.
