### ISSUE TITLE
CSS Override

### ISSUE THREAD

**Issue by ariasfernando** [CuppaLabs/angular2-multiselect-dropdown#2]
Hi! Do you have any way to override default css styles in your component? I wouldn't want to modify them inside the package and loose after an update. Thanks!

**Comment by ariasfernando** [comment]
Hi @CuppaLabs ! Could you estimate when would you have this enhancement applied? Thanks!

**Comment by CuppaLabs** [comment]
You should be getting the change by tomorrow.

**Comment by CuppaLabs** [comment]
fixed.
