### ISSUE TITLE
Keep always one item selected in single selection mode

### ISSUE THREAD

**Issue by rudolf-gitler** [CuppaLabs/angular2-multiselect-dropdown#203]
I would like to to be able to force that always one item is selected  for `singleSelection: true`. 
Currently an selected item can be unselected and I haven't found a setting option to prevent this.

So I implemented the following as a work around:
```  
onDeselectKw(event) {
    this.itemSelected = [event];
  }
```
This way there is always one item selected, but the window does not close if the already selected item is selected again.

It would be nice if there were a setting option like `preventUnselect: boolean`

**Comment by CuppaLabs** [comment]
single selection mode it to make sure that only one item is selected at a time. The selected items can be managed through selected-items array.

**Comment by rudolf-gitler** [comment]
My issue was not about having at least one item selected. I was asking for having always one item selected in single selection mode without the possibility to unselect that item.
