### ISSUE TITLE
HTML parts of the examples are not visible

### ISSUE THREAD

**Issue by xameeramir** [CuppaLabs/angular2-multiselect-dropdown#205]
HTML parts of the examples are not visible

**Comment by CuppaLabs** [comment]
they are visible. Verified.

**Comment by xameeramir** [comment]
Are you able to see html example code at https://cuppalabs.github.io/angular2-multiselect-dropdown/#/basic ?

**Comment by CuppaLabs** [comment]
yes i am able to see 
![image](https://user-images.githubusercontent.com/3957664/38102433-d7083ffa-33a0-11e8-9fe4-f79902786fc7.png)

**Comment by xameeramir** [comment]
Then I probably have some blocker which is not allowing me to view this. Thanks anyways and apologies for inconveniences.
