### ISSUE TITLE
Dropdown Options disappear when clicked outside Plugin

### ISSUE THREAD

**Issue by vikramjeet93** [CuppaLabs/angular2-multiselect-dropdown#207]
We are facing the issue in 2.6.0. (2.5.0 and earlier versions works fine)

When we click on the drop-down to view options or hide them, this plugin works as intended. When we click outside the plugin, and then click again on plugin, the drop-down options disappear. (Selected options remain as it is and works as intended)

**Comment by CuppaLabs** [comment]
works as expected. please check demo pages for reference.

**Comment by ariel-santos** [comment]
I have the same problem and the demo pages not help me.

Can someone help?

**Comment by sandeep2701kumar** [comment]
same issue please help

**Comment by CuppaLabs** [comment]
Point taken. Will be resolved soon

**Comment by sandeep2701kumar** [comment]
It's a version problem degrade the version of angular2-multiselect-dropdown to 2.4.0 and this will work fine.

**Comment by CuppaLabs** [comment]
not able to replicate. Create a stackblitz example @ https://stackblitz.com/edit/angular2-multiselect-dropdown. 
please editing the code there and replicate the issue and report.

**Comment by CuppaLabs** [comment]
Please update the stackblaze example, replicate the issue and reopen the issue. As of now not able to reproduce the issue.
