### ISSUE TITLE
Data binding from [data] is buggy

### ISSUE THREAD

**Issue by kunalgrover05** [CuppaLabs/angular2-multiselect-dropdown#208]
Tested numerous times with updating [data] variable array.

Binding does not work for a lot of cases. I am still not able to identify a Unit test which shows that, but something that is surely a bug.

**Comment by kunalgrover05** [comment]
Use-case: Multiple dropdowns which act as filter for others. Usually, selecting items in one dropdown leads to other dropdowns having some lesser data.

Current workaround is to always reset the original array size first using:  
    ```this.array.length = 0;```
and followed by assigning the array to values.
Without this, the original items are still shown.

**Comment by CuppaLabs** [comment]
Can you see how changing data works in this example https://cuppalabs.github.io/angular2-multiselect-dropdown/#/groupby

**Comment by CuppaLabs** [comment]
please list down the numerous use cases that does not work and determine what is that "something is buggy" clearly and specifically and reopen the issue again.

**Comment by kunalgrover05** [comment]
I wrote a test component which reproduces the issue.

```

**Comment by kunalgrover05** [comment]
@CuppaLabs Sorry I don't have rights to open this issue again, can you do the same?

**Comment by CuppaLabs** [comment]
Can you replicate the issue at https://stackblitz.com/edit/angular2-multiselect-dropdown. Then create a new issue.
