### ISSUE TITLE
showing no data when two are use together with different object

### ISSUE THREAD

**Issue by sandeep2701kumar** [CuppaLabs/angular2-multiselect-dropdown#209]

**Comment by CuppaLabs** [comment]
@sandeep2701kumar  Can you replicate the issue at https://stackblitz.com/edit/angular2-multiselect-dropdown

**Comment by CuppaLabs** [comment]
Please update the stackblaze example, replicate the issue and reopen the issue. As of now not able to reproduce the issue.
