### ISSUE TITLE
Custom Name

### ISSUE THREAD

**Issue by ccocker** [CuppaLabs/angular2-multiselect-dropdown#21]
Hi,

If i understand correctly the multi-select will only work correctly if the array of objects being supplied has a property called ItemName.  Is that correct or can you specify a setting that allows you to specify the property to be used for the itemName?

For example if i had 

`this.dropdownList = products;`

products object looked like this 

```
[
       {"id":1,"productTitle":"Oracle"},
       {"id":2,"productTitle":"SAP"},
 ];
```

**Comment by CuppaLabs** [comment]
Hi,
I don't think we should make the object property names generic. There is no way to identify which property belong to the name field and even if we do with the property index number, it would make the data structure unusable for any data manipulations.. Not feasible, hence closing the issue.
