### ISSUE TITLE
Cannot read property 'length' of undefined     at AngularMultiSelect.closeDropdown

### ISSUE THREAD

**Issue by sandeep2701kumar** [CuppaLabs/angular2-multiselect-dropdown#210]

**Comment by CuppaLabs** [comment]
@sandeep2701kumar  can you please replicate the issue at https://stackblitz.com/edit/angular2-multiselect-dropdown

**Comment by CuppaLabs** [comment]
Please update the stackblaze example, replicate the issue and reopen the issue. As of now not able to reproduce the issue.
