### ISSUE TITLE
On search how to load the list on demand(through an API)

### ISSUE THREAD

**Issue by santoshkumarsuru** [CuppaLabs/angular2-multiselect-dropdown#214]
Is there any event that triggers on search so that i can do a ajax call and load my list dynamically

**Comment by santoshkumarsuru** [comment]
When it will be completed?

**Comment by Zheness** [comment]
We are still waiting for #148 to be merged. That could resolve this issue.
Any updates on the PR ?

**Comment by CuppaLabs** [comment]
feature available in v2.9.0
