### ISSUE TITLE
Search By Index is not working in Group By Option

### ISSUE THREAD

**Issue by kiran3490** [CuppaLabs/angular2-multiselect-dropdown#218]
Search By Index is working here ONLY.
https://cuppalabs.github.io/angular2-multiselect-dropdown/#/searchfilter

This feature should also work along with Group By If you can implement.
https://cuppalabs.github.io/angular2-multiselect-dropdown/#/groupby

##FEATURE REQUEST##
Suggestion for implementation.
Question : Which item to search (Parent/child items) ?
We can use below syntax.
2 (Second Parent)
2:1 (Second Parent : First Child)
2 (Second Parent)
*:5 (Any Parent : Fifth Child)

**Comment by CuppaLabs** [comment]
Search filter implementation is only for the row item properties and not the group headers. Redundant requirement. Hence closing the issue.

**Comment by kiran3490** [comment]
Ok
