### ISSUE TITLE
select all is not gets checked in automatically

### ISSUE THREAD

**Issue by V2NileshSukalikar** [CuppaLabs/angular2-multiselect-dropdown#219]
When selectedItems contains all the data during initialization, drop-down doesn't check in select all button automatically.

If i have such data during initialization

this.itemList = [
			{ "id": 1, "itemName": "India" },
			{ "id": 2, "itemName": "Singapore" },
			{ "id": 3, "itemName": "Australia" },
			{ "id": 4, "itemName": "Canada" },
			{ "id": 5, "itemName": "South Korea" },
			{ "id": 6, "itemName": "Brazil" }
		];

		this.selectedItems = [
			{ "id": 1, "itemName": "India" },
			{ "id": 2, "itemName": "Singapore" },
			{ "id": 3, "itemName": "Australia" },
			{ "id": 4, "itemName": "Canada" },
			{ "id": 5, "itemName": "South Korea" },
			{ "id": 6, "itemName": "Brazil" }];

		this.settings = {
			text: 'Select Countries',
			selectAllText: 'Select All',
			unSelectAllText: 'UnSelect All',
			classes: 'myclass custom-class',
			enableSearchFilter: true,
		};

then clicking on dropdown , select all check box should be checked in

**Comment by CuppaLabs** [comment]
Working correctly. Please see the example of your use case here https://stackblitz.com/edit/angular2-multiselect-dropdown
