### ISSUE TITLE
Issues faced with template driven form

### ISSUE THREAD

**Issue by sneharghya** [CuppaLabs/angular2-multiselect-dropdown#22]
I am using the angular2-multiselect component inside a model driven form. Following is my html markup:
 ```
<form #dynamicform="ngForm" novalidate="" class="form-inline">
                   <angular2-multiselect [settings]="dataMap.role?.multiSelectSettings" 
                                    [data]="dataMap.role?.options" name="role" #role="ngModel" 
                                    [(ngModel)]="pageMap.role"
                                        id="role"></angular2-multiselect>
 </form>
```

Inside the component, I have the following code:
```
this.dataMap['role']={};
        var dropdownList = [
                              {"id":1,"itemName":"India"},
                              {"id":2,"itemName":"Singapore"},
                              {"id":3,"itemName":"Australia"}
                              
                            ];

        this.dataMap['role']['options']=dropdownList;
        this.pageMap['role'] = [
                                {"id":1,"itemName":"India"}
                            ];
        var dropdownSettings = { 
                                  singleSelection: false, 
                                  text:"Select Countries",
                                  selectAllText:'Select All',
                                  unSelectAllText:'UnSelect All',
                                  enableSearchFilter: true,
                                  classes:"myclass custom-class"
                                }; 
                                
        this.dataMap['role']['multiSelectSettings']=dropdownSettings;
```
An am getting the following error in console: Error in ./AngularMultiSelect class AngularMultiSelect - inline template:35:35 caused by: Cannot read property 'forEach' of undefined.

But if i remove the `form` tag and use the following markup, then everything works fine:
```
<angular2-multiselect [settings]="dataMap.role?.multiSelectSettings" 
                                    [data]="dataMap.role?.options" name="role" #role="ngModel" 
                                    [(ngModel)]="pageMap.role"
                                        id="role"></angular2-multiselect>
```

**Comment by NileshPatel17** [comment]
@CuppaLabs this component works fine with reactive forms. but to use with template forms, name atttribute must be set for the control.
<form #f="ngForm">
          <angular2-multiselect name="state" [data]="basicExampleList" [(ngModel)]="basicExampleSelectedItems" [settings]="basicExampleSettings" ></angular2-multiselect>
        </form>
but this will fix the issue. there is a bug in the code. this.selectedItems is null. So, needs to put not null check in isSelected() function like below.

isSelected(clickedItem:ListItem){
        let found = false;
        this.selectedItems && this.selectedItems.forEach(item => {
           if(clickedItem.id === item.id){
               found = true;
           }
        });
        return found;
    }

If you do not mind, i can send PR for this :)
Would definitely like to see my name in contribution list :)
Thanks!
Nilesh Patel
