### ISSUE TITLE
Custom JSON data

### ISSUE THREAD

**Issue by samir-kamble** [CuppaLabs/angular2-multiselect-dropdown#224]
Hello,

I have data of type

       {
		ArrayName : [{
			b: "item Name",
			a: "ab123"
		}, {
			b: "another item name",
			a: "ab234"
		}, …]
	}

Where 'a' is id and 'b' is itemname. But it is not getting rendered inside drop down.

Can you please help.

Regards,
Sam

**Comment by CuppaLabs** [comment]
read configuration settings to define label key and primary key properties.
