### ISSUE TITLE
There option no option to give the User typed text(free text) in the dropdown list

### ISSUE THREAD

**Issue by santoshkumarsuru** [CuppaLabs/angular2-multiselect-dropdown#225]

**Comment by CuppaLabs** [comment]
need clarity on this. Could you please explain clearly ?

**Comment by santoshkumarsuru** [comment]
Yeah,
If user is trying to search for something in the list.. if it is not there in the list.. can i populate tht value in the list dynamically??

**Comment by CuppaLabs** [comment]
redundant requirement. Search functionality should not be adding new items, Just search what is in list. However, upcoming feature is search through service API. which might help you.
