### ISSUE TITLE
Option to sort matches with n-grams or pass custom filtering/sorting method.

### ISSUE THREAD

**Issue by Emn1ty** [CuppaLabs/angular2-multiselect-dropdown#227]
The current filtering is highly inaccurate although suitable for simple task. Unfortunately it matches some very arbitrary things (especially when it comes to numeric comparisons). Current solution is going to be extending the component to override the comparison operation.

Would it be possible to build in n-grams or allow a comparison and sorting function be passed in?

**Comment by CuppaLabs** [comment]
Hi, the search functionality is a mesh search, i.e the keyword is matched with all the key value pairs in the object of the array. So you might see list with only the label but might not match with the search keyword, but it must have matched with other properties in the same object.

**Comment by Emn1ty** [comment]
Ah, alright that makes sense. Still, it might be useful to allow the filtering and sorting be overridden. It's very confusing from a UX perspective when results appear that don't seem remotely related to what I've typed.

**Comment by CuppaLabs** [comment]
Advanced and custom search / search API is in pipeline for this weeks release.

**Comment by CuppaLabs** [comment]
Advanced search. "searchBy" configuration available in v2.9.0
