### ISSUE TITLE
Angular - multiselect dropdown refresh is not working

### ISSUE THREAD

**Issue by SDhondkar** [CuppaLabs/angular2-multiselect-dropdown#230]
I have options selected in dropdown but dropdown doesn't get refreshed (original state of unselected checkbox) after calling below code.

onItemDeSelectAll(event){
    this.removePlaceholder("test")
		this.selectedItem=[]
  }

![image](https://user-images.githubusercontent.com/15892403/38924153-c58ca65c-4319-11e8-8419-6982eaa62d87.png)

Am I missing anything?

**Comment by CuppaLabs** [comment]
Please refer to https://cuppalabs.github.io/angular2-multiselect-dropdown/#/basic. Works as expected. Not clear what your requirement is. Please drop a mail if any implementation issues. Hence closing.
