### ISSUE TITLE
Can't see data list in drop down

### ISSUE THREAD

**Issue by AbhijitMuke** [CuppaLabs/angular2-multiselect-dropdown#232]
Can you please help me out data list in drop down - [Plnkr](https://plnkr.co/edit/gG59W5)

**Comment by CuppaLabs** [comment]
Hi. In wrapper.component.ts line# 49 you are emptying the array. Very obvious you would not see the list. Comment this line and see, it works. 
PS. Please raise only bugs related to the component here. For any help on implementations do drop a mail to me. happy coding :)
