### ISSUE TITLE
Alignment Issue 

### ISSUE THREAD

**Issue by h0ujun** [CuppaLabs/angular2-multiselect-dropdown#237]
Anyone know why the filters are like these?

![image](https://user-images.githubusercontent.com/13286101/39293526-ae5c3ecc-496b-11e8-90fc-d77b8bd91dd7.png)

Thanks!

**Comment by CuppaLabs** [comment]
@h0ujun Please refer to https://stackblitz.com/edit/angular2-multiselect-dropdown . Please make sure you have installed the package properly
