### ISSUE TITLE
tab index not working

### ISSUE THREAD

**Issue by RahulShahUI** [CuppaLabs/angular2-multiselect-dropdown#240]
when i press tab button it will skip the multiselectdropdown.

**Comment by mkginfo** [comment]
Any update regarding this issue.

**Comment by RahulShahUI** [comment]
not yet

**Comment by mkginfo** [comment]
So what is the alternative for tabindex.

**Comment by parmodmalik** [comment]
any update on this.

**Comment by CuppaLabs** [comment]
work in progress

**Comment by parmodmalik** [comment]
any update on this.

**Comment by parmodmalik** [comment]
Any workaround for this issue? Please suggest.

**Comment by CuppaLabs** [comment]
fixed. Fix available in latest version. v2.10.2

**Comment by CuppaLabs** [comment]
Refer example http://localhost:4200/#/usinginform for the fix

**Comment by JitMondal** [comment]
Can you please provide the actual URL as the above mentioned URL is incorrect!!

**Comment by seraries** [comment]
When I tab to the dropdown, it highlights it but I cannot actually open the dropdown (neither enter nor space key work)

**Comment by Ankit8010** [comment]
it seems they have fixed something else.
