### ISSUE TITLE
Select All Doesn't Select Filtered Results

### ISSUE THREAD

**Issue by shubh28** [CuppaLabs/angular2-multiselect-dropdown#242]
I am trying to implement multiselect functionality. When I am searching the data is filtered but when I am clicking on select all it selects all the elements rather than just selecting the filtered elements. How can I implement such functionality? Thanks

**Comment by SayingsOlly** [comment]
@shubh28 
I also have this problem recently...
hope next version, it will have a config item like : isSelectAllAppliedFilter: boolean

this is my workaround:

onSelectAllChange() {
        const filteredSelectedItemNames = [];
        this.elRef.nativeElement.querySelectorAll('li.pure-checkbox > label').forEach(node => {
            filteredSelectedItemNames.push(node.innerText);
        });
        this.selectedItems = this.selectedItems.filter(i => filteredSelectedItemNames.indexOf(i.itemName) > -1);
        this.onItemSelectionChange();
    }

    onDeSelectAllChange() {
        const filteredSelectedItemNames = [];
        this.elRef.nativeElement.querySelectorAll('li.pure-checkbox > label').forEach(node => {
            filteredSelectedItemNames.push(node.innerText);
        });
        this.selectedItems = this.loadedValues.filter(i => filteredSelectedItemNames.indexOf(i.itemName) <= -1);
        this.onItemSelectionChange();
    }

**Comment by WillGeller** [comment]
I would also love this feature. I will try @SayingsOlly work around for now.

**Comment by dertdog** [comment]
@CuppaLabs, would you be able to comment on this issue? Do you agree with us that this is undesired behavior?

**Comment by MiRush94** [comment]
Came across this ssame issue, please implement it in the next version, this is something that many of us would like to have and would use a lot.

**Comment by MiRush94** [comment]
@SayingsOlly , do you maybe have a stackblitz for your workaround? would like to try it out.
thanks in advance :)

**Comment by CuppaLabs** [comment]
New feature added in v2.10.0. Use new property 'enableFilterSelectAll' to select all the filtered results. Example at https://cuppalabs.github.io/angular2-multiselect-dropdown/#/searchfilter

**Comment by Indranilkundu1993** [comment]
When we are selecting Select All from the filtered result, which callback method is being used?
