### ISSUE TITLE
Addition of custom option

### ISSUE THREAD

**Issue by thedarkdestructor** [CuppaLabs/angular2-multiselect-dropdown#243]
Hi,

did you consider the possibility to add custom options to the dropdown? 

We require this feature for an application we are developing... something similar to what is doing [this component ](https://github.com/ng-select/ng-select) where is possbile to **add a custom option in the select component**.

Thanks in advance for the support :)

**Comment by thedarkdestructor** [comment]
No news?

**Comment by CuppaLabs** [comment]
Similar features are available by the use of settings configuration object.
