### ISSUE TITLE
SVG tags compatibility with Safari and mobile

### ISSUE THREAD

**Issue by jcaninov** [CuppaLabs/angular2-multiselect-dropdown#249]
Hi!
We've found an issue with the SVG html tags used to render icons (close icon on badges, search icon). It doesn't work properly on Safari, some mobile phones, and Iphones. 
This tag could easily be replaced with special fonts (glyphicons), or a simple image.

Thanks

**Comment by ubaid-rehman** [comment]
+1

**Comment by CuppaLabs** [comment]
Works as expected.  Tested on safari mobile in iphone. If still the error persists, check your html tag with the html5 standards
