### ISSUE TITLE
If I select one option It selects all options for single select dropdown

### ISSUE THREAD

**Issue by dharmarajan** [CuppaLabs/angular2-multiselect-dropdown#252]
![selection_isuue](https://user-images.githubusercontent.com/11973262/40539742-58709b5a-6033-11e8-94d0-b8d2f9d0e3a7.PNG)

I have selected the above first option(xyzq). But It selected all other options.

**Comment by Rjitendra** [comment]
change id

**Comment by Rjitendra** [comment]
this.schoolNames.push({'id': illness.data.GetSchool[i].schoolID , 'itemName': illness.data.GetSchool[i].SchoolName});

**Comment by impuneet** [comment]
ID change of what ??

**Comment by impuneet** [comment]
<angular2-multiselect [data]="schools" [(ngModel)]="schoolModal" [settings]="dropdownSettings1" (onSelect)="onItemSelect($event)"
           >
            <c-badge>
                <ng-template let-item="item">
                    <label style="margin: 0px;">{{item.name}}</label>
                </ng-template>
            </c-badge>

            <c-item>
              <ng-template let-item="item">
                <label style="color: #333;min-width: 150px;">{{item.name}}</label>
              </ng-template>
            </c-item>
          </angular2-multiselect>

**Comment by impuneet** [comment]
Do I need to change the ID of  the angular2-multiselect

**Comment by CuppaLabs** [comment]
please use unique ID for individual option in the list.

**Comment by manavdahra** [comment]
If anyone is still stuck, then to elaborate... 
What is expected is that the list bound to **[data]** property must have an **id** field in the array of objects. Eg. {id: '<some unique id>', itemName: '<some name>'}
angular2-multiselect picks up "id" property and assigns it to <input type="checkbox"> element under the hood. Add that property using your own unique id if it does not exists in the list.
