### ISSUE TITLE
Question about CSS styling

### ISSUE THREAD

**Issue by meyer20** [CuppaLabs/angular2-multiselect-dropdown#254]
Hi,

I'm trying to apply my custom CSS, and i try'ed to follow the instructions of documentation, but doesn't worked. The style must be in the component, in the main app, or i have to use ViewEncapsulation?

Thanks

**Comment by meyer20** [comment]
I added the styles in global CSS and it worked!

**Comment by macpatel** [comment]
@meyer20 i tried adding this in global styles but it didn't work. Any idea ?

```
.selected-list .c-btn{
  box-shadow: none;
}
```

**Comment by meyer20** [comment]
@macpatel try to use the `!important` in all your styles, worked for me.

**Comment by nikhilghodke17** [comment]
Hi @macpatel ,

- Pass a custom class with 'classes' attribute to dropdown settings. 
- Add styling to that class at global style sheet in angular application.
- Use [css descendant selector](https://www.w3schools.com/css/css_combinators.asp) for overriding the styling of dropdown.

**Comment by macpatel** [comment]
@meyer20 Thanks. for me it worked.

@nikhilghodke17 thanks for this alternate tip.
