### ISSUE TITLE
custom class not working 

### ISSUE THREAD

**Issue by suresh2018** [CuppaLabs/angular2-multiselect-dropdown#255]
.selected-list .c-btn {   
height: 38px!important;  
 box-shadow: none !important;  
 }

this class not working ...
also not working custom-class

**Comment by gentle9** [comment]
I have the same issue and I can´t add the styles to the global css because I want to use themes to change the style on the fly.

**Comment by meyer20** [comment]
@gentle9 maybe the ViewEncapsulation can help you (https://angular.io/guide/component-styles)

**Comment by gentle9** [comment]
@meyer20 I already tried to change the ViewEncapsulation on my components but without success.

**Comment by nikhilghodke17** [comment]
**Custom class is not working.**

`.custom-class-example {
    color: #ccc;
}
.custom-class-example .c-token{
    background: #38d574 !important;
}
.custom-class-example .pure-checkbox label::before {
    border-color: #38d574 !important;
}
.custom-class-example .pure-checkbox input[type="checkbox"]:checked + label[_ngcontent-c1]:before {
    background: #38d574 !important;
}`

> As shown in here [https://cuppalabs.github.io/angular2-multiselect-dropdown/#/styling](url)

**Comment by CuppaLabs** [comment]
Works as expected. You should add the custom classes in the global css file and include it in .angular-cli.json file

**Comment by tecssil** [comment]
Hello,
I went through this problem and as other people point out, it's true that a custom class won't work when it's load from a different component on its css file, as this file is not in the .angular-cli.json. It should be a new feature, to be able to style the dropdown from the component css instead of the global css file.
Thanks
