### ISSUE TITLE
Dropdown alignment issue in responsive table

### ISSUE THREAD

**Issue by ramyalatha-redpinesignals** [CuppaLabs/angular2-multiselect-dropdown#256]
On click on the drop-down in the responsive table, the elements are hidden it should not be like that and dropdown should be enabled on top of the table 
![drodownissue](https://user-images.githubusercontent.com/19818129/40906099-6d89d82c-67fd-11e8-948b-de41ed532843.PNG)

**Comment by CuppaLabs** [comment]
try applying z-index to 9999999 via the global CSS

**Comment by ramyalatha-redpinesignals** [comment]
@CuppaLabs I already tried by applying z-index its doesn't work.

**Comment by CuppaLabs** [comment]
@ramyalatha-redpinesignals I think you are controlling the scroll with a div elemt surrounding the table. in that case there is no way it shows outside the div area. You need to workaround with your css. As this is no issue with component, closing the issue.
