### ISSUE TITLE
Search filter is not working while accessing in mobile desktop version

### ISSUE THREAD

**Issue by VenkiMit04** [CuppaLabs/angular2-multiselect-dropdown#258]
I noticed the search filter doesn't work with mobile desktop version. On blur, it seems to be filter but on the keypress event doesn't seem to filter. It happens only when I request for desktop version in mobile browser.
I tested in chrome mobile browser.

**Comment by CuppaLabs** [comment]
Works as expected . Tested in mobile safari browser in iphone.

**Comment by VenkiMit04** [comment]
I could see still the issue persist. Steps to reproduce
1) Browse the website in mobile browser
2) Switch to desktop version
3) Access the multi-dropdown. on typing, the results dont get filter
