### ISSUE TITLE
Hiding dropdown behind the div 

### ISSUE THREAD

**Issue by sai401** [CuppaLabs/angular2-multiselect-dropdown#260]
I am using angular 5 and angular material.I have added the dropdown inside the angular material mat-card tag.but dropdown  is not appearing fully instead it is hiding some part into mat-card tag.
![capture](https://user-images.githubusercontent.com/20453732/41906284-2055fae4-795b-11e8-8d5f-516a21a7d56a.PNG)

**Comment by macpatel** [comment]
@sai401  try
```
.dropdown-list{
position: fixed !important;
}
```

**Comment by tishansoft** [comment]
I have the same problem. This solution doesn't seem to fix the issue.

**Comment by CuppaLabs** [comment]
use global css relative to your containers css and manage. Component explicitly cannot manage this.
