### ISSUE TITLE
missing major dev dependency

### ISSUE THREAD

**Issue by atljoseph** [CuppaLabs/angular2-multiselect-dropdown#261]
please run this and re-up the version after committing!
```npm install --save-dev @fortawesome/angular-fontawesome```

**Comment by atljoseph** [comment]
actually missing more. please update this so i can reliably reproduce an issue your lib has!

**Comment by CuppaLabs** [comment]
font-awesome is no more required as the images used in the dropdown are svg inline images.

**Comment by atljoseph** [comment]
please update the repo
