### ISSUE TITLE
The command "npm run vs_build_prod" exited with code 1 when trying to publish

### ISSUE THREAD

**Issue by gauravpatni123** [CuppaLabs/angular2-multiselect-dropdown#266]
Hi i am getting and error while publishing my project . Its is working fine in my local but when i am trying to publish it , publish failed with below error , can anyone please help and in the documentation  there is no help for how to map angular multi select in 'Systemjs.config.js' file.

6>------ Publish started: Project: Pyramid.Staffing.Api, Configuration: Release Any CPU ------
6>Connecting to E:\StaffingPublish...
6>Transformed Web.config using E:\Pyramid Staffing Project1\Development\Pyramid.Staffing\Pyramid.Staffing.Api\Web.Release.config into obj\Release\TransformWebConfig\transformed\Web.config.
6>Deploy | Copying angular files to root along with appbundle.min.js)
6>npm run vs_build_prod
6>
6>> aspnet@1.0.0 vs_build_prod E:\Pyramid Staffing Project1\Development\Pyramid.Staffing\Pyramid.Staffing.Api
6>> npm run copy_html_css_prod && browserify -s main ./ng2/app/main.js > ./appbundle.js && npm run minify
6>
6>
6>> aspnet@1.0.0 copy_html_css_prod E:\Pyramid Staffing Project1\Development\Pyramid.Staffing\Pyramid.Staffing.Api
6>> copyfiles -f ./ng2/app/**/*.html ./ng2/app/**/*.css ./
6>
6>
6>E:\Pyramid Staffing Project1\Development\Pyramid.Staffing\Pyramid.Staffing.Api\node_modules\angular2-multiselect-dropdown\index.js:1
6>export { AngularMultiSelect } from './multiselect.component';
6>^
6>ParseError: 'import' and 'export' may appear only with 'sourceType: module'
6>npm ERR! code ELIFECYCLE
6>npm ERR! errno 1
6>npm ERR! aspnet@1.0.0 vs_build_prod: `npm run copy_html_css_prod && browserify -s main ./ng2/app/main.js > ./appbundle.js && npm run minify`
6>npm ERR! Exit status 1
6>npm ERR! 
6>npm ERR! Failed at the aspnet@1.0.0 vs_build_prod script.
6>npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
6>
6>npm ERR! A complete log of this run can be found in:
6>npm ERR!     C:\Users\gauravp\AppData\Roaming\npm-cache\_logs\2018-07-17T10_43_14_720Z-debug.log
6>E:\Pyramid Staffing Project1\Development\Pyramid.Staffing\Pyramid.Staffing.Api\Pyramid.Staffing.Api.csproj(814,5): Error MSB3073: The command "npm run vs_build_prod" exited with code 1.
6>

**Comment by CuppaLabs** [comment]
unrelated to this component.
