### ISSUE TITLE
limitSelection not binding selected Item to input formData

### ISSUE THREAD

**Issue by vishwanathg** [CuppaLabs/angular2-multiselect-dropdown#269]
`<angular2-multiselect [data]="prefferedCdacCenterList" name="prefferedCdacCentresList" class="form-control" [(ngModel)]="model.prefferedCdacCentresList" [settings]="centersSettings" (onSelect)="onItemSelect($event)" (onDeSelect)="OnItemDeSelect($event)" (onSelectAll)="onSelectAll($event)"
                                        (onDeSelectAll)="onDeSelectAll($event)">
                                    </angular2-multiselect>`

`this.centersSettings = {
      limitSelection: 3
    };`

In above code when I do not change pre filled selected Items in the multiselect dropdown, I am not getting selected Items. Same code is working fine for the same scenario when I am not using limitSelection. Please help

**Comment by CuppaLabs** [comment]
redundant . not valid.
