### ISSUE TITLE
Filter input keyup & change output

### ISSUE THREAD

**Issue by HigorSilvaRosa** [CuppaLabs/angular2-multiselect-dropdown#27]
Is possible to implment outputs when filter input have a keyup or change event ?

**Comment by HigorSilvaRosa** [comment]
Is possible to implment outputs when filter input have a keyup or change event ?

**Comment by HigorSilvaRosa** [comment]
I did this new feature. How can I ask for a merge request?

**Comment by CuppaLabs** [comment]
@HigorSilvaRosa You can clone the repository, and implement your changes and then raise a pull request.
Thanks
