### ISSUE TITLE
Limit the height of the dropdown

### ISSUE THREAD

**Issue by tishansoft** [CuppaLabs/angular2-multiselect-dropdown#276]
Hi

It is very nice component.  But got some trouble using it. The dropdown hides behind the div in Footer. How to limit the height of the dropdown if there are lot of data. Also I want the dropdown to appear on top of other divs not to hide behind for example footer div.

**Comment by CuppaLabs** [comment]
Hi, Please use 'maxHeight' property in settings object. Please refer to documentation for the height configuration.
