### ISSUE TITLE
scripts.bundle.js issue with ng

### ISSUE THREAD

**Issue by trextroy** [CuppaLabs/angular2-multiselect-dropdown#279]
Hi,
For every version above 2.7 i am facing issue with the js file. 

Here in this file: angular2-multiselect-dropdown.umd.min.js

(function webpackUniversalModuleDefinition(root, factory) {
	if(typeof exports === 'object' && typeof module === 'object')
		module.exports = factory(require("@angular/core"), require("@angular/common"), require("@angular/forms"));
	else if(typeof define === 'function' && define.amd)
		define(["@angular/core", "@angular/common", "@angular/forms"], factory);
	else if(typeof exports === 'object')
		exports["ticktock"] = factory(require("@angular/core"), require("@angular/common"), require("@angular/forms"));
	else
		**root["ticktock"] = factory(root["ng"]["core"], root["ng"]["common"], root["ng"]["forms"]);**
})

Error log
Uncaught TypeError: Cannot read property 'core' of undefined
    at webpackUniversalModuleDefinition (scripts.bundle.js:30)
    at scripts.bundle.js:31

I am using it with Angular cli 1.7.4 version. This is also causing my unit test scripts to fail.

Can someone please help ?

**Comment by CuppaLabs** [comment]
build issue not related to the component.
