### ISSUE TITLE
Problem with select on the edge browser

### ISSUE THREAD

**Issue by Rambuto** [CuppaLabs/angular2-multiselect-dropdown#280]
Hello.
Sorry for my english.
I have truble with Edge. 
When i try open select i see only triangle and does't see popup with possible value.
But if I do page resize, select start working correctly.

Do you have any idea how I can fix it. 

This big problem and I need find solution very quickly

npm select v2.9.1
browser edge
angular v6.0.3

**Comment by CuppaLabs** [comment]
Hi, works as ecpected and correctly. below is the local environment test screenshot.
![image](https://user-images.githubusercontent.com/3957664/45251613-bc2e7f00-b366-11e8-8939-5d28fa74d5ab.png)

**Comment by Rambuto** [comment]
Could you provide version of the select which work on you demo site ? 
Because last version does't work.
I can provide video when this work on same time in the chrome and doesn't work on EDGE (but working on ie11) 
Also I have proble on the IE10

**Comment by helgablazhkun** [comment]
@Rambuto , @CuppaLabs 
I have the same issue. The root cause is in "hidden" attribute. 
It is better to use ngIf instead.
Anyway, the following style fix will help:
*[hidden] { display: none; }
