### ISSUE TITLE
searchBy is not working for particular mentioned key

### ISSUE THREAD

**Issue by manojtiwari801** [CuppaLabs/angular2-multiselect-dropdown#281]
1) Let's consider my object is like below mentioned

{
'id' : 1001,
'name' : 'Manoj',
'description' : 'Cuppa Labs Multi-select drop-down'
}

Here we configure searchBy: ['name'] in settings, but if we type in search box is 1001 or Cuppa, search shows the same result. Means searchBy is not working for particular mentioned key , its work over all the keys present in object.

**Comment by CuppaLabs** [comment]
Works as expected. Follow the new example at https://cuppalabs.github.io/angular2-multiselect-dropdown/#/searchFilterByOneProperty
