### ISSUE TITLE
Search and select all is not working properly.

### ISSUE THREAD

**Issue by manojtiwari801** [CuppaLabs/angular2-multiselect-dropdown#282]
We have search result for any key and found 3 result and click on select all and all 3 rows are getting selected. now we again search for other key and found 2 result and click select all, here finally only last two records are getting selected and previous 3 records are deselect automatically. Expected result all 5 records should be selected.

**Comment by CuppaLabs** [comment]
fixed . fix available in v2.10.0

**Comment by CuppaLabs** [comment]
use new property "select all filter results"
