### ISSUE TITLE
Styling issue with bootstrap 3.3.7

### ISSUE THREAD

**Issue by MiRush94** [CuppaLabs/angular2-multiselect-dropdown#285]
![out-of-the-box](https://user-images.githubusercontent.com/12034264/45283697-ddb27680-b4de-11e8-9930-33c04fc1c5ea.PNG)

the class from-control on the c-btn is not really working along with bootstrap 3.3.7. Upgrading to bootstrap 4 is not an option, as this is a customer project and we are not allowed to do it. Any ideas on how to fix this?

**Comment by MiRush94** [comment]
And you've left some console.logs in the code 

  AngularMultiSelect.prototype.toggleSelectAll = function() {
    console.log(this.ds.getData());
    console.log(this.filter);

**Comment by CuppaLabs** [comment]
Now you can use the themes feature in v3.0.0 for styling. Refer to theming and themes in documentation at  http://localhost:4000/components/multiselectDropdown/#Template---For-custom-html-of-menu-item
