### ISSUE TITLE
Wrong documentation for "Data from remote API example".

### ISSUE THREAD

**Issue by Sidonet** [CuppaLabs/angular2-multiselect-dropdown#286]
On documentation page https://cuppalabs.github.io/angular2-multiselect-dropdown/#/remoteData

Shown basic.ts instead of Data from remote API example.

Please help to ipmlement this feature.

p.s. I need to implement lazy loading with Remote API back-end. (get next values on scroll, or filter) If you have solution for this please add it to documentation too..

**Comment by CuppaLabs** [comment]
Fixed.   

Please write a mail for the below implementation

> **I need to implement lazy loading with Remote API back-end. (get next values on scroll, or filter) If you have solution for this please add it to documentation too..**
