### ISSUE TITLE
Getting Error in Building PROD Mode

### ISSUE THREAD

**Issue by santoshkumarsuru** [CuppaLabs/angular2-multiselect-dropdown#290]
ERROR in ng:///D:/Projects/MOVERS-SHAKERS/MandS-Client/node_modules/angular2-multiselect-dropdown/multiselect.component.d.ts.AngularMultiSelect.html (104,15): Type 'Boolean' is not assignable to type 'boolean'.
  'boolean' is a primitive, but 'Boolean' is a wrapper object. Prefer using 'boolean' when possible.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mands@0.0.1 build:src: `ng build "--prod"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mands@0.0.1 build:src script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ssuru082916\AppData\Roaming\npm-cache\_logs\2018-09-12T10_21_42_421Z-debug.log
ERROR: "build:src -- --prod" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mands@0.0.1 build: `run-s build:public "build:src -- {@}" --  "--prod"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mands@0.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ssuru082916\AppData\Roaming\npm-cache\_logs\2018-09-12T10_21_42_978Z-debug.log

**Comment by CuppaLabs** [comment]
Fixed. Please use v3.0.1
