### ISSUE TITLE
Missing default.theme.theme.css file

### ISSUE THREAD

**Issue by GitHubish** [CuppaLabs/angular2-multiselect-dropdown#292]
Hello,

The default.theme.css file seems missing when I get the package by NPM.

node_modules\angular2-multiselect-dropdown\src\app\angular2-multiselect-dropdown\default.theme.css

**Comment by CuppaLabs** [comment]
The theme file is available @ node_modules\angular2-multiselect-dropdown\themes\default.theme.css

**Comment by GitHubish** [comment]
But the themes folder is not in the package. See capture below of the package following the NPM INSTALL

![image](https://user-images.githubusercontent.com/7701833/45547342-c6e28b80-b820-11e8-9b92-bc757680fea2.png)

**Comment by CuppaLabs** [comment]
Noted. There is a package error. Please wait for v3.1.0 today.

**Comment by CuppaLabs** [comment]
Fixed.Please use v3.1.0
