### ISSUE TITLE
3.0.1 version build errors

### ISSUE THREAD

**Issue by DejanNemet** [CuppaLabs/angular2-multiselect-dropdown#293]
Hi,

I've tried to upgrade from 2.9.0 to 3.0.1 because when I use (lazyLoading: true) I get no data back.

After running yarn install and running the app I get this error while building:

ERROR in node_modules/angular2-multiselect-dropdown/src/app/angular2-multiselect-dropdown/clickOutside.ts(31,25): error TS6138: Property '_elementRef' is declared but its value is never read.
node_modules/angular2-multiselect-dropdown/src/app/angular2-multiselect-dropdown/clickOutside.ts(38,39): error TS6133: 'targetElement' is declared but its value is never read.
node_modules/angular2-multiselect-dropdown/src/app/angular2-multiselect-dropdown/menu-item.ts(1,40): error TS6133: 'NgModule' is declared but its value is never read.
node_modules/angular2-multiselect-dropdown/src/app/angular2-multiselect-dropdown/menu-item.ts(1,63): error TS6133: 'AfterContentInit' is declared but its value is never read.
node_modules/angular2-multiselect-dropdown/src/app/angular2-multiselect-dropdown/menu-item.ts(1,112): error TS6133: 'OnChanges' is declared but its value is never read.
node_modules/angular2-multiselect-dropdown/src/app/angular2-multiselect-dropdown/menu-item.ts(1,141): error TS6133: 'ViewEncapsulation' is declared but its value is never read.
node_modules/angular2-multiselect-dropdown/src/app/angular2-multiselect-dropdown/menu-item.ts(1,167): error TS6133: 'Output' is declared but its value is never read.
node_modules/angular2-multiselect-dropdown/src/app/angular2-multiselect-dropdown/menu-item.ts(1,175): error TS6133: 'EventEmitter' is declared but its value is never read.
node_modules/angular2-multiselect-dropdown/src/app/angular2-multiselect-dropdown/menu-item.ts(1,189): error TS6133: 'ElementRef' is declared but its value is never read.
node_modules/angular2-multiselect-dropdown/src/app/angular2-multiselect-dropdown/menu-item.ts(1,201): error TS6133: 'AfterViewInit' is declared but its value is never read.
node_modules/angular2-multiselect-dropdown/src/app/angular2-multiselect-dropdown/menu-item.ts(1,216): error TS6133: 'Pipe' is declared but its value is never read.
node_modules/angular2-multiselect-dropdown/src/app/angular2-multiselect-dropdown/menu-item.ts(1,222): error TS6133: 'PipeTransform' is declared but its value is never read.
node_modules/angular2-multiselect-dropdown/src/app/angular2-multiselect-dropdown/menu-item.ts(1,237): error TS6133: 'Directive' is declared but its value is never read.
node_modules/angular2-multiselect-dropdown/src/app/angular2-multiselect-dropdown/menu-item.ts(2,1): error TS6192: All imports in import declaration are unused.
node_modules/angular2-multiselect-dropdown/src/app/angular2-multiselect-dropdown/menu-item.ts(3,1): error TS6133: 'CommonModule' is declared but its value is never read.
node_modules/angular2-multiselect-dropdown/src/app/angular2-multiselect-dropdown/multiselect.component.ts(1,210): error TS6133: 'AfterViewInit' is declared but its value is never read.
node_modules/angular2-multiselect-dropdown/src/app/angular2-multiselect-dropdown/multiselect.component.ts(1,225): error TS6133: 'Pipe' is declared but its value is never read.
node_modules/angular2-multiselect-dropdown/src/app/angular2-multiselect-dropdown/multiselect.component.ts(1,231): error TS6133: 'PipeTransform' is declared but its value is never read.
node_modules/angular2-multiselect-dropdown/src/app/angular2-multiselect-dropdown/multiselect.component.ts(180,5): error TS7030: Not all code paths return a value.
node_modules/angular2-multiselect-dropdown/src/app/angular2-multiselect-dropdown/multiselect.component.ts(180,28): error TS6133: 'index' is declared but its value is never read.
node_modules/angular2-multiselect-dropdown/src/app/angular2-multiselect-dropdown/multiselect.component.ts(180,43): error TS6133: 'evt' is declared but its value is never read.
node_modules/angular2-multiselect-dropdown/src/app/angular2-multiselect-dropdown/multiselect.component.ts(212,21): error TS6133: 'c' is declared but its value is never read.
node_modules/angular2-multiselect-dropdown/src/app/angular2-multiselect-dropdown/multiselect.component.ts(261,15): error TS6133: 'index' is declared but its value is never read.
node_modules/angular2-multiselect-dropdown/src/app/angular2-multiselect-dropdown/multiselect.component.ts(293,5): error TS7030: Not all code paths return a value.
node_modules/angular2-multiselect-dropdown/src/app/angular2-multiselect-dropdown/multiselect.component.ts(441,9): error TS6199: All variables are unused.

If I can somehow show data (I have around 30k entries...) I would go back to 2.9.0 version.
Thank you in advance for any input.

**Comment by CuppaLabs** [comment]
Noted. There is a package error. Please wait for v3.1.0

**Comment by CuppaLabs** [comment]
Fixed. Please use v3.1.0
