### ISSUE TITLE
angular2-multiselect-dropdown v3.1.0 can not work in IE11

### ISSUE THREAD

**Issue by LinWang2** [CuppaLabs/angular2-multiselect-dropdown#298]
I am trying to use angular2-multiselect-dropdown v3.1.0 in my angular project. It can work well in chrome, but in IE11, when I select item in dropdown list, IE11 is just pending there and has no response any more. I saw the console log by F12, but there is no error either.

but when I open the official website (below link) in IE11, the dropdown works well.
https://cuppalabs.github.io/angular2-multiselect-dropdown/#/basic

Does anyone know the reason? did I miss anything?

this is my package.json

> "dependencies": {
    "@angular/animations": "^4.4.4",
    "@angular/common": "^4.4.4",
    "@angular/compiler": "^4.4.4",
    "@angular/core": "^4.4.4",
    "@angular/forms": "^4.4.4",
    "@angular/http": "^4.4.4",
    "@angular/platform-browser": "^4.4.4",
    "@angular/platform-browser-dynamic": "^4.4.4",
    "@angular/router": "^4.4.4",
    "ag-grid": "^18.0.1",
    "ag-grid-angular": "^18.0.1",
    "angular2-multiselect-dropdown": "^3.1.0",
    "bootstrap": "^3.3.7",
    "chart.js": "^2.7.2",
    "core-js": "^2.5.1",
    "moment": "^2.21.0",
    "ng2-charts": "^1.6.0",
    "ngx-bootstrap": "^2.0.5",
    "rxjs": "^5.1.0",
    "zone.js": "^0.8.18"
  },
  "devDependencies": {
    "@angular/cli": "^1.4.5",
    "@angular/compiler-cli": "^4.4.4",
    "@angular/language-service": "^4.4.4",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "^2.0.3",
    "@types/node": "^6.0.89",
    "codelyzer": "~3.0.1",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "^1.7.1",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.0.4",
    "tslint": "~5.3.2",
    "typescript": "~2.3.3"
  }

**Comment by CuppaLabs** [comment]
I think you have an implementation issue in your project. Please drop a mail to me. This is not a component issue. Hence closing it here.

**Comment by amantarento** [comment]
@CuppaLabs  on click of outside it is not closing  event in chrome .please provide the solution how to fix it.

**Comment by SasikalaGanapathy** [comment]
I am also facing the same issue. Its working fine with Chrome and Edge edge browser buts its not working in IE browser..
What is the issue?

**Comment by amantarento** [comment]
@SasikalaGanapathy  there is one Boolean flag  that we need to  active and deactivate when we are clicking outside .  <angular2-multiselect #participantsDropDown [data]="participantList" [(ngModel)]="selectedParticipantList" [settings]="participantsDropDownSettings"
                            (onSelect)="selectParticipants($event)" (onDeSelect)="OnParticipantsDeSelect($event)">
                            <c-search>
                                <ng-template>
                                    <input  [attr.disabled]= "participantList.length>0 ? null : true"type="text" (keyup)="getUserListWithQuery($event,'participant')" placeholder="{{resourceService?.frmelmnts?.prmpt?.search}}"
                                    />
                                </ng-template>
                            </c-search>
                        </angular2-multiselect> 
  @ViewChild('participantsDropDown') participantsDropDown;
then use like that 
 this.participantsDropDown.isActive = false;
