### ISSUE TITLE
Maximum allowed number of selections

### ISSUE THREAD

**Issue by pantonis** [CuppaLabs/angular2-multiselect-dropdown#3]
Hi,

It would be good to have a maximum allowed number of selections and if exceed disable checkboxes for the rest. For example lets say that my dropdown loads 100 items. I only want it to select maximum 20 items. if the user selects 20 items then the other checkboxes should be disabled and an event should be fired.

Thanks

**Comment by CuppaLabs** [comment]
Fixed. With latest version 1.1.2, this feature is available. Hence, closing.
