### ISSUE TITLE
Dropdown menu is closing after selecting one item

### ISSUE THREAD

**Issue by LorenzoRuggeri** [CuppaLabs/angular2-multiselect-dropdown#30]
Hi there,
thanks for you work, I'd like to know if there are workarounds/fixes for the behaviour described on the subject of the thread: after selected one option the dropdown menu is closing.
In your showcase site ( https://cuppalabs.github.io/angular2-multiselect-dropdown/ ) the described behaviour is not present. 
I digged into the compiled code of the showcase just to observe the version is running is different; in fact in to the Settings there's a key named 'searchPlaceholderText' instead of the current key named 'text'.

Any help would be really appreciated. :)

**Comment by CuppaLabs** [comment]
works as expected. 'searchPlaceholderText' and 'text' are two different settings for different features.
