### ISSUE TITLE
Can't bind to 'ngModelOptions' since it isn't a known property of 'angular2-multiselect'

### ISSUE THREAD

**Issue by odikusar** [CuppaLabs/angular2-multiselect-dropdown#303]
I use reactive forms with `angular2-multiselect` v2.9.1
If I add formControlName="selectedItems" I see error:
`VM560:37 Error: Template parse errors:
Can't bind to 'ngModelOptions' since it isn't a known property of 'angular2-multiselect'. `

**Comment by CuppaLabs** [comment]
Please use greater than or equal V3.1.0. v2.9.1 is a corrupt package.
