### ISSUE TITLE
Type VirtualScrollComponent in node_modules/angular2-multiselect-dropdown/virtual-scroll.d.ts is part of the declarations of 2 modules

### ISSUE THREAD

**Issue by badkicker** [CuppaLabs/angular2-multiselect-dropdown#307]
Type VirtualScrollComponent in node_modules/angular2-multiselect-dropdown/virtual-scroll.d.ts is part of the declarations of 2 modules: 
AngularMultiSelectModule in
node_modules/angular2-multiselect-dropdown/multiselect.component.d.ts and VirtualScrollModule

**Comment by CuppaLabs** [comment]
Please update to v3.1.1. Fixed.
