### ISSUE TITLE
AoT build fail: Type 'Item' is not assignable to type 'boolean'

### ISSUE THREAD

**Issue by poleindraneel** [CuppaLabs/angular2-multiselect-dropdown#309]
Getting following error while doing AoT Build - 

> Error at aot/node_modules/angular2-multiselect-dropdown/multiselect.component.ngfactory.ts:1753:11: Type 'Item' is not assignable to type 'boolean'.

Same issue is also happening on my build server

**Comment by poleindraneel** [comment]
> Getting following error while doing AoT Build -
> 
> > Error at aot/node_modules/angular2-multiselect-dropdown/multiselect.component.ngfactory.ts:1753:11: Type 'Item' is not assignable to type 'boolean'.
> 
> Same issue is also happening on my build server

Some more information on this bug. This is happening with Angular version 4. Works perfectly in JIT build but not in AoT. The problem occurs for two lines in Multiselect.component.html file with following conditions - 
`<div *ngIf="!settings.groupBy && settings.lazyLoading && itemTempl" [style.maxHeight]="settings.maxHeight+'px'" style="overflow: auto;">`

**Comment by aneem** [comment]
I am also getting the same issue when doing the aot build

**Comment by samuelrajsams** [comment]
hey can u look at into the issue most of the developers facing this issue while AOT build

**Comment by samuelrajsams** [comment]
hey can u look at into the issue most of the developers facing this issue while AOT build @CuppaLabs

**Comment by glennkarlsen** [comment]
Getting the same error for both AOT and JIT. @CuppaLabs

**Comment by PhoebePan** [comment]
I got the same issue, Angular version 4.3
```
webpack : [at-loader] ./aot/node_modules/angular2-multiselect-dropdown/multiselect.component.ngfactory.ts:1742:11; TS2322: Type 'Item' is not assignable to type 'boolean'.
 
webpack : [at-loader] ./aot/node_modules/angular2-multiselect-dropdown/multiselect.component.ngfactory.ts:1744:11; TS2322: Type 'Item' is not assignable to type 'boolean'.
```

multiselect.component.ngfactory.ts
```
  const currVal_23:boolean = ((!_co.settings.groupBy && !_co.settings.lazyLoading) && _co.itemTempl);
    _ck(_v,70,0,currVal_23);
    const currVal_24:boolean = ((!_co.settings.groupBy && _co.settings.lazyLoading) && _co.itemTempl);
    _ck(_v,73,0,currVal_24);
```

**Comment by avudai-16thyard** [comment]
Any update on this errror?

**Comment by CuppaLabs** [comment]
Please use v4.0

**Comment by avudai-16thyard** [comment]
After uninstall of my version 3.2.1, I installed v4.0.0. Then while running built command, It gives "ERROR in Metadata version mismatch for module" For info: Am using yarn PM. Please guide me on this.

![image](https://user-images.githubusercontent.com/24448559/47679285-f2abac00-dbe9-11e8-833e-1ee08b409bab.png)

**Comment by banibanc** [comment]
Same here.
@CuppaLabs, can you please tell me what to do ? I'm on angular 4...

**Comment by ShadabFaiz** [comment]
> After uninstall of my version 3.2.1, I installed v4.0.0. Then while running built command, It gives "ERROR in Metadata version mismatch for module" For info: Am using yarn PM. Please guide me on this.
> 
> ![image](https://user-images.githubusercontent.com/24448559/47679285-f2abac00-dbe9-11e8-833e-1ee08b409bab.png)

This error happens if you are using angular ver 4.4.4 with the library ver 4.x.x.

**Comment by Jakartoine** [comment]
In order to avoid this error, you can update the following line (multiselect.component.d.ts):

![image](https://user-images.githubusercontent.com/27675999/56811461-0c484c00-6839-11e9-97a1-b2401bbfd9a6.png)

Into:

![image](https://user-images.githubusercontent.com/27675999/56811487-18340e00-6839-11e9-85d9-aebe52f5e71a.png)

**Comment by PIoneer2** [comment]
@Jakartoine, nice solution! Same time it lacks further type usage. 8\

IMHO, the original error (in ngfactory) comes from AoT builder that tries to use resulting <boolean> in view condition (ngIf) IF it starts with booleans. But in 
`<div *ngIf="!settings.groupBy && settings.lazyLoading && itemTempl" ...`
itemTempl is not the boolean among others.
Can't override (and, maybe, not should) Ngs AoT builder now.
So to really fix v4 and any other, you could use one of the following to break that chain:
1. Classic solution - stable but with additional cast. Force JS typecast in the view condition (add double negation (!!) at you object to cast it to boolean - the condition list now have all booleans): 
`<div *ngIf="!settings.groupBy && settings.lazyLoading && !!itemTempl" ...`
2. Working solution - little faster solution for current AoT logic . Change the order of conditions. When condition will start with non-boolean type AoT builder will define resulting variable with type <any>. In this case any condition shouldn't be <boolean> explicit.
`<div *ngIf="itemTempl && !settings.groupBy && settings.lazyLoading" ...`

@CuppaLabs , @poleindraneel, FYI

**Comment by tishma** [comment]
> @Jakartoine, nice solution! Same time it lacks further type usage. 8\
> 
> IMHO, the original error (in ngfactory) comes from AoT builder that tries to use resulting in view condition (ngIf) IF it starts with booleans. But in `<div *ngIf="!settings.groupBy && settings.lazyLoading && itemTempl" ...` itemTempl is not the boolean among others. Can't override (and, maybe, not should) Ngs AoT builder now. So to really fix v4 and any other, you could use one of the following to break that chain:
> 
> 1. Classic solution - stable but with additional cast. Force JS typecast in the view condition (add double negation (!!) at you object to cast it to boolean - the condition list now have all booleans):
>    `<div *ngIf="!settings.groupBy && settings.lazyLoading && !!itemTempl" ...`
> 2. Working solution - little faster solution for current AoT logic . Change the order of conditions. When condition will start with non-boolean type AoT builder will define resulting variable with type . In this case any condition shouldn't be  explicit.
>    `<div *ngIf="itemTempl && !settings.groupBy && settings.lazyLoading" ...`
> 
> @CuppaLabs , @poleindraneel, FYI

Thank you so much for confirming that it's only happening when an object reference comes after real booleans. Also, when doing a non-prod build - I did not have this problem which made it harder to spot.
