### ISSUE TITLE
Change detection called unnecessarily for onPush component

### ISSUE THREAD

**Issue by behuda** [CuppaLabs/angular2-multiselect-dropdown#312]
https://stackblitz.com/edit/angular-wv8nae?file=src%2Fapp%2Fchild.component.ts

All component are onPush

Just click anywhere, notice the console change detection is called as many times as no. of angular-multiselect component count.

**Comment by CuppaLabs** [comment]
@behuda beacuse it is looking for a change based on click outside directive event.
