### ISSUE TITLE
Cannot style dropdown (button element) based on drop down state

### ISSUE THREAD

**Issue by dangrima90** [CuppaLabs/angular2-multiselect-dropdown#317]
I'm trying to add style on the component when the dropdown is open (i.e. the button element: .c-btn). Since a CSS class is not provided for this I tried to leverage this logic by using the onOpen/onClose callback functions.

I encountered the following issues:

**onOpen:**

The onOpen callback does not seem to fire.

**onClose:**

The onClose callback is triggered whenever the body is clicked. I understand the logic for this as you need to hide the dropdown list when a click "outside" of the dropdown is done. However it would be nice if that logic is separate than the onClose callback itself. This would mean that the onClose is only triggered when the dropdown is _actually_ closed.

I have replicated the issue I have here:

[https://stackblitz.com/edit/angular2-multiselect-issue](url)

You can check out the console to see what the onOpen and onClose events return when they are triggered.

I think it would be nice if a CSS class is provided on the button if the dropdown is opened. This would help to add style depending on the state of the dropdown list.

**Comment by dangrima90** [comment]
[https://stackblitz.com/edit/angular2-multiselect-issue](url)

**Comment by dangrima90** [comment]
Sorry closed the issue by mistake. Note that the url is somehow being pointed to github itself.. please copy and paste

**Comment by CuppaLabs** [comment]
@dangrima90 Issues fixed in v4.2
