### ISSUE TITLE
LazyLoading dropdown displays only 5 items after search

### ISSUE THREAD

**Issue by SerhiiThivinskiy** [CuppaLabs/angular2-multiselect-dropdown#319]
https://cuppalabs.github.io/angular2-multiselect-dropdown/#/lazyloadingRemoteData

Steps to reproduce:

1) Click on dropdown
![screenshot from 2018-10-10 14-35-33](https://user-images.githubusercontent.com/15870242/46733981-93b5df80-cc9a-11e8-8ecb-2e9df7e7904f.png)

2) Search with empty result
![screenshot from 2018-10-10 14-36-07](https://user-images.githubusercontent.com/15870242/46734219-3ec69900-cc9b-11e8-97a5-9e4f6879e016.png)

3) Remove search keyword
![screenshot from 2018-10-10 14-36-42](https://user-images.githubusercontent.com/15870242/46734242-5271ff80-cc9b-11e8-94ea-7ae153ab9ced.png)

Tested in Chrome and Firefox browsers.

**Comment by Zabudska-Yuliia** [comment]
same for me

**Comment by vladimirr** [comment]
I have faced with this issue as well. Could you please check it?

**Comment by yurii-abdulaiev** [comment]
The same issue for me :((

**Comment by CuppaLabs** [comment]
Hey !! will be resolved soon.

**Comment by EduardRakov** [comment]
btw guys, to reproduce the issue here https://cuppalabs.github.io/angular2-multiselect-dropdown/#/lazyloadingRemoteData just open the dropdown before the data is loaded

**Comment by Basemm** [comment]
Hello @CuppaLabs , any update on the fix?

**Comment by JaroslavPrt** [comment]
any update on the fix?)

**Comment by benny2009** [comment]
Would be great to see a fix on that 🙏  In general very great work @CuppaLabs for that whole component 💪

**Comment by CuppaLabs** [comment]
Guys, you will be getting a fix for this in one week.

**Comment by JaroslavPrt** [comment]
![andgone](https://user-images.githubusercontent.com/11339544/51847761-0a97e680-2325-11e9-8db6-1a141adf714e.jpg)

**Comment by benny2009** [comment]
Who solved it :D ?

**Comment by benny2009** [comment]
On my machine it still exists 😢

**Comment by Paso988** [comment]
Any news on this?

**Comment by SerhiiThivinskiy** [comment]
Hi! Any update?

**Comment by Zabudska-Yuliia** [comment]
Hi there! Any updates?

**Comment by JaroslavPrt** [comment]
> Hi there! Any updates?

прикалюха в тому що ти, я і автор цього топіка з одного міста @_@

**Comment by EduardRakov** [comment]
> > Hi there! Any updates?
> 
> прикалюха в тому що ти, я і автор цього топіка з одного міста @_@

і я 🤣

**Comment by DrSmile444** [comment]
> Hi! Any update?

Waiting for this too :D

**Comment by CuppaLabs** [comment]
fixed. fix available in version above v4.5.0

**Comment by JaroslavPrt** [comment]
almost a year

![dane](https://user-images.githubusercontent.com/11339544/63247959-f0950580-c26e-11e9-87c4-a2f21bc3aa7a.jpg)

**Comment by CuppaLabs** [comment]
Guys, you should understand that this is an open source code, a contribution to developers community. Every developer is welcome to find a solution and contribute by sending pull request and just not some absurd smileys and expression  !!

**Comment by Zabudska-Yuliia** [comment]
@CuppaLabs thanks for resolving this issue guys!

**Comment by JaroslavPrt** [comment]
> Guys, you should understand that this is an open source code, a contribution to developers community. Every developer is welcome to find a solution and contribute by sending pull request and just not some absurd smileys and expression !!

guys, also you should understand what is [Sarcasm](https://en.wikipedia.org/wiki/Sarcasm) ^_^
