### ISSUE TITLE
Stops working in IE after the latest update

### ISSUE THREAD

**Issue by sukhminderparmar** [CuppaLabs/angular2-multiselect-dropdown#32]
Hi

I took the latest update.
It has stopped working the IE. The angular-cli does not bootstrap with an error 'Cannot read property 'call' of undefined'
While installing the new update, I noticed some unmet dependencies as:
<component> requires a peer of angular/commonA^4.0.0 but none was installed
same for @angular/core@^4.0.0
@angular/forms@^4.0.0
tslibs@^1.6.1

Please let me know how it can be resolved.

**Comment by CuppaLabs** [comment]
fixed with v1.2.4
