### ISSUE TITLE
ERROR TypeError: Cannot read property 'toString' of null

### ISSUE THREAD

**Issue by JaroslavPrt** [CuppaLabs/angular2-multiselect-dropdown#321]
```
singleSelection: true,
enableSearchFilter: true,
enableCheckAll: false,
lazyLoading: true,

AngularMultiSelect.html:73 ERROR TypeError: Cannot read property 'toString' of null
    at multiselect.component.js:466
    at Array.filter (<anonymous>)
    at AngularMultiSelect.push../node_modules/angular2-multiselect-dropdown/multiselect.component.js.AngularMultiSelect.filterInfiniteList (multiselect.component.js:464)
```

all works fine if:

```
singleSelection: false,
enableSearchFilter: true,
enableCheckAll: true,
lazyLoading: true
```

guess the problem is `lazyLoading: true`  and `singleSelection: true` not working together?
and seems that `onScrollToEnd` fires only with `lazyLoading: true`, is it?

**Comment by CuppaLabs** [comment]
fixed

**Comment by abhi037** [comment]
hello sir i am using cuppalabs multi select dropdown three time in my form with any lazyloading but still I got this
ERROR TypeError: Cannot read property 'lazyLoading' of undefined at AngularMultiSelect.push../node_modules/angular2-multiselect-dropdown/fesm5/angular2-multiselect-dropdown.js.AngularMultiSelect.ngOnChanges (angular2-multiselect-dropdown.js:222
