### ISSUE TITLE
Hard coded hyphen

### ISSUE THREAD

**Issue by akrao** [CuppaLabs/angular2-multiselect-dropdown#322]
https://github.com/CuppaLabs/angular2-multiselect-dropdown/blob/156348d3c8981430e6f53ac4f170524726fa92ab/projects/angular2-multiselect-dropdown-lib/src/lib/multiselect.component.html#L116

Hyphen should not be hard coded. User should have the option to mention what to render as a label.

**Comment by CuppaLabs** [comment]
fixed.
