### ISSUE TITLE
onOpen and onClose event error

### ISSUE THREAD

**Issue by BergkampHUN** [CuppaLabs/angular2-multiselect-dropdown#329]
The onOpen function does not working at all, never been called.
The onClose function fires on every click on the page even if the dropdown are closed.
I don't know these two things are related, but they are exists, at least for me.

If you add the 'enableSearchFilter: true' option the onOpen event is fired.

version 4.0.0

**Comment by Cobr3n** [comment]
Subscribe please help!
onOpen doesn't emit event when specifying c-search,
without custom c-search is work fine for me....
https://stackblitz.com/edit/angular-3tcuzj

**Comment by CuppaLabs** [comment]
@Cobr3n  Refer https://cuppalabs.github.io/angular2-multiselect-dropdown/#/customSearchAPI for the code. Compare your code and the examle code, you will get the solution.

**Comment by BergkampHUN** [comment]
@CuppaLabs Here is a demo for the original issue:
https://stackblitz.com/edit/angular-3qqhrw

**Comment by Cobr3n** [comment]
@uppaLabs 
![image](https://user-images.githubusercontent.com/25749976/48111834-0314f400-e286-11e8-93d8-d2abb8beb3b9.png)
onOpen doesnt work ? why
PS: if i remove <c-search> then everything works fine

**Comment by CuppaLabs** [comment]
Fixed. Please use v4.1.0
