### ISSUE TITLE
When Enable Lazy Loading in label show Id Key + Label Key

### ISSUE THREAD

**Issue by suyudo** [CuppaLabs/angular2-multiselect-dropdown#331]
I'm try to use that feature ( Lazy Loading ), but i'm stuck, why in view label show Id Key + Label Key. I don't want use custom template, because not hard to styling, Anyone have solution ?

**Comment by CuppaLabs** [comment]
We cannot hardcode the properties of an object in component. You have to use custom template feature to get the row item in the way you wanted
