### ISSUE TITLE
Disable selected value

### ISSUE THREAD

**Issue by Manivannandurairaj** [CuppaLabs/angular2-multiselect-dropdown#333]
Hello Team,

How to disabled selected default option value in the multiselect plugin

**Comment by CuppaLabs** [comment]
use disabled property of the dropdown. If you want to disable the selected item, that is not possible.

**Comment by gabomontero89** [comment]
@CuppaLabs we are facing this issue. When you select an item and click again on the same item the selection is erased, these is not the expected behavior, if the select is setup as single select, the selected item need to be excluded from possible selections.

**Comment by kodze** [comment]
Same need in single mode..
