### ISSUE TITLE
Cannot use select all filtered reuslts on grouped items 

### ISSUE THREAD

**Issue by MiRush94** [CuppaLabs/angular2-multiselect-dropdown#334]
When I load my items into the dropdown, and then try to select all filtered items, I get this error in the console. 

![capture](https://user-images.githubusercontent.com/12034264/49727369-62449a80-fc70-11e8-8125-2bd23776e300.PNG)

**Comment by MiRush94** [comment]
You can chek this same issue in the demo of your dropdwon, it doesn't work there either. 

https://cuppalabs.github.io/angular2-multiselect-dropdown/#/groupby

Search for something and the try to click the checkbox: select all filtered results.

**Comment by CuppaLabs** [comment]
Fixed. fix available in v4.5.0

**Comment by kiranp1992** [comment]
Is this really fixed? I'm still able to reproduce it in version 4.6.3
