### ISSUE TITLE
After deploying i got this isssue

### ISSUE THREAD

**Issue by linkingas** [CuppaLabs/angular2-multiselect-dropdown#335]
![image](https://user-images.githubusercontent.com/4223540/49815786-d7959580-fd6c-11e8-9e4e-b52c38cccd75.png)

**Comment by linkingas** [comment]
![image](https://user-images.githubusercontent.com/4223540/50402913-ac626b80-079a-11e9-8346-b90d4c586b51.png)

the problem is coming from this form-control class

**Comment by CuppaLabs** [comment]
removed in latest version
