### ISSUE TITLE
Unable to open multiselect on external button click

### ISSUE THREAD

**Issue by Aparna447** [CuppaLabs/angular2-multiselect-dropdown#337]
Multiselect needs to be opened on external button click.
External click refers to a button which is outside your multiselect.Whenever that button is clicked i wanted to open multiselect.

Can you please help on this and reply asap.

**Comment by Aparna447** [comment]
Any help on this?Need this implementation asap so that it would help us.

**Comment by CuppaLabs** [comment]
@Aparna447 : This is completed and in pipeline for publishing. Probably on tomorrow's release you should have this solution

**Comment by CuppaLabs** [comment]
v4.2 fixed

**Comment by ankurraiyani** [comment]
Hi

I am not able to open dropdown using external button with openDropdown() method.
I am using version 4.6.3

Please help asap.

Thanks
