### ISSUE TITLE
How to add some extra properties in dropdown list?

### ISSUE THREAD

**Issue by vinitKr** [CuppaLabs/angular2-multiselect-dropdown#34]
Hello,

I want to add some extra fields like image or some text in the dropdown list. I tried to use jquery to dynamically add some extra fields, it work fine.

but when I try to use search filter, it removes all the extra added values from the dropdown.

Can you please suggest a solution for this?

Thanks
![dropdown_1](https://user-images.githubusercontent.com/22386576/29365695-8ac7051e-82b5-11e7-86e6-4638e488066c.png)
![dropdown_2](https://user-images.githubusercontent.com/22386576/29365700-9050b070-82b5-11e7-9c10-a312089ea1c0.png)
![dropdown_3](https://user-images.githubusercontent.com/22386576/29365706-93eec0be-82b5-11e7-975a-bc5194841471.png)

**Comment by CuppaLabs** [comment]
as of now , there is no support for adding extra properties. JQuery usage is highly discouraged in angular components. Please implement the features in angular and raise a pull request to merge it to master.

**Comment by vinitKr** [comment]
@CuppaLabs  Thank you for your response.

Can you please let me know why is the external fields disappeared after searching, and if you have any  solution to fix this problem.

Thanks
