### ISSUE TITLE
labelKey: Not working with nested object

### ISSUE THREAD

**Issue by tong-ho** [CuppaLabs/angular2-multiselect-dropdown#340]
Hello all,

Although the document states that labelKey does work with nested objects, I have not had any luck getting it to work.

`import { IAddress } from './address.model';`

`export interface ILocation {`
  `id: number;`
  `addressId: number;`
 ` address: IAddress;`
  `addressString: string;`
`}`

`export interface IAddress{`
  `id: number;`
 ` addressLine1: string;`
`...`
`}`

`    this.settingsForLocation = {`
`      singleSelection: false,`
 `     text: "Select Locations",`
  `    searchPlaceholderText: "Address",`
   `   selectAllText: 'Select All',`
    `  unSelectAllText: 'UnSelect All',`
     ` enableSearchFilter: true,`
      `searchBy: ['address'],`
      `primaryKey: "id",`
      `labelKey: "address.addressLine1",`
      `class: ['list-group-item']`
    `};`

`        <angular2-multiselect [data]="locationList"`
`                              [(ngModel)]="selectedLocations"`
`                              [settings]="settingsForLocation"`
`                              (onSelect)="onItemSelect($event)"`
`                              (onDeSelect)="OnItemDeSelect($event)"`
`                              (onSelectAll)="onSelectAll($event)"`
`                              (onDeSelectAll)="onDeSelectAll($event)">`

Changing labelKey to id gives me the location id correctly.
Changing labelKey to address gives me object Object.
Changing it to address.addressLine1 gives me a tiny box on the control (assuming it contains nothing).

Anyways, thanks for all your hard work.

**Comment by suheylLiliomlab** [comment]
I have the same issue.

**Comment by CuppaLabs** [comment]
The component does not support nested object data.
