### ISSUE TITLE
Group checkbox not checked by default

### ISSUE THREAD

**Issue by voilacti** [CuppaLabs/angular2-multiselect-dropdown#341]
Hello !
I think there is a problem with the group checkbox when the options **groupBy**  and **selectGroup** are actives. Even if all the items of the group are included in the selected list by default (I manually included them), the group checkbox is not checked...
I also wonder if there are events to do something when you select/deselect a group ? Like a  _onSelectGroup_ _onDeSelectGroup_ because I need to compute values when the selected list is changed by making a REST call to my server. The option ngModelChange would have been an answer but it makes one call by element and the process would be too long...
Thank you for this component and the evolutions you are making, it is great !

**Comment by vijendrakumar** [comment]
Same problem occurred with me.

**Comment by donton17** [comment]
Is this resolved or still a bug?

**Comment by harshadvala** [comment]
is there any option for this ?

**Comment by CuppaLabs** [comment]
Fixed. Fix available in v4.5.0
