### ISSUE TITLE
Unable to import DataService class from angular2-multiselect-dropdown

### ISSUE THREAD

**Issue by saran-babu** [CuppaLabs/angular2-multiselect-dropdown#344]
Unable to directly import and use classes like DataService, Badge, CIcon, Search  from angular2-multiselect-dropdown for customization. Please do assist.

**Comment by CuppaLabs** [comment]
@saran-babu The component expose only the following as public methods to be used. Other methods and variables are encapsulated.
export { AngularMultiSelect } from './multiselect.component';
export { ClickOutsideDirective } from './clickOutside';
export { ListFilterPipe } from './list-filter';
export { Item } from './menu-item';
export { TemplateRenderer } from './menu-item';
export { AngularMultiSelectModule } from './multiselect.component';
