### ISSUE TITLE
Dynamic single selection dropdown reset other dropdown

### ISSUE THREAD

**Issue by vikasbhadran** [CuppaLabs/angular2-multiselect-dropdown#345]
After selecting a dropdown value (using ngmodel as array) other dropdown values are set by last selected item. we are using dynamic form with dynamic dropdown.
![image](https://user-images.githubusercontent.com/41143533/52032592-a0ab5700-2547-11e9-896b-2f4132bd4f10.png)

**Comment by CuppaLabs** [comment]
Please refer https://cuppalabs.github.io/angular2-multiselect-dropdown/#/usingInList or write to me on my email for implementation help.
