### ISSUE TITLE
unselect all filtered results checkbox should be unchecked when Deselect all is clicked

### ISSUE THREAD

**Issue by Aparna447** [CuppaLabs/angular2-multiselect-dropdown#346]

**Comment by Aparna447** [comment]
Hi Team,

When "Deselect All" is clicked unselect all filtered results checkbox should be unchecked.
Because deselect all means ewe need to uncheck all check boxe.Can you please implement this and let me know once it is done.

**Comment by ivanferrer** [comment]
There is an important issue here, for example: if I check at least 2 selections, the option to uncheck all should already appear.
