### ISSUE TITLE
Select all filtered results checkbox not getting checked With Group By

### ISSUE THREAD

**Issue by vijendrakumar** [CuppaLabs/angular2-multiselect-dropdown#347]
Select all filtered results checkbox not getting checked with Group By of list feature.
Throwing below mentioned error in console.
ERROR TypeError: Cannot read property 'forEach' of undefined

**Comment by pwinstead** [comment]
I believe this is a duplicate of issue #334.  Unfortunately, there is no resolution yet.

**Comment by CuppaLabs** [comment]
Fixed. ix available in 4.5.0
