### ISSUE TITLE
Filtering out all options in group by dropdown can cause options not to repopulate on filter clear.

### ISSUE THREAD

**Issue by pwinstead** [CuppaLabs/angular2-multiselect-dropdown#348]
I have a situation where I'm using an API call to populate the dropdown data. I then use the filter of the dropdown to filter out all possible results. If I then clear the filter the dropdown remains empty.  

I did some investigation and it looks like the groupCahcedItem variable isn't being populated in all the necessary spots. It's value gets set during the control's init (ngOnInit) along with the cachedItems variable. However, it does not get set ngOnChanges, which cacheditems does.

**Comment by CuppaLabs** [comment]
Fixed. Fix available in v4.6.2

**Comment by CuppaLabs** [comment]
refer example at https://cuppalabs.github.io/angular2-multiselect-dropdown/#/remoteData
