### ISSUE TITLE
FireFox related bug - click on delete icon

### ISSUE THREAD

**Issue by LorenzoRuggeri** [CuppaLabs/angular2-multiselect-dropdown#35]
Hi there, 
I encountered a bug using Firefox and it'd be reproduced on your show-case application ( https://cuppalabs.github.io/angular2-multiselect-dropdown/ ): if you select one or more items and then you try to un-select them clicking on the 'X' icon the click will be intercepted and it'll open the items menu.

It works perfectly in Chrome instead.

Thanks for your great work!

![capture](https://user-images.githubusercontent.com/20802945/29527156-53552f66-8698-11e7-9368-43f2a38057c5.PNG)

**Comment by thedarkdestructor** [comment]
We experienced the same strange behavior in firefox. Everything seems ok in Chrome.

**Comment by CuppaLabs** [comment]
resolved. Fix available with latest version 1.2.5. update npm as well.

**Comment by thedarkdestructor** [comment]
Thank you for your quick action.

**Comment by LorenzoRuggeri** [comment]
@CuppaLabs 
Thank you so much!
