### ISSUE TITLE
All the dropdown list data disappear on filtering -- v 4.2.1

### ISSUE THREAD

**Issue by valenciadaniel0** [CuppaLabs/angular2-multiselect-dropdown#352]
Hello guys,
I'm working with the last version of angular2-multiselect-dropdown and I have a problem when I start typing on the filter input, when I type something it doesn't filter and all the data dissapear, even when I clean the filter input the dropdown still doesn't have data:
![image](https://user-images.githubusercontent.com/4191911/52724620-b116f500-2f7d-11e9-9268-72f89ca95318.png)
![image](https://user-images.githubusercontent.com/4191911/52724678-ca1fa600-2f7d-11e9-937b-1a6d8d40d208.png)

Here how I'm implementing the multiselect:

**this.settingsLocations = {
            singleSelection: true,
                idField: 'id',
                labelKey: 'itemname',                
                text:'Seleccione un origen',
                primaryKey:'id',               
                searchPlaceholderText: 'Buscar...',
                noDataLabel:'No hay datos disponibles',                    
                enableSearchFilter: true,                
                groupBy:'category',
                showCheckbox:true,
                classes:'',
                lazyLoading:true
            };**

**<angular2-multiselect					
					[data]="locations"
					[ngModelOptions]="{standalone: true}"
					[settings]="settingsLocations"
					[(ngModel)]="destination"
					(onSelect)="selectDestination($event)"
					(onDeSelect)="deselectDestination($event)"					
				>
				</angular2-multiselect>**	

thanks in advance for your help

**Comment by CuppaLabs** [comment]
@valenciadaniel0 Fixed in v4.5.0
