### ISSUE TITLE
not retaining all values on outside click (Lazyloading)

### ISSUE THREAD

**Issue by divyaaetvn** [CuppaLabs/angular2-multiselect-dropdown#356]
we are not able to retain all values after we search something and click out side and when we came back. search term became empty but results are coming with previous search term.when we perform any click like 'Enter',,'Backspace' in search box then we are getting all data.

![alldata](https://user-images.githubusercontent.com/42432100/53416147-d7ff0d80-39f8-11e9-927b-9fd875a3f9b9.PNG)
![select](https://user-images.githubusercontent.com/42432100/53416149-d7ff0d80-39f8-11e9-8bdb-d5745d1c4c53.PNG)
![clickout](https://user-images.githubusercontent.com/42432100/53416148-d7ff0d80-39f8-11e9-99fe-ec43fd63db8c.PNG)

Expected: when we search for any item then closed drop down,when we opened again search term should be cleared and data should get like when no search performed.like functionality when not using lazyloading

**Comment by CuppaLabs** [comment]
fixed. fix available in v4.5.0
