### ISSUE TITLE
Documentation Error

### ISSUE THREAD

**Issue by ShadabFaiz** [CuppaLabs/angular2-multiselect-dropdown#357]
In the documentation, it says after installing it, we should import it from 
`import { AngularMultiSelectModule } from 'angular2-multiselect-dropdown/angular2-multiselect-dropdown'; 

but it would produce an error in Angular v4.4 (i have not checked with other versions.). To properly improt it, we should import in like this:
`import { AngularMultiSelectModule } from '../../node_modules/angular2-multiselect-dropdown';
`

**Comment by CuppaLabs** [comment]
@ShadabFaiz it should be 
import { AngularMultiSelectModule } from 'angular2-multiselect-dropdown';
