### ISSUE TITLE
angular2-multiselect groupby is not working after upgrade to version 4.2.1

### ISSUE THREAD

**Issue by Priyanka-09** [CuppaLabs/angular2-multiselect-dropdown#359]
this.dropdownSettings = {
        text: "Select",
        selectAllText: 'Select All',
        unSelectAllText: 'UnSelect All',
        enableCheckAll: false,
        // limitSelection: 2,
        badgeShowLimit: 1,
        scrollableHeight: '10px',
        scrollable: true,
        autoUnselect: true,
        groupBy: "filter",
        selectGroup: false
      };

This was working fine previously after upgrading to version 4.2.1 it has stopped working for custom html of menu

```
<angular2-multiselect [data]="dropdownList" [(ngModel)]="selectedItems" [settings]="dropdownSettings">
  <c-item>
          <ng-template let-item="item">
            <label style="">{{item.itemName}}</label>
                <i class="fa fa-circle" *ngIf="item.id!=''" [style.color]="item.status == '1' ? '#45d552' : '#f37165'"></i>
              </ng-template>
          </ng-template>
  </c-item>    
</angular2-multiselect>
```
![new2](https://user-images.githubusercontent.com/48080403/53549618-a0a87200-3b5a-11e9-8385-82070550b5bb.PNG)
![old2](https://user-images.githubusercontent.com/48080403/53549621-a3a36280-3b5a-11e9-9efe-69f8fe6895b7.PNG)

First one is new one after upgrade I want it like second one which was before upgrade

**Comment by MALHARIHALGEKAR** [comment]
Even I am facing same issue please help

**Comment by Priyanka-09** [comment]
> Even I am facing same issue please help

Hi @MALHARIHALGEKAR

**Comment by CuppaLabs** [comment]
please use v4.2.7

**Comment by rohitatGit** [comment]
i am using angular 7.2 with cuppa v4.6.Same issue happening for me as well .Group by feature is not working properly.please suggest.

**Comment by Priyanka-09** [comment]
Hi @rohitatGit 

Try  using this  in ur global CSS code , it solved issue for me :

.grp-title input[type=checkbox]+label {
display:none;
}
