### ISSUE TITLE
reactiveForm insertion documentation

### ISSUE THREAD

**Issue by blemoinesgcib** [CuppaLabs/angular2-multiselect-dropdown#36]
the multiselect dropdown doesn't have any instruction about how to set it up in a reactiveForm template.

Also in forms,
 it would be great to have a param to add and id attribute to focus on the search input corresponding to a label having a "for" attribute.

**Comment by SvenSchoene** [comment]
I ran into the same issue.  

For me, adding `[ngModelOptions]="{standalone: true}"`  worked, like so:
```html
<angular2-multiselect
  [data]="data"
  [(ngModel)]="selectedItems"
  [ngModelOptions]="{standalone: true}"
  [settings]="dropdownSettings"
  (onSelect)="onItemSelect($event)" 
  (onDeSelect)="OnItemDeSelect($event)"
></angular2-multiselect>
```

**Comment by CuppaLabs** [comment]
Please refer to this example https://cuppalabs.github.io/angular2-multiselect-dropdown/#/usinginreactiveform
