### ISSUE TITLE
group by labels are not showing when open a dropdown

### ISSUE THREAD

**Issue by samba439** [CuppaLabs/angular2-multiselect-dropdown#360]
I have group items based on user selection, items are grouping up but the group label is not showing up beside to checkbox.
please see below screenshot. 
highlighted with yellow color 
![issue](https://user-images.githubusercontent.com/11311519/53737149-b8ad2800-3eb1-11e9-92b6-6f8a2bed1579.PNG)

**Comment by CuppaLabs** [comment]
fixed
