### ISSUE TITLE
onClose event is not working for multiple select dropdown

### ISSUE THREAD

**Issue by srinivasrgowda** [CuppaLabs/angular2-multiselect-dropdown#361]
I am using multiple select dropdown, when I click on the dropdown onOpen event is working fine, but onClose event is not triggering 

Angular: "^5.2.0"
Multiselect: "^4.2.1"

> <angular2-multiselect #dropdownElem [data]="PayerDetails" [(ngModel)]="PayerDetailsSelected" [settings]="dropdownSettings" 
(onSelect)="onItemSelect($event)"
(onDeSelect)="OnItemDeSelect($event)" 
(onSelectAll)="onSelectAll($event)" 
(onDeSelectAll)="onDeSelectAll($event)"
(onOpen)="onOpen($event)"
(onClose)="onClose($event)">
</angular2-multiselect>

**Comment by foramkumar-parekh** [comment]
I am also facing the same issue. Do we have any solution for this?
I am on
Angular: "^7.2.14"
Multiselect: "^4.2.1"

**Comment by foramkumar-parekh** [comment]
I shifted to Multiselect: "^4.2.6" and now onclose is working. 
But now something new is happening,

After I close the dropdown, the onclose method is called. Expected :)
But After this, if I click anywhere on the page, it calls the onclose method. weird and not expected :(

Kindly provide the resolution for this as I need to use the onclose method critically.

**Comment by srinivasrgowda** [comment]
Hi @foramkumar-parekh ,
Multiselect dropdown has clickOutside event, if you click anywhere on the body (page) this event will be called. 
Please find the below reference code example. 
(clickOutside)="onClickOutideDropdown($event)"

`<angular2-multiselect [data]="itemList" 
                      [(ngModel)]="selectedItems" 
                      [settings]="settings" 
                      (onSelect)="onItemSelect($event)"
                      (onDeSelect)="OnItemDeSelect($event)" 
                      (onSelectAll)="onSelectAll($event)" 
                      (onDeSelectAll)="onDeSelectAll($event)"
                      (clickOutside)="onClickOutideDropdown($event)">
</angular2-multiselect>`

**Comment by foramkumar-parekh** [comment]
That's great to know...
But this is happening with me with onClose.

And i have not used clickOutside for this. Also i don't want to call the function on clicking anywhere on the page.

I just need to get onClose

**Comment by CuppaLabs** [comment]
working as expected. refer to example at https://cuppalabs.github.io/angular2-multiselect-dropdown/#/multipledropdowns
