### ISSUE TITLE
Group Checkbox Not Showing..

### ISSUE THREAD

**Issue by 0nyn** [CuppaLabs/angular2-multiselect-dropdown#362]
Hey guys,

Is there any work around about this issue, It seems like the group header checkbox are not showing:

![image](https://user-images.githubusercontent.com/26914475/54417396-02f99900-473d-11e9-9954-7fb7bcf11bd8.png)

Thank you and hoping to hear from you soon...

**Comment by STK913** [comment]
Hello,

I confirm this bug. Do you have a solution to work around this problem?

Thanks in advance.

**Comment by STK913** [comment]
After analyzing the code, I just saw that you have to add the selectGroup parameter! It isn't specified in the documentation.

Here are my settings:

public settings = {
    singleSelection: false,
    text: "Sélectionner des intitulés",
    selectAllText: 'Tout sélectionner',
    unSelectAllText: 'Tout désélectionner',
    searchPlaceholderText: 'Rechercher...',
    noDataLabel: "Aucune donnée disponible",
    enableSearchFilter: true,
    addNewItemOnFilter: true,
    enableCheckAll: true,
    selectGroup: true,
    badgeShowLimit: 5,
    groupBy: "category"
  };

**Comment by kraczo** [comment]
Hi, I have the same issue, groupBy settings property is added ...

**Comment by CuppaLabs** [comment]
fixed. Fix available in v4.5.0
