### ISSUE TITLE
Grouped Dropdown Single Selection doesn't add selected_item class

### ISSUE THREAD

**Issue by aislingnorris** [CuppaLabs/angular2-multiselect-dropdown#368]
On the dropdown when selecting from one ungrouped list, the selected item's element in the dropdown gets appended with 'selected-item'.
![no-group](https://user-images.githubusercontent.com/9976168/55631722-9ceab980-57b0-11e9-9e57-98d3e0947f85.png)
You can see I have selected Alaska, the class selected-item has been appended to the element, and I have been able to change that class to be purple.

When the dropdown has a grouping, this class does not get appended the same way.
![grouped](https://user-images.githubusercontent.com/9976168/55631721-9c522300-57b0-11e9-8c48-5be197cb4ff8.png)
You can see I have selected Apple, but the element has no class, and no highlight.

**Comment by aislingnorris** [comment]
Also, I am using v4.2.1

**Comment by CuppaLabs** [comment]
fixed. fix available in v4.6.0
