### ISSUE TITLE
Remove number from label in dropdown when lazyLoading is enabled

### ISSUE THREAD

**Issue by rahul051296** [CuppaLabs/angular2-multiselect-dropdown#369]
How do i remove the numbers appended to the label of the dropdown when lazyloading is enabled? My settings are as below.

`"{
unSelectAllText:'Unselect All',
 badgeShowLimit: 2, 
searchPlaceholderText: 'Search Application', 
enableSearchFilter: true, 
lazyLoading: true, 
labelKey: 'itemName'
}"`

**Comment by orahul1** [comment]
any solution ?

**Comment by orahul1** [comment]
Fixed this issue. pull request is on review. Quick solution nodemodules > angular2-multiselect-dropdown > remove all {{item.id}} from bundles

**Comment by CuppaLabs** [comment]
fixed in v4.5.0
