### ISSUE TITLE
There are many uses of "var" instead of "let" or "const" causing ts linting errors.

### ISSUE THREAD

**Issue by pratik-joshi-cactus** [CuppaLabs/angular2-multiselect-dropdown#370]
Nice plugin, I really liked it :+1:  :) 
There are many uses of "var" instead of "let" or "const" causing ts linting errors.
I guess var keyword should not be used at all in ts file when working on angular.
Please fix it.

**Comment by CuppaLabs** [comment]
fixed. fix available in v4.6.0
