### ISSUE TITLE
Displaying top Countries on top of the list

### ISSUE THREAD

**Issue by edizsuleyman** [CuppaLabs/angular2-multiselect-dropdown#371]
My question is, is there a way to display, let's say top 2 Countries above the dropdown list and separate them with a line?
So, I want something like below.

When i click the dropdown with the country list it will display this:

**Germany**
**Switzerland**
**-------------------**
**The rest of the countries**

Thank you in advance.

**Comment by CuppaLabs** [comment]
You can use group by feature along with category and sorting to get this kind of implementation. The component itself cannot provide a specification to achieve so.
