### ISSUE TITLE
angular 2 version compatibility

### ISSUE THREAD

**Issue by amic81** [CuppaLabs/angular2-multiselect-dropdown#374]
Hello,

I have a question about the "2.10.2" version of the component.
From the package.json I see that it requires angular 4.0.0.

Then looking better, in fact already from the "1.0.1" version of the component requires angular 4.0.0 or higher.

I would like to use it in an angular 2.4 project, but then your component is actually usable only from version 4.0.0 of angular?

I look forward to your feedback.

Thank you

amic81

**Comment by CuppaLabs** [comment]
you can use it across all versions.
