### ISSUE TITLE
Error in app.module.ts after on adding AngularMultiSelectModule

### ISSUE THREAD

**Issue by maitreek** [CuppaLabs/angular2-multiselect-dropdown#376]
I'm using angular version 6 and am trying to integrate angular2-multiselect-dropdown in my app. On trying to run the app, after following the usage steps from this reference:
[http://cuppalabs.github.io/components/multiselectDropdown/](url)
[https://www.npmjs.com/package/angular2-multiselect-dropdown](url)

I get error as below:

Date: 2019-05-02T07:41:56.573Z
Hash: 8b7ca08bfd8ad516f706
Time: 27855ms
chunk {main} main.js, main.js.map (main) 4.99 MB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 473 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 5.22 kB [entry] [rendered]
chunk {scripts} scripts.js, scripts.js.map (scripts) 158 kB  [rendered]
chunk {styles} styles.js, styles.js.map (styles) 255 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 7.43 MB [initial] [rendered]

ERROR in ./src/app/app.module.ts
Module not found: Error: Can't resolve 'angular2-multiselect-dropdown/angular2-multiselect-dropdown' in 'D:\Projects\Gosnow\src\gosnow_admin\src\app'
i ｢wdm｣: Failed to compile.

I tried with "angular2-multiselect-dropdown": "^4.2.2" and "angular2-multiselect-dropdown": "^4.2.0" both to get the same error.

May I please get some help on this?

**Comment by fridoo** [comment]
I think the import statement in the documentation here http://cuppalabs.github.io/components/multiselectDropdown/#Usage is wrong.

`import { AngularMultiSelectModule } from 'angular2-multiselect-dropdown/angular2-multiselect-dropdown';`

should be 

`import { AngularMultiSelectModule } from 'angular2-multiselect-dropdown';`

**Comment by maitreek** [comment]
@fridoo you are right, I made the changes and its working now. Thanks for the help! :)

**Comment by maitreek** [comment]
@CuppaLabs , can you please make the necessary changes to the documentation as mentioned by @fridoo  in his comment so as to avoid any such errors in future. Thanks!

**Comment by CuppaLabs** [comment]
Fixed.
