### ISSUE TITLE
remove 'x' from the badge

### ISSUE THREAD

**Issue by foramkumar-parekh** [CuppaLabs/angular2-multiselect-dropdown#377]
I am facing some issues with the selected items.

1) If I set the selected values and without opening the dropdown, I remove the selected items using the 'x' in the selected item badge, then that entries also gets removed from the dropdown list. Not sure why this is happening.

So as a work around, I want to remove the 'x' from the selected item badge and want the user to deselect the option by unchecking the checkbox only.

2) when nothing is selected, the dropdown is not expanded as per the option text. This looks pretty bad, Please refer below screen shot for this.
![localhost_4200_](https://user-images.githubusercontent.com/26627307/57070159-347df200-6cf4-11e9-9940-89ccaf838640.png)

3) the text and the arrow to open/close dropdown overlaps. Refer above screen shot.

Please let me know the solution for this.

Below is the entry of dependency in my package.json file

> "angular2-multiselect-dropdown": "^4.2.1",

**Comment by CuppaLabs** [comment]
Try using css to hide it.
