### ISSUE TITLE
Is any Validation Example for template driven form

### ISSUE THREAD

**Issue by nikbe** [CuppaLabs/angular2-multiselect-dropdown#378]
How to create validation and generate error message when field is mandatory.

**Comment by CuppaLabs** [comment]
@nikbe Please refer to example @ https://cuppalabs.github.io/angular2-multiselect-dropdown/#/usinginform

**Comment by yogesh-mali44** [comment]
Validation error message works fine but is there a way of highlighting the dropdown if validation fails?  e.g apply red border if drop down is mandatory but not selected
