### ISSUE TITLE
concatenate labelKey  (label+label2)

### ISSUE THREAD

**Issue by mariobustosjmz** [CuppaLabs/angular2-multiselect-dropdown#379]
How I can show  two fields concatenate on labelKey property , I mean, I wanna show these like 

> "name : lastname" -> "Mario : Bustos"

Thanks.

**Comment by CuppaLabs** [comment]
@mariobustosjmz You have to concatenate the two labels in your controller class, and then pass it to the dropdown or use the template example(https://cuppalabs.github.io/angular2-multiselect-dropdown/#/templating) to concatenate the data. The dropdown component itself cannot provide this feature as the labelKey is unique

**Comment by mariobustosjmz** [comment]
Cool, Thanks!
