### ISSUE TITLE
Clicking on an angular-sortablejs row doesn't clear selection

### ISSUE THREAD

**Issue by dereklin** [CuppaLabs/angular2-multiselect-dropdown#38]
I am using a multiselect dropdown inside an angular-sortablejs row.

When I open up the dropdown, select an item, then unselect the same item, and click on the sortablejs row, the dropdown is closed.  When I open up the dropdown again, the item appears to be selected still.

For the above exercise: I open up the dropdown, select and item, then unselect the same item, if I click out outside of the row, at any blank space in the document, then things work as expected.

So the document.click handler does something special/extra.  Can you advise on what extra stuff it's doing to clear out any selection?  When I unselect an item when the dropdown is still open, I want to clear out the selection for good.  I don't want to rely on the document.click event.

**Comment by CuppaLabs** [comment]
can you take a video of the test case and send it to my mail solomon.terli@gmail.com

**Comment by dereklin** [comment]
@CuppaLabs I am trying to create a stackblitz, but was not able to install  angular2-multiselect-dropdown. 
 
https://stackblitz.com/edit/angular-kx3nsb?file=app%2Fapp.module.ts

However, I was able to install angular-sortablejs

The error is Unexpected token export.

I compared https://unpkg.com/angular2-multiselect-dropdown@1.2.5 with https://unpkg.com/angular-sortablejs@2.0.6

They look different.  Any ideas?

**Comment by CuppaLabs** [comment]
https://stackoverflow.com/questions/38296667/getting-unexpected-token-export

**Comment by dereklin** [comment]
I can't do a video at this point.  With with some debugging.  The problem is different from what I first described.  This is what I see:

1. I open the drop down
2. Select an item
3. Unselect an item
4. Click on somewhere in the sortable row
5. The item is selected -- The checkmark is there, but the item is not in the input box
6. Then the dropdown closes
7. The input box is empty
8. I open the dropdown again, the item is selected -- the checkmark is there

**Comment by dereklin** [comment]
Can I enable select/unselect only on the checkbox?

**Comment by dereklin** [comment]
Hum... I am limiting selection to 4.

When I open up the dropdown at the first time, I did select/unselect on 8 of them, 4 at a time, in the end, I unselect everything.

Now when I click on the row, every checkbox that was previously selected show the checkmark again, all 8 of them.

I am looking for a way to remove this "remembering" behavior...

**Comment by dereklin** [comment]
My workaround is to force re-render the angular2-multiselect component when the dropdown is closed, by cloning the [data] object.

Ideally, the angular2-multiselect should not give any opportunity to sortable.js to pollute the html content.
