### ISSUE TITLE
Type 'Boolean' is not assign able to type 'boolean'. in angular 2.3

### ISSUE THREAD

**Issue by Gajendrasinh** [CuppaLabs/angular2-multiselect-dropdown#380]
I am using angular 2.3 version on build using ng build --prod

below error is showing in angular2-multiselect-dropdown

ERROR in C:/Users/gazala/Desktop/GCDB_Workspace/GCDB6-portal/src/$$_gendir/node_modules/angular2-multiselect-dropdown/clickOutside.ngfactory.ts (159,9): Expected 0 arguments, but got 1.
ERROR in C:/Users/gazala/Desktop/GCDB_Workspace/GCDB6-portal/src/$$_gendir/app/cmf-account/account-view/account-view.component.ngfactory.ts (65702,5): The containing function or module body is
 too large for control flow analysis.
ERROR in C:/Users/gazala/Desktop/GCDB_Workspace/GCDB6-portal/src/$$_gendir/node_modules/angular2-multiselect-dropdown/multiselect.component.ngfactory.ts (3551,11): Type 'Boolean' is not assign
able to type 'boolean'.
  'boolean' is a primitive, but 'Boolean' is a wrapper object. Prefer using 'boolean' when possible.
ERROR in C:/Users/gazala/Desktop/GCDB_Workspace/GCDB6-portal/src/$$_gendir/node_modules/angular2-multiselect-dropdown/clickOutside.ngfactory.ts (74,35): Expected 2 arguments, but got 1.
ERROR in C:/Users/gazala/Desktop/GCDB_Workspace/GCDB6-portal/src/$$_gendir/node_modules/angular2-multiselect-dropdown/clickOutside.ngfactory.ts (113,9): Expected 0 arguments, but got 1.
ERROR in C:/Users/gazala/Desktop/GCDB_Workspace/GCDB6-portal/src/$$_gendir/node_modules/angular2-multiselect-dropdown/clickOutside.ngfactory.ts (159,9): Expected 0 arguments, but got 1.

**Comment by CuppaLabs** [comment]
@Gajendrasinh Please update the component package in your package.json and install latest version v4.2.3. This should be fixed.
