### ISSUE TITLE
cant able to run in angular 7

### ISSUE THREAD

**Issue by muhammedfayazp** [CuppaLabs/angular2-multiselect-dropdown#382]
Failed to compile.

../node_modules/angular2-multiselect-dropdown/fesm5/angular2-multiselect-dropdown.js
Module not found: Error: Can't resolve '@angular/common' in

**Comment by RFMV34** [comment]
We run 2 projects on Angular 7 and this library and it works

**Comment by muhammedfayazp** [comment]
can you help me

**Comment by RFMV34** [comment]
I do not know how, because we have not problems.

**Comment by Tcharl** [comment]
May be importing `@angular/common` in your package.json.

This lib works pretty well with `angular 7.2.12`.

If I had a wish, can it be renamed angularx-multiselect... or ngx-multiselect... ? 
It would bring more clear for users coming the project: originally, we picked up angular4-multiselect, which is a no more maintained fork of this project then switched to this one by luck. Read the angular4-multi documentation, come here and see more followers and recent commits...

Best regards and thank you so much for this marvelous component!
