### ISSUE TITLE
angular6-multiselect-dropdown dynamiccally bind

### ISSUE THREAD

**Issue by vikasamballa** [CuppaLabs/angular2-multiselect-dropdown#389]
This is working  
this.selectedItems = [
                                {"id":2,"itemName":"Singapore"},
                                {"id":3,"itemName":"Australia"}
                            ];

How can I add dynamically in loop?
Like 
 for (let a of this.serviceTypeSelectedItems) {
           this.selectedItems = [
        { "serviceTypeId": a.serviceTypeId, "serviceTypeName": a.serviceTypeName }
      ]
    }
It selecting last one, but can I selectable all in loop
Can you help here how can I select dynamically?

**Comment by sivailangos** [comment]
````
this.selectedItems = [];

for (let a of this.serviceTypeSelectedItems) {
    this.selectedItems.push(
        { "id": a.serviceTypeId, "itemName": a.serviceTypeName }
    )
}
````

It seems you are not appending the values into list

**Comment by vikasamballa** [comment]
No its not working like that.
Its resolved with this
 var list = [];
    for (let a of this.getSelectedItemServiceTypes) {
      this.selectedItems = [
        { "id": a.serviceTypeId, "itemName": a.serviceTypeName }
      ]
//every time its come only one item in foreach
      this.selectedItems.forEach((item: any) => {
        list.push(item);
      });
    }    
    Array.prototype.push.apply(this.selectedItems, list);
