### ISSUE TITLE
Length of undefined for selectedItems causing menu items disabled

### ISSUE THREAD

**Issue by zallen3** [CuppaLabs/angular2-multiselect-dropdown#39]
Was originally getting this error:
![multiselect_length_error](https://user-images.githubusercontent.com/10876692/29683485-290ca66a-88d4-11e7-982b-35226199da6c.PNG)

and the multiselect menu appeared like:
![menu_disabled](https://user-images.githubusercontent.com/10876692/29683493-2c6ccfc4-88d4-11e7-84ed-d8e1d6e75437.PNG)

I traced the issue back to not completely instantiating selectedItems
![selecteditems](https://user-images.githubusercontent.com/10876692/29683540-53c5ca94-88d4-11e7-9707-3d0f0123119b.PNG)

Change selectedItems to:
![selecteditems_fix](https://user-images.githubusercontent.com/10876692/29683635-a3f00552-88d4-11e7-923f-4751dc6e2c6c.PNG)

Instantiated selectedItems to an empty array and fixed the bug, no more error, and menu items appear normal.

**Comment by CuppaLabs** [comment]
This issue no more exists in the latest version. Please update the package.

**Comment by zallen3** [comment]
Cool Thanks
