### ISSUE TITLE
custom styling on error

### ISSUE THREAD

**Issue by timoberlin** [CuppaLabs/angular2-multiselect-dropdown#391]
If no selection on an angular2-multiselect-dropdown was made, this should be marked by a red border around the field. For normal input fields, this behavior can be achieved by the bootstrap class "invalid-feedback". Is there similar functionality for the dropdown?

<img width="793" alt="screen" src="https://user-images.githubusercontent.com/2080312/59582365-5aaaf600-90d8-11e9-9ca6-c2261c30d758.png">

**Comment by CuppaLabs** [comment]
Please use this example to catch errors https://cuppalabs.github.io/angular2-multiselect-dropdown/#/usinginform
