### ISSUE TITLE
Tested in Local v1.3.4 is working as expected.  Please clear your cache, update the package properly.

### ISSUE THREAD

**Issue by elibushehri** [CuppaLabs/angular2-multiselect-dropdown#395]
Tested in Local v1.3.4 is working as expected.  Please clear your cache, update the package properly.
**Warning !!** - @spa9999 - Please do not raise issues without thorough testing. 
![image](https://user-images.githubusercontent.com/3957664/31907103-7c3b7112-b850-11e7-9620-32063ff2fa94.png)

Hence closing.

_Originally posted by @CuppaLabs in https://github.com/CuppaLabs/angular2-multiselect-dropdown/issues/71#issuecomment-338759120_

**Comment by CuppaLabs** [comment]
Please use latest version v4.2.4
