### ISSUE TITLE
Update:

### ISSUE THREAD

**Issue by elibushehri** [CuppaLabs/angular2-multiselect-dropdown#396]
Update:

Actually issue is, its populating the data but still not displaying in the dropdown. When I select 'Select All' option, its showing all of the fields in the input box!. 
![2017-10-23 14_33_52-ortam web](https://user-images.githubusercontent.com/14339940/31906761-ebb61fa2-b7ff-11e7-8cbe-cdc6d9da1258.png)
![2017-10-23 14_36_57-ortam web](https://user-images.githubusercontent.com/14339940/31906765-ee214d34-b7ff-11e7-8dd8-9daf45af01ca.png)

_Originally posted by @spa9999 in https://github.com/CuppaLabs/angular2-multiselect-dropdown/issues/71#issuecomment-338756431_

**Comment by elibushehri** [comment]
I have same problem

**Comment by CuppaLabs** [comment]
Please use v4.2.4 . Also follow example @ https://cuppalabs.github.io/angular2-multiselect-dropdown/#/groupby
