### ISSUE TITLE
On deselect of checkbox, elements get removed from view/data.

### ISSUE THREAD

**Issue by 9561690684** [CuppaLabs/angular2-multiselect-dropdown#397]
Hi,

Initially I am populating all the values selected in my dropdown(all checkbox selected). Then after deselecting the values from dropdown its getting removed from selectedItems and data as well. I already debug the code but no luck.

Please let me know if anyone having any idea regarding this issue.

Thanks

**Comment by CuppaLabs** [comment]
What version are you using?

**Comment by CuppaLabs** [comment]
Your case is replicated at this example https://cuppalabs.github.io/angular2-multiselect-dropdown/#/basic
It works perfectly well and good. So closing the issue.

**Comment by santoshrshinde** [comment]
I have set all elements selected by assigning values in example.
import { Component, OnInit } from '@angular/core';

@Component({
    templateUrl: './views/basic.html'
})
export class BasicExample implements OnInit {

    itemList = [];
    selectedItems = [];
    settings = {};
    
    constructor() {}
    ngOnInit() {

        this.itemList = [
            { "id": 1, "itemName": "India" },
            { "id": 2, "itemName": "Singapore" },
            { "id": 3, "itemName": "Australia" },
            { "id": 4, "itemName": "Canada" },
            { "id": 5, "itemName": "South Korea" },
            { "id": 6, "itemName": "Brazil" }
        ];

        this.selectedItems = this.itemList;
        this.settings = {
            text: "Select Countries",
            selectAllText: 'Select All',
            unSelectAllText: 'UnSelect All',
            classes: "myclass custom-class"
        };
    onItemSelect(item: any) {
        console.log(item);
        console.log(this.selectedItems);
    }
    OnItemDeSelect(item: any) {
        console.log(item);
        console.log(this.selectedItems);
    }
    onSelectAll(items: any) {
        console.log(items);
    }
    onDeSelectAll(items: any) {
        console.log(items);
    }

    }

}


Now above code working fine, all element gets selected but not click the dropdown and try to uncheck one of option. Option gets removed from dropdown list.

**Comment by ThibautJoukes** [comment]
> I have set all elements selected by assigning values in example.
> import { Component, OnInit } from '@angular/core';
> 
> @component({
> templateUrl: './views/basic.html'
> })
> export class BasicExample implements OnInit {
> 
> ```
> itemList = [];
> selectedItems = [];
> settings = {};
> 
> constructor() {}
> ngOnInit() {
> 
>     this.itemList = [
>         { "id": 1, "itemName": "India" },
>         { "id": 2, "itemName": "Singapore" },
>         { "id": 3, "itemName": "Australia" },
>         { "id": 4, "itemName": "Canada" },
>         { "id": 5, "itemName": "South Korea" },
>         { "id": 6, "itemName": "Brazil" }
>     ];
> 
>     this.selectedItems = this.itemList;
>     this.settings = {
>         text: "Select Countries",
>         selectAllText: 'Select All',
>         unSelectAllText: 'UnSelect All',
>         classes: "myclass custom-class"
>     };
> onItemSelect(item: any) {
>     console.log(item);
>     console.log(this.selectedItems);
> }
> OnItemDeSelect(item: any) {
>     console.log(item);
>     console.log(this.selectedItems);
> }
> onSelectAll(items: any) {
>     console.log(items);
> }
> onDeSelectAll(items: any) {
>     console.log(items);
> }
> 
> }
> ```
> 
> }
> 
> Now above code working fine, all element gets selected but not click the dropdown and try to uncheck one of option. Option gets removed from dropdown list.

For people that have this same issue, make sure the itemlist and the selectedItems do not have the same reference.
