### ISSUE TITLE
Add multiselect in *ngFor loop.

### ISSUE THREAD

**Issue by aditivai** [CuppaLabs/angular2-multiselect-dropdown#399]
I want to add multiselect dropdowns in ngFor loop.
How to give dynamic function names to the (onSelect), (onAddFilterNewItem) etc function ?
Below is the code for reference:
------
`<div *ngFor="let m of types; let k = index">`
`<label class="col-form-label">Select Types: <span class="star-red">*</span></label>`
    ` <angular2-multiselect [data]="m.itemList" [(ngModel)]="m.selectedItems" [settings]="settings"  ``(onSelect)="onItemSelect{{m.divName}}($event)" (onDeSelect)="onItemDeSelect{{m.divName}}`
`($event)" (onSelectAll)="onSelectAll{{m.divName}}($event)" ``(onDeSelectAll)="onDeSelectAll{{m.divName}}($event)"
` `(onAddFilterNewItem)="onAddItem{{m.divName}}($event)" name="item{{m.planId}}" ``#item="ngModel"></angular2-multiselect> </div>`
----------------
the above code gives error:
ERROR Error: Uncaught (in promise): Error: Template parse errors:
Parser Error: Got interpolation ({{}}) where expression was expected at column 12 in [onItemSelect{{m.divName}}($event)] in ng:///DietitianModule/MealPlanComponent.html@71:22 ("elect [data]="m.itemList" [(ngModel)]="m.selectedItems" `[settings]="settings"`
                      [ERROR ->](onSelect)="onItemSelect{{m.divName}}($event)" (onDeSelect)="onItemDeSelect{{m.divName}}($event)"
   "): ng:///DietitianModule/MealPlanComponent.html@71:22

**Comment by CuppaLabs** [comment]
@aditivai Refer to example @ https://cuppalabs.github.io/angular2-multiselect-dropdown/#/usingInList
