### ISSUE TITLE
Feature to clear all the selection

### ISSUE THREAD

**Issue by foramkumar-parekh** [CuppaLabs/angular2-multiselect-dropdown#405]
I need to have a say 'x' to clear all the selected option in one go. Is there a way to do this?

@CuppaLabs if this is not yet available, can we expect it in the near future?

**Comment by foramkumar-parekh** [comment]
Do we have any update on this?
@CuppaLabs can you provide your thoughts on this?

**Comment by CuppaLabs** [comment]
fixed. v4.2.8
