### ISSUE TITLE
Styling Setting "text"

### ISSUE THREAD

**Issue by tq-birschl** [CuppaLabs/angular2-multiselect-dropdown#406]
If you have not selected anything and the "text" is displayed, there is a height difference of 2px as if something is selected. Is it possible to give the span of the "text" a class so I can change it directly? 

<class="c-btn">
<span **class="select-text"**>Select<span>

![heightDifferenceDropdown](https://user-images.githubusercontent.com/35221545/61522765-47f74a00-aa13-11e9-9fd5-5ea373731f02.png)

**Comment by CuppaLabs** [comment]
fixed in v4.2.8
