### ISSUE TITLE
Lazy Loading Remote Data white rectangle before items load

### ISSUE THREAD

**Issue by enoquemoises** [CuppaLabs/angular2-multiselect-dropdown#407]
Try to click the link bellow and before the items for the MultiSelect are loaded, open the Dropdown.

https://cuppalabs.github.io/angular2-multiselect-dropdown/#/lazyloadingRemoteData

It will show a blank white rectangle that won't disappear when the items arrive.

**Comment by CuppaLabs** [comment]
@enoquemoises fixed in v4.5.0
