### ISSUE TITLE
No event fires for select all or none of filtered items

### ISSUE THREAD

**Issue by cciccole** [CuppaLabs/angular2-multiselect-dropdown#408]
When using the search filter to limit the items, using the all/none filtered item checkbox does not result in any events being fired.

There needs to be some way of knowing when selections or deselections are made in this case.

**Comment by seraries** [comment]
I took a look at `angular2-multiselect-dropdown-umd.js` and found that there are events, they just aren't listed in the documentation. Using the following I was able to handle those filter select all and deselect all events.
```
            this.onFilterSelectAll = new core.EventEmitter();
            this.onFilterDeSelectAll = new core.EventEmitter();
```
Also in the documentation, it states that `enableCheckAll` is set to `false` by default, but it is actually set to `true`.

**Comment by CuppaLabs** [comment]
@cciccole feature already available. Documentation update is available as well.
