### ISSUE TITLE
allow search by passed function

### ISSUE THREAD

**Issue by cciccole** [CuppaLabs/angular2-multiselect-dropdown#410]
Right now search is pretty well supported. We have the default and multi-key approach as well as the fully custom approach. However, there is a bit of a usability gap between those options.

A good way to fill that gap would be by passing a search function. The signature of the function can be `(term: string, item: any): boolean` and then the component iterates all items and passes them to this function.

This is a nice feature in the `ng-select` package.

**Comment by CuppaLabs** [comment]
@cciccole custom search feature is already available. please refer to the following example http://localhost:4200/#/customSearchAPI
