### ISSUE TITLE
No event fired when clearing a single select dropdown

### ISSUE THREAD

**Issue by vincent-cm** [CuppaLabs/angular2-multiselect-dropdown#411]
"angular2-multiselect-dropdown": "~4.5.0",
    "@angular/core": "~8.2.1",
    "typescript": "3.5.3", 
     node: LTS --latest, macOS, npm: LTS --latest

The issue is after update to 4.5.0, in a single selection mode, the dropdown shows an unexpected x (clear button) when one item is selected.

However, it is not firing any event if using this button to clear the selection. (onDeSelectAll/onDeSelect not firing)

Should be an additional event to be added? Then could you please add a flag to enable the clear button (making sure it is persistent to previous versions)?

**Comment by CuppaLabs** [comment]
fixed. fix available in v4.6.0
