### ISSUE TITLE
Only the labelKey field is searched when using groupBy option.

### ISSUE THREAD

**Issue by pwinstead** [CuppaLabs/angular2-multiselect-dropdown#413]
I'm currently using version 4.5.0 but this issue is also reproducible on the demo site (https://cuppalabs.github.io/angular2-multiselect-dropdown/#/basic) which I assume is running latest.

The issue I'm seeing is that only the labelKey value will be searched if I am using the groupBy option. For example on the demo site example of group by (https://cuppalabs.github.io/angular2-multiselect-dropdown/#/groupby) I try filtering by 'Asia' and will get back no results in my filter, but I would expect both the Asia and Asia Pacific countries to be listed.  I also created my own version of this where gave each list item a 'region' property that was a duplicate value of the current category property. This still didn't solve the issue. I also specifically overrode the searchBy setting and included both the category and region properties.  Still it didn't filter on those properties.

**Comment by CuppaLabs** [comment]
Fixed. Fix available in v4.6.1
