### ISSUE TITLE
Not able to use Lazy loading with enableSearchFilter/onFilterSelectAll 

### ISSUE THREAD

**Issue by jbrischle** [CuppaLabs/angular2-multiselect-dropdown#414]
What happens is that if lazyLoading is enabled that all items getting selected instead of just the ones matching the filter/search.

https://stackblitz.com/edit/angular2-multiselect-dropdown-lazyloading
Here you can dis/enable the lazyLoading setting, for testing.

**Comment by CuppaLabs** [comment]
@jbrischle fixed. fix available in v4.6.3

**Comment by amandeepranaday** [comment]
I am not able to fire onFilterSelectAll() and onFilterDeSelectAll() if lazyLoading:true
it's working fine if lazyLoading:false
Can you please fix this issue
