### ISSUE TITLE
Disable cross sign when disabled=true

### ISSUE THREAD

**Issue by kapenzo** [CuppaLabs/angular2-multiselect-dropdown#415]
Hi everyone,

I disabled multiselect input (per settings or dynamicly doesn't metter) so I expect I am not able to change input. 

When I click the arrow sign nothing happened as expected.

But the X sign is still available and when I click it the selected item is cleared.

I would expect:
1. Hiding X when disabled=true; or
2. Add an option in settings to hide X no matter if the disabled=true or false; or
3. Still showing X but deactivate the behaviour

Is there some way to achieve such a behaviour ? Should we implement it ?

![image](https://user-images.githubusercontent.com/16196222/63600285-9031fb00-c5c3-11e9-96fa-0a1dc0769aef.png)

**Comment by CuppaLabs** [comment]
Fixed. Fix available in v4.6.1
