### ISSUE TITLE
Dropdown options are disabled by default

### ISSUE THREAD

**Issue by beanian** [CuppaLabs/angular2-multiselect-dropdown#42]
When the control loads the select options are disabled. Only by clicking Select All and then Unselect all do they become available again

Also the 'x' on the pills is missing...
See Plunker for example.
https://plnkr.co/edit/cgtU9GpTqq7vAlUtjNBk

**Comment by CuppaLabs** [comment]
plunker not created properly. Refer to demos at https://cuppalabs.github.io/angular2-multiselect-dropdown/  and usage at http://cuppalabs.github.io/components/multiselectDropdown/
