### ISSUE TITLE
Allow to change the message when there is no data

### ISSUE THREAD

**Issue by ocridlig** [CuppaLabs/angular2-multiselect-dropdown#43]
I need to translate component messages. But the message "No Data Available" seems to be hard coded.

Is it possible to add a setting for this message?

Thanks.

**Comment by JigSawFr** [comment]
See `text`setting on http://cuppalabs.github.io/components/multiselectDropdown/

**Comment by ocridlig** [comment]
Not the same message. 
* Text : Text to be show in the dropdown, when no items are selected.

The message I'm talking about appears when the list is empty.

**Comment by CuppaLabs** [comment]
@ocridlig You are right. Will add it in next release.

**Comment by Mridul16** [comment]
Even I need this. Please help add it in the next build ASAP

**Comment by gray0072** [comment]
Please try noDataLabel property.
dropdownSettings = {
    ...other settings
    noDataLabel: 'No data available. It seems you have no access rights'
};
I've found it here https://github.com/CuppaLabs/angular2-multiselect-dropdown/blob/88aaa027c6f63763871cad91aaf6eb3946b6fd49/src/app/angular2-multiselect-dropdown/multiselect.component.ts#L100

**Comment by CuppaLabs** [comment]
Please refer to settings configuration in the documentation. All labels are configurable.

**Comment by RoshiniLamba** [comment]
noDataLabel can be done only if the data isn't available . What if the dropdown takes time to load the data ? i want to show "loading" instead of a hard-coded "no Data Available". how do i change the text ?

**Comment by PankajMSharma** [comment]
@RoshiniLamba You would have to change the whole object of settings. This is because while change detection angular only check the reference of the object. Reference changes for setting only when we assign a new object to settings.
Eg.
`settings = {...settings, noDataLabel: 'Loading..'}`
