### ISSUE TITLE
Clear search box after dropdown closed

### ISSUE THREAD

**Issue by xavier-experion** [CuppaLabs/angular2-multiselect-dropdown#44]
How can we clear the search box field after multi select drop down is closed ?
As of now the searched text is always persists in the field and the list is always filters based this value.
Thanks and Regards

**Comment by CuppaLabs** [comment]
fixed. Please refer to https://cuppalabs.github.io/angular2-multiselect-dropdown/ for demo. However, please wait for next release to reflect in npm package.
