### ISSUE TITLE
Want dropdown to open only in Bottom not in top and position option not working

### ISSUE THREAD

**Issue by samir-kamble** [CuppaLabs/angular2-multiselect-dropdown#449]
I want to have a drop down that always opens in bottom. But when body dont have sufficient space in bottom it automatically opens in top. 

Even if I gave position: 'bottom' in options it still opens in top.

But if I give position: 'top' in options it always opens in top irrespective of body position. 

Please help.

Sam.

**Comment by davidecampello** [comment]
Hi have the same problem. 
Thanks

**Comment by jiangmf** [comment]
was having the same issue, setting `autoPosition: false,` fixed it for me

**Comment by BijithNV** [comment]
Where this property needs to be set ?

**Comment by samhei03** [comment]
> Where this property needs to be set ?
You can find it in DropdownSettings interface.

**Comment by karanbedre** [comment]
> was having the same issue, setting `autoPosition: false,` fixed it for me

can u specify where this needs to be put

**Comment by hide-pms** [comment]
Hi Position:'top', Not working I have the same problem.

**Comment by SteffiKeranJ** [comment]
In the dropdown settings where you specify the `position:bottom`, you should be specifying the `autoPosition: false`. This worked for me and opened the dropdown always at bottom.

My dropdown settings looked like this
`settings = {
  position: 'bottom',
  autoPosition: false
};`

**Comment by karanbedre** [comment]
> In the dropdown settings where you specify the `position:bottom`, you should be specifying the `autoPosition: false`. This worked for me and opened the dropdown always at bottom.
> 
> My dropdown settings looked like this
> `settings = { position: 'bottom', autoPosition: false };`

thanks alot, it worked for me

**Comment by ankurraiyani** [comment]
> Hi Position:'top', Not working I have the same problem.

Did you get any solution? I am facing same issue.

**Comment by karanbedre** [comment]
> > Hi Position:'top', Not working I have the same problem.
> 
> Did you get any solution? I am facing same issue.

settings = { position: 'bottom', autoPosition: false };

**Comment by ankurraiyani** [comment]
@karanbedre That's for the bottom. I need to open at top.

**Comment by samir-kamble** [comment]
Closed as no solution

**Comment by vlo-rte** [comment]
Hi,
autoPosition set to true (default value) does not work when the list appears at the top, no ?

**Comment by punithgeepalyam** [comment]
<img width="213" alt="image" src="https://user-images.githubusercontent.com/80587722/173771883-1503b98f-0269-42a1-b2cc-3f8dc3d1b63d.png">

As like the above screenshot,
we need to define the position and autoPosition properties in the settings. It will work.
