### ISSUE TITLE
html goes down when select single checkbox entry

### ISSUE THREAD

**Issue by ankita199** [CuppaLabs/angular2-multiselect-dropdown#45]
https://cuppalabs.github.io/angular2-multiselect-dropdown/ 
When i select single item in MultiSelect, Show all Selected, Select All, it makes below html tags to down

**Comment by avanithikab** [comment]
Could you please confirm on this issue whether it is fixed or not.

**Comment by CuppaLabs** [comment]
fixed. However please wait for next release to reflect in npm package.
