### ISSUE TITLE
high debounceTime

### ISSUE THREAD

**Issue by aishwaryardandi** [CuppaLabs/angular2-multiselect-dropdown#468]
hi @CuppaLabs I wanted to know why you have such a high debounceTime (1000) for search in lazyLoading enabled selectors? Sometimes when someone enters 4 letters or less really fast, it doesnt take it into consideration and this is caused by the debounceTime. You can also see this on your demo page.

Steps to reproduce:

1) Open the multiselector on https://cuppalabs.github.io/angular2-multiselect-dropdown/#/lazyloading

2) Search for anything (1st time works fine), do not select it.

3) Click anywhere outside to close the dropdown

4) Search for the same, result list doesnt change.

**Comment by youthrone01** [comment]
@CuppaLabs i am also facing this issue. i feel the debounceTime(1000) it is ok if search for large amount of data. My solution is to call searchTerm$.next('') when close dropdown for search in lazyloading.

**Comment by CuppaLabs** [comment]
@youthrone01 @aishwaryardandi please use version v5.0.3. This is fixed now.
