### ISSUE TITLE
Data from server

### ISSUE THREAD

**Issue by rupeshtare** [CuppaLabs/angular2-multiselect-dropdown#48]
i have 1000's of records and i don't want to load all at initial time. i want to just display 10 records at initial and after search i want to do server call.

**Comment by sachinkasana** [comment]
Hi Rupeshtare,
you can make it auto-complete from server side also. as i have added-
 <angular2-multiselect [data]="citiesList" name="selectedCity" [(ngModel)]="selectedCities" #selectedCity="ngModel" required [settings]="dropdownCities" (onSelect)="onCitySelect($event)" (onDeSelect)="OnCityDeSelect($event)" **(keyup)="filter($event)"**></angular2-multiselect>

filter(key: any) {
        if (key.target.value.length > 2) {
            this._getStartedService.getCityList(key.target.value).subscribe(
                response => {
                    debugger;
                    this.citiesList = response.data.data;
},
                error => {
                    this.flashMessagesService.show(error, { cssClass: 'alert-danger custom-alert ', timeout: 5000 });
                });
        }
    }

**Comment by junalmeida** [comment]
I guess that this should be reopened, in order to improve documentation and examples on loading data from server.
