### ISSUE TITLE
Deselecting all checked element pressing X doesn't trigger any event, just removes the elements from the list

### ISSUE THREAD

**Issue by Yorer** [CuppaLabs/angular2-multiselect-dropdown#483]
Currently I've tried to catch an event, when the main 'X' button has pressed which can clear all list. I've tried to catch this event with "onDeSelect" and "onDeSelectAll" as well. None of them triggered.

So my question is: Is there any event there I can catch when I press X button? If no, can you add one, please?

By the way I really like it's working, so thank's for this component.

**Comment by ircheg** [comment]
The event which is triggered on 'X' button is clearSelection. I fixed the issue you described in #479 
But seems that it needs to be reviewed and then it will be automatically merged. You can speed up this - just make a review. Please have a look at my fix, it's small enough.

**Comment by Yorer** [comment]
Yes it is working now thanks
