### ISSUE TITLE
Form template validation

### ISSUE THREAD

**Issue by alokekantal** [CuppaLabs/angular2-multiselect-dropdown#488]
How can i validate this dropdown for template based validation. Successfully validate formgroup validation. but unable to validate using template validation. I am giving my code snapshot.
`<form name="form" (ngSubmit)="f.form.valid && downloadReport()" #f="ngForm" novalidate><angular2-multiselect [data]="dataList" [ngModelOptions]="{standalone: true}"
                  [(ngModel)]="data" [settings]="config" name="data" #data="ngModel" required>
                </angular2-multiselect><form>`

By using this data is invalid but entire form treated as valid in I  don't select any thing.

**Comment by CuppaLabs** [comment]
@alokekantal please refer to https://cuppalabs.github.io/angular2-multiselect-dropdown/#/usinginform working as expected.
