### ISSUE TITLE
Add to settings a default open state

### ISSUE THREAD

**Issue by jpriesten** [CuppaLabs/angular2-multiselect-dropdown#489]
Hi @CuppaLabs, I have been using _angular2-multiselect-dropdown_ for a while now but I have always found it difficult to **open the dropdown** without having to click on it. 

Thanks for looking into this.

I am currently using:
```
Angular:  "9.0.1"
angular2-multiselect-dropdown: "4.6.3"
```

**Comment by jaffbeto** [comment]
i have similar issue. The main problem is that it cannot be opened with keyboard navigation (tab + enter or tab + space or tab + down arrow).
I have tried to force it with javascript but there is no way to tell the component to open it is missing something like "element.open()" by referring to itself as #element

**Comment by CuppaLabs** [comment]
@jaffbeto @jpriesten please use latest version v5.0.4. Refer to example https://cuppalabs.github.io/angular2-multiselect-dropdown/#/dropdownMethods to open on click of button
