### ISSUE TITLE
search result issue when lazyloading enabled

### ISSUE THREAD

**Issue by youthrone01** [CuppaLabs/angular2-multiselect-dropdown#492]
1. type in search value
2. click clear icon in end of search box
3. type in the same value as first time, search function not working at this time.

due to debounceTime(1000) and distinctUntilChanged(), type the same value will not fire the search function. Below is a similar issue to this one.

https://github.com/CuppaLabs/angular2-multiselect-dropdown/issues/468

**Comment by CuppaLabs** [comment]
@youthrone01 Please refer to https://cuppalabs.github.io/angular2-multiselect-dropdown/#/lazyloading . Working as expected.

**Comment by CuppaLabs** [comment]
@youthrone01 please use version v5.0.3. This is fixed now.
