### ISSUE TITLE
both single and multiple selection

### ISSUE THREAD

**Issue by susandotmark** [CuppaLabs/angular2-multiselect-dropdown#494]
Very good component, love it. I ran into a problem where there is a need for both single selection for certain category and multiple selection for another category. Can this be done? or any workaround how this can be achieved?

**Comment by CuppaLabs** [comment]
Thank you. Please refere to https://cuppalabs.github.io/angular2-multiselect-dropdown/#/singleselection and https://cuppalabs.github.io/angular2-multiselect-dropdown/#/multipledropdowns. In case you have a specific requirement, please do write to me/ create stackblitz and send me.
