### ISSUE TITLE
Search is not working correctly in angular2-multi-select

### ISSUE THREAD

**Issue by adityas140797** [CuppaLabs/angular2-multiselect-dropdown#495]
Let's suppose if I have countries like India, Australia, USA, Britain in my dropdown list and I search q, it is showing me "No Data Available", which is fine, but if I use the backspace key once to erase it. It is showing me nothing, no message and not even the list.

Used property enableSearchFilter: true to enable and my data is present as [{"id":1, "itemName":India}]. If I have missed anything, please inform me.

**Comment by CuppaLabs** [comment]
@adityas140797 Working as expected. Please refer to example https://cuppalabs.github.io/angular2-multiselect-dropdown/#/searchfilter
