### ISSUE TITLE
On select all I want to show one pill like "All selected". 

### ISSUE THREAD

**Issue by hide-pms** [CuppaLabs/angular2-multiselect-dropdown#497]
In the dropdown, all item selection action I want one feature like -
1- User will open the dropdown
2- CLick on "ALL selected"
3- Only one pill should be displayed in input- **"All selected"** 
Final Output should be like these. 
![output](https://user-images.githubusercontent.com/21213996/87794334-14d4da00-c864-11ea-8925-df83e8ef3576.PNG)

**Comment by CuppaLabs** [comment]
Usability wise that's not a good solution.
