### ISSUE TITLE
will this support Angular 9 

### ISSUE THREAD

**Issue by ahavagowtham** [CuppaLabs/angular2-multiselect-dropdown#498]
Getting this error in Angular 9. Kindly clarify on Angular 9 support.

ERROR NullInjectorError: R3InjectorError(AppModule)[DataService -> DataService -> DataService]: 
  NullInjectorError: No provider for DataService!
    at

**Comment by reimavronicolas** [comment]
@ahavagowtham Yes it works fine in Angular 9. Your error seems not related to this component, but rather something in your own application.
