### ISSUE TITLE
Typescript Error

### ISSUE THREAD

**Issue by jj-julia** [CuppaLabs/angular2-multiselect-dropdown#5]
After npm installing the module in my project, and adding it to my app.module file I get three  errors stating:  **Parameter 'index' implicitly has an 'any' type**.

Is this an error because i haven't set it up correctly with system.js?

**Comment by CuppaLabs** [comment]
Hi, I am using angular-cli and ECMA2016 for compilation. What version of ecma are you using for compiling the code ?

**Comment by CuppaLabs** [comment]
cannot reproduce. hence, closed.
