### ISSUE TITLE
how to get custom value

### ISSUE THREAD

**Issue by ngochiep30051998** [CuppaLabs/angular2-multiselect-dropdown#501]
How can I customize the output value if I do not want to use the map function ?. 
example: 
itemList = [
            { "id": 1, "itemName": "India" },
            { "id": 2, "itemName": "Singapore" },
            { "id": 3, "itemName": "Australia" },
            { "id": 4, "itemName": "Canada" },
            { "id": 5, "itemName": "South Korea" },
            { "id": 6, "itemName": "Brazil" }
        ];
output : ['Singapore','Brazil']

**Comment by CuppaLabs** [comment]
The data models needs to be intact in order to maintain the uniqueness of the given list item. Working as expected.
