### ISSUE TITLE
(angular2-multiselect-dropdown) Groupby and Filtering does not work at same time

### ISSUE THREAD

**Issue by maheennasir18** [CuppaLabs/angular2-multiselect-dropdown#505]
After implementing groupBy, I am faced a lot of issues. E.g Filter something and than click "select filtered items" but nothing gets selected. I tested it directly on cuppalabs demo page and functionality is not even working there. 

https://cuppalabs.github.io/angular2-multiselect-dropdown/#/groupby

**Comment by CuppaLabs** [comment]
@maheennasir18 Please use latest version v5.0.1. This is fixed now.
