### ISSUE TITLE
How to check/uncheck the select all checkbox programmatically ?

### ISSUE THREAD

**Issue by saratSubramaniam** [CuppaLabs/angular2-multiselect-dropdown#51]
Hello,
I have to meet this requirement where all the items of the drop down should be selected by default, and I was able to achieve this by pre-populating the ngModel array. But at the same time, the select all checkbox should be pre-checked to make it logical.
Is there a way to programmatically check/uncheck the select-all checkbox ?

**Comment by frans-beech-it** [comment]
guess that PR #47 would make this possible

**Comment by rasmk** [comment]
I would be surprised if PR #47 alone helped.
Select all is displayed in reaction to an event (drop-down) and event triggers change detection anyway.

Had a quick look into the code and `writeValue` seems to take care of the select-all checkbox.
```TypeScript
                if(this.selectedItems.length === this.data.length && this.data.length > 0){
                            this.isSelectAll = true;
                        }
```
@saratSubramaniam if you compare length of arrays you pass to the ngModel and data input, do you have the same here and there?

**Comment by CuppaLabs** [comment]
Coming up, API methods to access the features programatically. Stay tuned.. Probably in next week release, you would be getting these features.

**Comment by avanithikab** [comment]
1) Can you please confirm whether this issue addressed in the latest code. Still I am seeing same issue with check all.
2) One more issue is when we select the items its showing all the name beside select instead of number of items selected. Could you please check.

**Comment by CuppaLabs** [comment]
fixed. please see the examples at https://cuppalabs.github.io/angular2-multiselect-dropdown/#/basic
