### ISSUE TITLE
Unable to open Dropdown

### ISSUE THREAD

**Issue by margi212** [CuppaLabs/angular2-multiselect-dropdown#517]
@CuppaLabs 

I am unable to open Dropdown on button click using openDropDown() Method in version 4.6.3

Please help ASAP.

Reprocduce Link is here : `https://stackblitz.com/edit/r7-angular2-multislect-8as6pk?file=src%2Fapp%2Fapp.component.html`
Following is the code snippet:

```
<angular2-multiselect [data]="dropdownList" [(ngModel)]="selectedItems" [settings]="dropdownSettings" #dropdownRef> </angular2-multiselect>
    
     <button (click)="openDropdown" >
       Click Here to Open Dropdown
     </button>

@ViewChild('dropdownRef',{static:false}) dropdownRef: AngularMultiSelect;
        
     openDropdown(){
         // Open Dropdown Method not working
        this.dropdownRef.openDropdown();
     }
```

**Comment by CuppaLabs** [comment]
Please use this corrections at https://r7-angular2-multislect-flh7o9.stackblitz.io

**Comment by leonidas4321** [comment]
ERROR Error: If ngModel is used within a form tag, either the name attribute must be set or the form
      control must be defined as 'standalone' in ngModelOptions.

      Example 1: <input [(ngModel)]="person.firstName" name="first">
      Example 2: <input [(ngModel)]="person.firstName" [ngModelOptions]="{standalone: true}">
    missingNameException http://localhost/front-chaos/main-es2015.bad95e5f9ab71c099259.js:2
    _checkName http://localhost/front-chaos/main-es2015.bad95e5f9ab71c099259.js:2
