### ISSUE TITLE
Unable to use select all in angular2-multiselect-dropdown

### ISSUE THREAD

**Issue by atish11pune** [CuppaLabs/angular2-multiselect-dropdown#518]
Hi @CuppaLabs,
can not use select all feature only if the installed library is version angular2-multiselect-dropdown 4.6.4.
other features are working fine like single select and search in dropdown options.

> actual issue is - when you click once on select all checkbox or button then all dropdown options will be selected and immediately gets deselected, I have used (onSelectall) hook and logged selection array.
if the installed library is version angular2-multiselect-dropdown 4.6.3 it works fine, I think the problem is with newly released version(4.6.4).

HTML-
<div class="form-group">
                            <label>State</label>
                                <angular2-multiselect
 [data]="stateList" [(ngModel)]="selectedStateList" [settings]="stateDropdownSettings" (onSelect)="stateChanged()" (onDeSelect)="stateChanged()" (onSelectAll)="stateChanged()" (onDeSelectAll)="stateChanged()" name="statecode" #statecode="ngModel"
                                    required>
                                    <c-item>
                                        <ng-template let-item="item">
                                            <label class="multi-select-overflow" title={{item.itemName}}>{{item.itemName}}
            ({{item.id}})</label>
                                        </ng-template>
                                    </c-item>
                                </angular2-multiselect>
                                <label class="fa fa-map-marker multi-drop-icon"></label>
                            </div>
                        </div>

dropdown setting-

      singleSelection: false,
      text: 'Select State',
      enableSearchFilter: true,
      enableFilterSelectAll: false,
      showCheckbox: true,
      badgeShowLimit: 0

hooked method-
stateChanged()
  {
    console.log(this.selectedStateList);
  }

Angular CLI version: 9.0.7
Node version: 10.15.3
Please reply and fix ASAP.
attached screenshot for more reference.
if you want to know more about an issue, please drop a mail on-atish11pune@gmail.com
Thank you!

![angular2-multiselect](https://user-images.githubusercontent.com/43402878/93972701-65027800-fd90-11ea-8e97-c2e5ef417ba5.png)

**Comment by rickvandermey** [comment]
Encountered the same problem, the parent div is clickable, but the checkbox and textfield isnt clickable

**Comment by engrshamie** [comment]
I'm having the same issue. Using the latest version too. Is there a fix to this already?

**Comment by atish11pune** [comment]
@engrshamie 
You can use angular2-multiselect-dropdown 4.6.3 version it works fine.

**Comment by engrshamie** [comment]
> @engrshamie
> You can use angular2-multiselect-dropdown 4.6.3 version it works fine.

@atish11pune yep. using that now and it works fine. thanks

**Comment by findela** [comment]
@atish11pune *4.6.3 won't work as it will try ti find next minor release ^4.6.4, so must only **4.6.3**, no patch update

**Comment by CuppaLabs** [comment]
In progress.

**Comment by CuppaLabs** [comment]
Fixed. v4.6.5

**Comment by atish11pune** [comment]
@CuppaLabs Thank you for your support!

**Comment by atish11pune** [comment]
@CuppaLabs Used v4.6.5 and it is working now.
