### ISSUE TITLE
Ivy warning after upgrading to angular 10

### ISSUE THREAD

**Issue by xchimera** [CuppaLabs/angular2-multiselect-dropdown#523]
I get the following warning when i build my application:

node_modules\angular2-multiselect-dropdown\__ivy_ngcc__\fesm2015\angular2-multiselect-dropdown.js depends on '@tweenjs/tween.js'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Is this a real issue, or am i doing something wrong?
I am converting my app to nx, and am paying special attention to warnings beacause of this.

**Comment by sysmat** [comment]
angular2-multiselect-dropdown [es2015/esm2015] (git+https://github.com/CuppaLabs/angular2-multiselect-dropdown.git)
Encourage the library authors to publish an Ivy distribution.

in angular 13
