### ISSUE TITLE
select all for multiple dropdowns broken in 4.6.5?

### ISSUE THREAD

**Issue by mado89** [CuppaLabs/angular2-multiselect-dropdown#527]
Hi,
when I try to have multiple dropdowns on a single page clicking 'select all' on the second drowdown selects all elements from the first one. Clicking 'select all' on the first one behaves as expected. I also tested this with the sample code provided (https://cuppalabs.github.io/angular2-multiselect-dropdown/#/multipledropdowns) and Angular 10.
Can you / could someone check if the last fixes have broken something?
Thanks!

**Comment by devglen** [comment]
This is a huge show stopper for me, is there any workaround?

**Comment by dzienskaj** [comment]
> This is a huge show stopper for me, is there any workaround?

You can try my fork #530

**Comment by mado89** [comment]
@dzienskaj Is there a way I can test your workaround in an easy way? eg applying it to the downloaded files in node_modules of the app

**Comment by dzienskaj** [comment]
@mado89 You can try replacing files but i have no idea if it will work. What we did is we built it using npm task and published it to npm

These identations were autoformatted by my IDE. Also there's no reason why empty line should have indentation anyway, if you check this project most empty lines don't have any.

I honestly have no idea why changedetection was were it was and i can only speculate that the reason it was there is angular's `Expression has changed after it was checked` error and DOM not refreshing properly because of that. Basically when data was changed in `subscribe` it wasn't changed in the DOM, so i think they used it to refresh it. `delay(0)` does the same thing and is sugested solution in this article https://blog.angular-university.io/angular-debugging/. As for if it will break anything i have honestly no idea if it fixes every usecase ie. `groupBy` or `lazyLoading` because in my team we are not using it, but there's no reason why it would. All i can say is that we had same issue in our application and this fork fixed our usecase so you might aswell try

**Comment by devglen** [comment]
> @mado89 You can try replacing files but i have no idea if it will work. What we did is we built it using npm task and published it to npm
> 
> These identations were autoformatted by my IDE. Also there's no reason why empty line should have indentation anyway, if you check most of empty lines in this project don't have any
> 
> I honestly have no idea why changedetection was were it was and i can only speculate that the reason it was there is angular's `Expression has changed after it was checked` error and DOM not refreshing properly because of that. Basically when data was changed in `subscribe` it wasn't changed in the DOM, so i think they used it to refresh it. `delay(0)` does the same thing and is sugested solution in this article https://blog.angular-university.io/angular-debugging/. As for if it will break anything i have honestly no idea if it fixes every usecase ie. `groupBy` or `lazyLoading` because in my team we are not using it, but there's no reason why it wouldn't. All i can say is that we had same issue in our application and this fork fixed our usecase so you might aswell try

When you published your forked version to npm, is it publicly available? For example, can I npm i your version?

**Comment by dzienskaj** [comment]
@devglen we did it using npm's organization scoped package and i don't think they are public. Also we did this fix on older version of this library don't remember which one but i think either 4.3.* or 4.2.*. But it also works on latest version since it was the one i figured out how to fix it

**Comment by devglen** [comment]
> @devglen we did it using npm's organization scoped package and i don't think they are public. Also we did this fix on older version of this library don't remember which one but i think either 4.3.* or 4.2.*. But it also works on latest version since it was the one i figured out how to fix it

Thank you so much! Last question :D would you happen to have any documentation as to how to package and publish the way you did? I hav never done anything like this.

**Comment by dzienskaj** [comment]
@devglen No problem. I'm not an expert in fact fixingu this lib was my first time doing it. First you need to clone my fork, than cerate npm account and follow this manual https://docs.npmjs.com/creating-and-publishing-an-organization-scoped-package and plublish repo. You need to remember that library is in catalog `src/lib` and the outter files are wrapper basically whole examples page.  Good luck

**Comment by devglen** [comment]
> @devglen No problem. I'm not an expert, in fact fixing this lib was my first time publishing anything to npm. First you need to clone my fork, than cerate npm account and follow this manual https://docs.npmjs.com/creating-and-publishing-an-organization-scoped-package and plublish repo. Keep in mind that library is in catalog `src/lib` and the outter files are wrapper basically whole examples page. Good luck

Thank you sooo much!!

**Comment by dzienskaj** [comment]
@devglen np. hope it fixes your issue

**Comment by joffarex** [comment]
@CuppaLabs what is the status on this one? will this get merged? 

I could use a solution @dzienskaj provided, but i really do not want to create my own package temporarily and use it. would be awesome if this #530 got merged asap

**Comment by CuppaLabs** [comment]
Please use v4.6.6

**Comment by devglen** [comment]
> Please use v4.6.6

thank you so much! It is working now!

**Comment by joffarex** [comment]
Good work guys
