### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by Basit-qc** [CuppaLabs/angular2-multiselect-dropdown#528]
Hi,

I am trying to integrate this module with my angular app. Getting
```core.js:1449 ERROR RangeError: Maximum call stack size exceeded```
on
```ScrollDirective.onClick @ angular2-multiselect-dropdown.js:80```

Line 80 goes as below:
``` 
    ScrollDirective.prototype.onClick = /**
     * @param {?} event
     * @param {?} targetElement
     * @return {?}
     */
    function (event, targetElement) {
        this.scroll.emit(event);
    };
```

Even in the production build, this error stays there.
If I do not load this module in my `app.module.ts`, this error is gone.

My angular version is v5.2.0

Anything I am missing in integration? @CuppaLabs

**Comment by CuppaLabs** [comment]
please update angular version. Latest version of the component works best with angular v8.0 + . Backward compatibility is not maintained at the moment.
