### ISSUE TITLE
Disabled: true not works 

### ISSUE THREAD

**Issue by ashjha1** [CuppaLabs/angular2-multiselect-dropdown#53]
public citySelectionSettings = {
                              text:"Select Countries",
                              selectAllText:'Select All',
                              unSelectAllText:'UnSelect All',
                              enableSearchFilter: false,
                              classes:"myclass custom-class",
                              limitSelection: 2,
                              disabled: true
  };

**Comment by CuppaLabs** [comment]
Working as expected. refer to https://github.com/CuppaLabs/angular2-multiselect-dropdown/blob/master/src/app/app.component.ts for example code

**Comment by nitishdigiapt** [comment]
How I'll apply the custom class can you please give a example of dropdown with custome class (with css code on textbox with border).
