### ISSUE TITLE
angular2-multiselect-dropdown.js depends on '@tweenjs/tween.js'. CommonJS or AMD dependencies can cause optimization bailouts. For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

### ISSUE THREAD

**Issue by SkrupSulten** [CuppaLabs/angular2-multiselect-dropdown#532]
I'm getting this error when building an Angular 11 application using our prod configuration:

Version: 4.6.5

> angular2-multiselect-dropdown.js depends on '@tweenjs/tween.js'. CommonJS or AMD dependencies can cause optimization bailouts.
> For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

**Comment by mado89** [comment]
Same with Angular 10

**Comment by CuppaLabs** [comment]
In your project you can include in build options in angular.json file.         
"allowedCommonJsDependencies": [
              "@tweenjs/tween.js"
           ],
