### ISSUE TITLE
modifying search filter does not update results until I click within the search/filtering component

### ISSUE THREAD

**Issue by lain-mack** [CuppaLabs/angular2-multiselect-dropdown#534]
I have the following options set for my dropdown:
```
{
    singleSelection: true,
    enableSearchFilter: true,
    addNewItemOnFilter: true
}
```

Unless I click within the search/filtering component after typing a letter, the filter used is one letter behind what I've typed.

Angular 10
angular2-multiselect-dropdown v4.2.1

**Comment by jpr303** [comment]
This is a duplicate of #524
