### ISSUE TITLE
cannot add new item on single selection dropdown without leaving enableFilterSelectAll as true

### ISSUE THREAD

**Issue by lain-mack** [CuppaLabs/angular2-multiselect-dropdown#535]
It doesn't make sense to have a "Select all filtered results" option on a single selection dropdown, but without it, the ability to add a new item does not appear or work.
Here are my dropdown options:
```
{
    singleSelection: true,
    enableSearchFilter: true,
    enableFilterSelectAll: true,
    addNewItemOnFilter: true
  }
```
(I'd like to be able to set enableFilterSelectAll to false and still be able to add a new item.)

Angular 10
angular2-multiselect-dropdown v4.2.1

**Comment by CuppaLabs** [comment]
Fixed. Please use latest version
