### ISSUE TITLE
clear-all ('x') icon is different from unselect-all checkbox

### ISSUE THREAD

**Issue by MPeli** [CuppaLabs/angular2-multiselect-dropdown#537]
Hi,

  I am checking [this example](https://cuppalabs.github.io/angular2-multiselect-dropdown/#/usinginreactiveform). I have got these two workflows:

The first one
- Select all skills
- Click clear-all icon (looks like an 'x')
- Form status: "**VALID**"

The second one
- Select all skills
- Click "UnSelect All"
- Form status: "**INVALID**"

I would expect that the form status should be invalid in both cases. Is that by design or it is a bug?

-  [clearSelection](https://github.com/CuppaLabs/angular2-multiselect-dropdown/blob/master/projects/angular2-multiselect-dropdown-lib/src/lib/multiselect.component.ts#L881)
- [toggleSelectAll](https://github.com/CuppaLabs/angular2-multiselect-dropdown/blob/master/projects/angular2-multiselect-dropdown-lib/src/lib/multiselect.component.ts#L447)

Thank you, Martin.

**Comment by CuppaLabs** [comment]
fixed. fix available in v4.6.7

**Comment by MPeli** [comment]
Thank you.
