### ISSUE TITLE
"Select All" clicking on white space used to work with Angular 6 & 4.0.0 version but not on Angular 9 & 4.6.6 version

### ISSUE THREAD

**Issue by kadivi** [CuppaLabs/angular2-multiselect-dropdown#541]
On Angular 6 & with version 4.0.0, clicking on the white space to the right for "Select All" used to work and add all the items just like the individual items in the list. 

What this means is that the item selection works even when we click on white space to the right but not for select all / unselect all.

So is there a way to make it work the same way for "Select All / Unselect All" with version 4.6.6 or later irrespective of Angular version? OR is there something that I can configure to make it work.

**Comment by CuppaLabs** [comment]
@kadivi This is removed intentionally as this is not a menu item.
