### ISSUE TITLE
ExpressionChangedAfterItHasBeenCheckedError

### ISSUE THREAD

**Issue by sysmat** [CuppaLabs/angular2-multiselect-dropdown#544]
- versions:
```
@angular-devkit/core            11.0.5
"angular2-multiselect-dropdown": "^4.6.9",
```
- error when clicking on the component
```
ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value for 'top': '563'. Current value: '166'.
    at throwErrorIfNoChangesMode (core.js:6536)
    at bindingUpdated (core.js:12647)
    at checkStylingProperty (core.js:16475)
    at ɵɵstyleProp (core.js:16364)
    at AngularMultiSelect_Template (angular2-multiselect-dropdown.js:4661)
    at executeTemplate (core.js:9310)
    at refreshView (core.js:9179)
    at refreshComponent (core.js:10345)
    at refreshChildComponents (core.js:8976)
    at refreshView (core.js:9229)
```

**Comment by sysmat** [comment]
From dev log it is on:

```
ɵngcc0.ɵɵstyleProp("width", ctx.dropDownWidth, "px")("top", ctx.dropDownTop, "px")("left", ctx.dropDownLeft, "px");
        ɵngcc0.ɵɵproperty("hidden", !ctx.isActive);
        ɵngcc0.ɵɵadvance(2);
```

**Comment by sysmat** [comment]
with version angular2-multiselect-dropdown:4.6.6 there is no problem

**Comment by fdiogoc** [comment]
Same here 

`core.js:5967 ERROR Error: NG0100: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value for 'top': '0'. Current value: '1'.`

**Comment by GillesMontyne** [comment]
same issue here, 4.6.6 is working though

**Comment by sysmat** [comment]
is there any planning for solution of this bug?

**Comment by orahul1** [comment]
any solution ?

**Comment by rituyadav95** [comment]
I am also facing the same issue, is there any solution expected for this bug?

**Comment by orahul1** [comment]
I couldn't find any solution so I switched to this package https://www.npmjs.com/package/ngx-dropdown-list .

**Comment by galazzaroni** [comment]
I solved this doing this:
`import {AfterViewChecked} from '@angular/core';

constructor(private changeDetector: ChangeDetectorRef) { }

ngAfterViewChecked() {
    this.changeDetector.detectChanges();
  }`

**Comment by sysmat** [comment]
for me ChangeDetectorRef not solve the problem, still getting an error

**Comment by sysmat** [comment]
hm, no progress, error still eksist in ng: 11.1.0

**Comment by sysmat** [comment]
Hm, it seems there is no progress

**Comment by ulisesmorenomassachusetts** [comment]
Thanks! Worked for me following @galazzaroni  instructions also include AfterViewChecked in your class declaration:
`import { ChangeDetectorRef} from '@angular/core';
import {AfterViewChecked} from '@angular/core';
export class MyClass implements  AfterViewChecked
constructor(private changeDetector: ChangeDetectorRef) { }

ngAfterViewChecked() {
    this.changeDetector.detectChanges();
  }`

**Comment by sysmat** [comment]
In dev mode even ngAfterViewChecked hook not working, angular is not happy:

```
ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value for 'left': '185.0568084716797'. Current value: '177.3295440673828'.. Find more at https://angular.io/errors/NG0100
    at throwErrorIfNoChangesMode (core.js:6732)
    at bindingUpdated (core.js:12875)
    at checkStylingProperty (core.js:16707)
    at ɵɵstyleProp (core.js:16596)
    at AngularMultiSelect_Template (angular2-multiselect-dropdown.js:4661)
    at executeTemplate (core.js:9538)
```

It seems that is the problem:

```
ɵngcc0.ɵɵstyleProp("width", ctx.dropDownWidth, "px")("top", ctx.dropDownTop, "px")("left", ctx.dropDownLeft, "px");
ɵngcc0.ɵɵproperty("hidden", !ctx.isActive);

```

**Comment by sysmat** [comment]
this is very unsolved if I want to use it this lib it works with ver. 4.6.6 so 4.6.7 broke something

**Comment by CuppaLabs** [comment]
The library is upgraded to angular v11+. What version are you using ?

**Comment by sysmat** [comment]
```
Angular CLI: 11.2.0
Node: 14.15.4
OS: win32 x64

Angular: 11.2.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.0
@angular-devkit/build-angular   0.1102.0
@angular-devkit/core            11.2.0
@angular-devkit/schematics      11.2.0
@schematics/angular             11.2.0
@schematics/update              0.1102.0
rxjs                            6.6.3
typescript                      4.1.5
```

**Comment by CuppaLabs** [comment]
Sorry my bad. The library is being upgraded to angular v11+, in coming release. Currently the library is in v8. Once the upgrade is released, this error will be resolved. Mostly in couple of days this would be fixed.

**Comment by dipaktelangre** [comment]
I was also getting the same error. So downgraded to exact version ```4.6.6``` and its working fine. 

```
"angular2-multiselect-dropdown": "4.6.6",
```

**Comment by sysmat** [comment]
@CuppaLabs any timeline when will it be upgraded to angular v11+

**Comment by GillesMontyne** [comment]
This issue is still present in the latest 4.6.9 release... Any timeline for the fix?

**Comment by LeandroFChaves** [comment]
Up

**Comment by Yorer** [comment]
What's up CuppaLabs? Any update about this issue?

**Comment by sysmat** [comment]
Any progress?

**Comment by Yorer** [comment]
Seems like this problem has fixed. I've updated my angular project again to lastest, and this problem disappeared. Guys, do an update!

**Comment by sysmat** [comment]
"angular2-multiselect-dropdown": "4.6.10" fixed in this version
