### ISSUE TITLE
Design Issue

### ISSUE THREAD

**Issue by kumarprabhash2** [CuppaLabs/angular2-multiselect-dropdown#547]
Dear Team, 
You have fixed an issue in dropdown position absolute to fixed but if dropdown open on upper side and if someone search anything then design is breaking please have look on this issue.

**Comment by kumarprabhash2** [comment]
> Dear Team,
> You have fixed an issue in dropdown position absolute to fixed but if dropdown open on upper side and if someone search anything then design is breaking please have look on this issue.

Or You can give any setting to append dropdown won body like primeng plugin

**Comment by abnersouza** [comment]
The same happening to me but the main issue is a style attribute with width, left and top position being auto-added to the HTML tag. Any advice?

**Comment by CuppaLabs** [comment]
Duplicate. However refer to https://cuppalabs.github.io/angular2-multiselect-dropdown/#/usingInDialog. Closing..

**Comment by bits-amitrathod** [comment]
issue is still occur @CuppaLabs
