### ISSUE TITLE
how to add deselect all button by default

### ISSUE THREAD

**Issue by frontend123** [CuppaLabs/angular2-multiselect-dropdown#55]
I see there is select all button and i want to add deselect all button also along with select all. Is there a way to do it ?

**Comment by CuppaLabs** [comment]
The functionality is like this... Once you click on "select all", the text changes to "deselect all". There is no point in having select all and deselect all at the same time.

**Comment by frontend123** [comment]
thanks for your response. I got that functionality but if I select 10 items out of 25 items from drop down, there is no option to deselect all until i click select all button. so just checking if there is an easy way to add deselect all button also by default.

**Comment by CuppaLabs** [comment]
Hi, please refer to "Reset Dropdown" demo at "https://cuppalabs.github.io/angular2-multiselect-dropdown/". This will clear the selected items. This solves your problem.
