### ISSUE TITLE
GroupBy Not working as expected

### ISSUE THREAD

**Issue by skonetigari** [CuppaLabs/angular2-multiselect-dropdown#553]
I am trying to achive the output like this
Parent 1
----    Child 1
Parent 2
----  Child 1
Parent 3
Parent 4

In the itemlist i am providing
itemList = [
      { "id": 1, "itemName": "Child 1", "category": "Parent 1" },
      { "id": 2, "itemName": "Child 1", "category": "Parent 2" },
      { "id":3, "category": "Parent 3"},
      { "id":4, "category":"Parent 4"},
]

i am getting output like this
Parent 1
  child 1
Parent 2
  child 1
Parent 3
 <empty checkbox>
Parent 4
 <empty checkbox>

Can you let me how to achive the output as below 
 Parent 1
 ---   Child 1
Parent 2
 --- Child 1
Parent 3
Parent 4

**Comment by CuppaLabs** [comment]
@skonetigari It doesn't make sense to have a parent without a child and vice versa. So i think this would not be supported as of now. Hence closing. Thank you.
