### ISSUE TITLE
Dropdown list misalignment in IE11

### ISSUE THREAD

**Issue by tridung57903** [CuppaLabs/angular2-multiselect-dropdown#555]
Hi Team,

Our angular2-multiselect seem not working properly in IE11 browser while expanding the dropdown list.
The dropdown list move to top of screen instead of showing bottom/ top of dropdown component

![image](https://user-images.githubusercontent.com/19341941/106131935-debece00-6195-11eb-8020-47eb599652c4.png)

Can someone help to advise?

**Comment by CuppaLabs** [comment]
@tridung57903 We do not support IE. Angular itself is planning to stop supporting IE. However, please try using global css to override dropdown styles. That might help.
