### ISSUE TITLE
Select all Filtered search result is not even working on the website 

### ISSUE THREAD

**Issue by karangoyal2592** [CuppaLabs/angular2-multiselect-dropdown#557]
![image](https://user-images.githubusercontent.com/59535832/110298928-20eff080-801b-11eb-9de8-166492710f12.png)

This is selecting the complete result rather than the filtered result.
Settings:-
multiselect, group by

**Comment by CuppaLabs** [comment]
@karangoyal2592 Issue resolved with v5.0.0. Please refer to https://cuppalabs.github.io/angular2-multiselect-dropdown/#/groupby

**Comment by Karangoyal25892** [comment]
Thanks ..
