### ISSUE TITLE
Multiselect :: Apply & Cancel button

### ISSUE THREAD

**Issue by tomani77** [CuppaLabs/angular2-multiselect-dropdown#559]
This is not a issue rather a question. I am planning to use multiselect with angular>=9.my requirement is to show Apply & Cancel button. Once user clicks on apply/cancel button - want to take certain actions. To give you the use case I am using multiselect in table header filterable column. Once user selects options and clicks on Apply,  will filter tabular data based on values selected in multi select

**Comment by CuppaLabs** [comment]
@tomani77 Probably you can create apply/cancel button separately and use the multiselect Model data and capture the selected data or clear data and then apply the filter logic. With current plugin you should be able to achieve it.
