### ISSUE TITLE
SearchBy returns duplicate Value

### ISSUE THREAD

**Issue by prabhuofficial** [CuppaLabs/angular2-multiselect-dropdown#560]
Example dataset:
         {
            "fullName":"PG1st Enterprises, LLC ",
            "corporatename":"PG1st Enterprises, LLC"
         },
         {
            "fullName":"PGK Financial Services Inc. ",
            "corporatename":"PGK Financial Services Inc."
         },
         {
            "fullName":"John Williams",
            "corporatename":"Google, LLC"
         },
         {
            "fullName":"Phil Brooks",
            "corporatename":"Facebook, LLC"
         }

Settings:
    this.settings = {
      text: 'Search Agent Name / Corp Name',
      enableSearchFilter: true,
      enableFilterSelectAll: false,
      singleSelection: true,
      lazyLoading: true,
      labelKey: 'fullName',
      classes: 'drop-down-width',
      searchBy: ['fullName', 'corporatename'],
    };

Problem:
Now when I search for text 
1). Phil then only one item loaded in the virtual scroller as name & corporate name are different
2). PG1st then first list item loaded twice in the virtual scroller as both email & corporate name has same values

Please let me know how to mitigate this value?

**Comment by CuppaLabs** [comment]
@prabhuofficial  Each object in the array list should have an 'id' property or a property designated as primaryKey. See documentation on 'primaryKey' setting.

**Comment by prabhuofficial** [comment]
Duplicate values returned in search even after adding id property to the array list

**Comment by prabhuofficial** [comment]
{
  "fullName":"PG1st Enterprises, LLC ",
  "id":21868,
  "corporatname":"PG1st Enterprises, LLC"
},
{
  "fullName":"PGK Financial Services Inc. ",
  "id":11434,
  "corporatname":"PGK Financial Services Inc."
}

![image](https://user-images.githubusercontent.com/4505806/112710597-7ca9ed00-8ee8-11eb-9eaa-12241568cabe.png)
