### ISSUE TITLE
Custom html of menu item not reflecting in my project.

### ISSUE THREAD

**Issue by pshobha97** [CuppaLabs/angular2-multiselect-dropdown#561]
I have added everything as mentioned in doc for <angular2-multiselect> . i want to add custom html for menu list.
I have used.

``<c-item>
  <ng-template let-item="item">
    <label style="color: #fff;min-width: 150px;"></label>
    <img [src]="item.image" style="width: 30px; border: 1px solid #efefef;margin-right: 20px;" />
    <label>Capital - </label>
  </ng-template>
</c-item>   ``

But it is not reflecting in my project.

Please help me to get out of it.
Should i include default.theme.css file then where should i include?

**Comment by CuppaLabs** [comment]
@pshobha97 Can you please provide more information like the version of angular you are using ?

**Comment by CuppaLabs** [comment]
Working as expected. Hence closing.

**Comment by pshobha97** [comment]
> @pshobha97 Can you please provide more information like the version of angular you are using ?

I am using angular version 4.
The issue is not solved yet.
Please help.
