### ISSUE TITLE
Custom html template for menu item is not reflecting.

### ISSUE THREAD

**Issue by pshobha97** [CuppaLabs/angular2-multiselect-dropdown#562]
I have added everything as mentioned in doc.  actually i want to add custom html for menu list.
I have used.

<c-item> <ng-template let-item="item"> <label style="color: #fff;min-width: 150px;"></label> <img [src]="item.image" style="width: 30px; border: 1px solid #efefef;margin-right: 20px;" /> <label>Capital - </label> </ng-template> </c-item>

But it is not reflecting in my project.
My angular version is 4.
Please help me to get out of it.
@CuppaLabs

**Comment by CuppaLabs** [comment]
@pshobha97 The component is working as expected. Please do drop me a mail, for help with implementation.
