### ISSUE TITLE
@pshobha97 Can you please provide more information like the version of angular you are using ?

### ISSUE THREAD

**Issue by pshobha97** [CuppaLabs/angular2-multiselect-dropdown#563]
@pshobha97 Can you please provide more information like the version of angular you are using ?
I am using angular version 4. when i do install the default.theme.css is not present in node_modules and the custom template is not reflecting. Please help.
_Originally posted by @CuppaLabs in https://github.com/CuppaLabs/angular2-multiselect-dropdown/issues/561#issuecomment-808415356_

**Comment by CuppaLabs** [comment]
@pshobha97 Please use the latest version v5.0.1 . it supports angular 11
