### ISSUE TITLE
Selected items not being selected in dropdown causing duplicates

### ISSUE THREAD

**Issue by seandoran** [CuppaLabs/angular2-multiselect-dropdown#57]
Hi 
whenever I place a item into the selectItems array it places the item in a position as seen bellow
![capture](https://user-images.githubusercontent.com/13631559/30676824-705a6c48-9ecb-11e7-8368-3a9331e721ba.PNG)

this understandably creates a duplicate if i select the item again.
if you could help me out on this i would greatly appreciate thanks.
Sean

**Comment by seandoran** [comment]
it appears that the ids were not the identical so i just change the id to something that wouldn't change and easy fix

**Comment by CuppaLabs** [comment]
Please read the documentation and test it multiple times before raising an issue. Thanks !
