### ISSUE TITLE
showCheckbox option is not working

### ISSUE THREAD

**Issue by Charan-SS** [CuppaLabs/angular2-multiselect-dropdown#579]
Dropdown list shows checkboxes even if I set showCheckbox option to false in settings.

**Comment by jaumarar** [comment]
Hi @Charan-SS, which settings are you using? When you make a npm run build it generates any errors?

For me the option is working in this project
![show_1](https://user-images.githubusercontent.com/16009441/122109674-ecf84880-ce1d-11eb-943a-ce1935a77954.png)

and also on my proyect
![show_2](https://user-images.githubusercontent.com/16009441/122109815-1618d900-ce1e-11eb-8d1d-211a4ab1bc88.png)

**Comment by CuppaLabs** [comment]
Working as expected.
