### ISSUE TITLE
Library without Bootstrap and Awesome font

### ISSUE THREAD

**Issue by kchiragowni** [CuppaLabs/angular2-multiselect-dropdown#59]
Hi,

Wondering whether we can use this library but without Bootstrap and Awesome font? 
If yes could you you point me right direction.

Thanks and plugin looks awesome.

**Comment by CuppaLabs** [comment]
Without bootstrap you can. But font awesome is required.

**Comment by kchiragowni** [comment]
Hi, thanks and can you share some knowledge on how/where to update to UI libraries?

**Comment by kchiragowni** [comment]
Don't worry I manage to sort out. Thanks
