### ISSUE TITLE
IE Remove icon having disable attribute

### ISSUE THREAD

**Issue by jdeepak91** [CuppaLabs/angular2-multiselect-dropdown#61]
We have used multiselect dropdown module in our project, but it is not working in Internet Explorer 11. We have made analysis and found one solution, remove disable attribute from remove icon.
We stucked here.

Help will be appriciated.

**Comment by CuppaLabs** [comment]
ETA 4 days to fix the issue.

**Comment by yashashri10** [comment]
@CuppaLabs : Have you made changes for this issue? We stucked here. Your help appriciated.

Once done please let us know

**Comment by CuppaLabs** [comment]
fixed. Please refer to https://cuppalabs.github.io/angular2-multiselect-dropdown/ for demo. However, please wait for next reease to reflect in npm package.
