### ISSUE TITLE
Create Ivy distribution

### ISSUE THREAD

**Issue by bjornharvold** [CuppaLabs/angular2-multiselect-dropdown#612]
From Angular 13.x:

Processing legacy "View Engine" libraries:
- angular2-multiselect-dropdown [es2015/esm2015] (https://github.com/CuppaLabs/angular2-multiselect-dropdown)
- angular2-multiselect-dropdown [main/umd] (https://github.com/CuppaLabs/angular2-multiselect-dropdown)
Encourage the library authors to publish an Ivy distribution.

**Comment by sysmat** [comment]
any progress?

**Comment by peer-kkang** [comment]
any progress on this? thanks for all your hard work @CuppaLabs

**Comment by tommai78101** [comment]
No update plans thus far. See this pull request for more info.

https://github.com/CuppaLabs/angular2-multiselect-dropdown/pull/645

**Comment by CuppaLabs** [comment]
Ivy distribution supported.
