### ISSUE TITLE
Unable to style the dropdown

### ISSUE THREAD

**Issue by ChaudhryAtif** [CuppaLabs/angular2-multiselect-dropdown#63]
For example, if I'm trying to remove the shadow of the dropdown, I see the following way (from dom explorer) to access it to change it:
![image](https://user-images.githubusercontent.com/7082580/31636854-ccf85d3c-b291-11e7-985f-b2cb6ce2f548.png)

I tried adding the following to my dropdown.component.css, and even to global style.css, but it didn't change anything, even with !important.

```
.selected-list .c-btn {
    box-shadow: none !important;
}

// Even tried exact selectors as shown in dom style explorer
.selected-list[_ngcontent-c6]   .c-btn[_ngcontent-c6] {
    box-shadow: none !important;
}
```

I was not able to make a plunkr demo, but if you are able to create for as a base for people to provide a demo of their issue, that'll be helpful.

Thank you.

**Comment by CuppaLabs** [comment]
Hi, you can overwrite the css by writing your css in style.css(or create and include) file at src level of your angular-cli application. This is the practice that angular suggests to scope css to components and override in case if we want. Hence closing..  
.selected-list .c-btn {
    box-shadow: none !important;
}
this works..
![error](https://user-images.githubusercontent.com/3957664/31733434-41545370-b459-11e7-91bc-bf8d83f8d9f0.png)

**Comment by ChaudhryAtif** [comment]
Thank you for the response.

I started a new project using 'ng new multi-dropdown' (because when I tried to ran this repo locally, it gave an error when running ng serve -- so might want to check into that).

I then installed this component, added the necessary code to html/ts files. And then added the above css to the connected stylesheet. It did not work for me. Can you try?

Attached is the project I made. Download + npm install, then ng serve to run.

[multi-dropdown.zip](https://github.com/CuppaLabs/angular2-multiselect-dropdown/files/1395807/multi-dropdown.zip)

**Comment by CuppaLabs** [comment]
@ChaudhryAtif   Please take a look at this plunker for styling.. https://plnkr.co/edit/fof4c6PBadEfZFnaWT2G?p=preview
