### ISSUE TITLE
'AngularMultiSelectModule' does not appear to be an NgModule class

### ISSUE THREAD

**Issue by anubhavs-mckinsey** [CuppaLabs/angular2-multiselect-dropdown#642]
I'm using latest version (5.0.4), while running app I'm getting following error

Error: src/app/app.module.ts:43:5 - error NG6002: 'AngularMultiSelectModule' does not appear to be an NgModule class.

43     AngularMultiSelectModule
       ~~~~~~~~~~~~~~~~~~~~~~~~

  node_modules/angular2-multiselect-dropdown/lib/multiselect.component.d.ts:121:22
    121 export declare class AngularMultiSelectModule {
                             ~~~~~~~~~~~~~~~~~~~~~~~~
    This likely means that the library (angular2-multiselect-dropdown) which declares AngularMultiSelectModule is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

**Comment by fmssystem001** [comment]
i am getting same error on angular 16

**Comment by tommai78101** [comment]
@anubhavs-mckinsey @fmssystem001 See this pull request for more info.

https://github.com/CuppaLabs/angular2-multiselect-dropdown/pull/645

**Comment by CuppaLabs** [comment]
Please use v8.0.0 for angular 16 support.
