### ISSUE TITLE
AngularMultiSelectModule is not compatible with Angular Ivy

### ISSUE THREAD

**Issue by jaffbeto** [CuppaLabs/angular2-multiselect-dropdown#646]
Try use in angular 15.x.x

ERROR:
This likely means that the library (angular2-multiselect-dropdown) which declares AngularMultiSelectModule is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

**Comment by Tweniee** [comment]
only Angularv13 is supported.

**Comment by tommai78101** [comment]
@jaffbeto @Tweniee Despite Angular v13 at the latest being supported, there is an effort to upgrade to support Angular Ivy. See this pull request for more info.

https://github.com/CuppaLabs/angular2-multiselect-dropdown/pull/645

**Comment by CuppaLabs** [comment]
Upgraded to support Ivy
