### ISSUE TITLE
Ivy Issue not able to render this libarary in angular 16

### ISSUE THREAD

**Issue by amitkrishna** [CuppaLabs/angular2-multiselect-dropdown#648]
Error: :13:5 - error NG6002: 'AngularMultiSelectModule' does not appear to be an NgModule class.
 
13     AngularMultiSelectModule
       ~~~~~~~~~~~~~~~~~~~~~~~~
 
  node_modules/angular2-multiselect-dropdown/lib/multiselect.component.d.ts:121:22
    121 export declare class AngularMultiSelectModule {
                             ~~~~~~~~~~~~~~~~~~~~~~~~
    This likely means that the library (angular2-multiselect-dropdown) which declares AngularMultiSelectModule is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.
 
 
Error: :122:5 - error NG2012: Component imports must be standalone components, directives, pipes, or must be NgModules.
 
122     AngularMultiSelectModule

**Comment by saver711** [comment]
+1

**Comment by R180105** [comment]
also got this issue, is there any update plan?

**Comment by selangley-wa** [comment]
For those who are able to, consider migrating to use the Angular Material Select component that is maintained by the Angular Team:

Select Component - Angular Material Version 18
https://material.angular.io/components/select/overview#multiple-selection

Select Component - Angular Material version 14
https://v14.material.angular.io/components/select/overview#multiple-selection

**Comment by rohanahata** [comment]
This is happening soon. 
![Uploading Screenshot 2024-07-17 at 12.28.32 PM.png…]()

**Comment by CuppaLabs** [comment]
Please use v8.0.0 for angular 16 support.
