### ISSUE TITLE
groupBy Scroll issue

### ISSUE THREAD

**Issue by spa9999** [CuppaLabs/angular2-multiselect-dropdown#65]
When there are more itemName's under a category, is there anyway to display all of them **without the scroll-bar?**

I see a scroll-bar for long lists unders one category, and in which the last itemName is **overlapped** little bit by the immediate next category

and **Scroll is not smooth, when I try to scroll, its jumping back to top of the list!**

Can you help me out with this?

Thank you

**Comment by CuppaLabs** [comment]
Could you upload a screenshot of this ?

**Comment by spa9999** [comment]
![unnamed](https://user-images.githubusercontent.com/14339940/31735154-04bdb054-b40f-11e7-9d13-b6c79ca7c3de.png)

**Comment by spa9999** [comment]
From the image,

Under EMPLOYEE.BEN category, I have 16 ItemNames and I cant access any of the ItemNames after 9th item. (Thats the reason, I said scroll is not working or not smooth). When I try to scroll, its jumps back on to top of the items/list.

Is there a way to disable scroll-bars when there is groupBy?

**Comment by CuppaLabs** [comment]
fixed. available in v1.3.2

**Comment by spa9999** [comment]
Thank you so much. Its working fine with the scroll but has some issue with blinking check box and sometimes not able to select the items up to 2-3 clicks

**Comment by spa9999** [comment]
I think I need to report a new bug!
