### ISSUE TITLE
Blinking Check boxes and Unable to select items on first click (When using groupBy only)

### ISSUE THREAD

**Issue by spa9999** [CuppaLabs/angular2-multiselect-dropdown#66]
Hi,

I am using 1.3.2 version. 
When using with groupBy and when I select any check boxes,

1st, items are not getting selected on the first click. I tried multiple times and then it works.
2nd, CHECK BOXES are blinking continuously, after selection/checking it.

 Please check it and help me out. 

Thanks in Advance.!!!

**Comment by spa9999** [comment]
Hi,

Can any one help me out with this issue?

**Comment by spa9999** [comment]
One more issue is, when using groupBy, I can one select one item at a time. 

All these issues are only when we use groupBy

**Comment by CuppaLabs** [comment]
fixed. Fix available in v1.3.4

**Comment by CuppaLabs** [comment]
Yes it is an issue. But we can assure you that its not an issue related to component. I have already sent you the screenshot of the local testing of component and it works as expected. You can send your business code or please explain your issue in details, we will see how we can help you.
