### ISSUE TITLE
Unable to style the dropdown (cont)

### ISSUE THREAD

**Issue by ChaudhryAtif** [CuppaLabs/angular2-multiselect-dropdown#67]
The previous [issue](https://github.com/CuppaLabs/angular2-multiselect-dropdown/issues/63) thread was closed without user verification.

Followup from point of being closed:

I started a new project using 'ng new multi-dropdown' (because when I tried to ran this repo locally, it gave an error when running ng serve -- so might want to check into that).

I then installed this component, added the necessary code to html/ts files. And then added the above css to the connected stylesheet. It did not work for me. Can you try?

Attached is the project I made. Download + npm install, then ng serve to run.

[multi-dropdown.zip](https://github.com/CuppaLabs/angular2-multiselect-dropdown/files/1396742/multi-dropdown.zip)

**Comment by CuppaLabs** [comment]
Use cases are tested in local angular-cli environment. And the issue #63 has been closed after testing and providing justification with screenshots and implemented code. We cannot support for individual use cases here. For personal consultation please write to personal email. Also, Pull requests are welcome on this repo.

**Comment by gwooding** [comment]
Same problem here.  Adding CSS to the styles.css did nothing.  Currently styles.css is linked into project in angular-cli.json file under apps -> styles.  Is that the problem?

**Comment by CuppaLabs** [comment]
@gwooding Please refer to the solution and screenshot at https://github.com/CuppaLabs/angular2-multiselect-dropdown/issues/63#issuecomment-337669698

**Comment by gwooding** [comment]
There's a trick you're not mentioning around how you're doing that, could you provide a little more detail please?  How do you include the styles.css file in the project?  For now I've copied your module locally and am editing the css first hand.  Naughty me!  Your dropdown is otherwise excellent.

**Comment by CuppaLabs** [comment]
Please take a look at this plunker for styling.. https://plnkr.co/edit/fof4c6PBadEfZFnaWT2G?p=preview

**Comment by gwooding** [comment]
Ah I see, that plunkr was very helpful.  I was trying to override the wrong elements
