### ISSUE TITLE
Select / Unselect all child elements while click on group name.

### ISSUE THREAD

**Issue by sanoopkr** [CuppaLabs/angular2-multiselect-dropdown#69]
Hi,

I have  integrated multi select dropdown in one of my project. It is working well. But I have query like whether the plugin provide any option to make the group name selected. It would be great if we have an option like that, Since it would make the control more user friendly.

To make things more clear,

![image](https://user-images.githubusercontent.com/33024850/31892059-b56895f8-b825-11e7-9dd7-ae64d2df446c.png)

**Comment by CuppaLabs** [comment]
Good Suggestions. Thank you. Will include in next release in next week.

**Comment by sanoopkr** [comment]
Thanks for the quick response.

**Comment by gentle9** [comment]
I would love to have this feature.

**Comment by suresh2018** [comment]
Mee too when wil you release this feature ? Thanks in advance

**Comment by sweetyv** [comment]
Hi, even I need this feature for my project urgently. Could you please help @CuppaLabs ?
Thank you in advance.

**Comment by GustavoLima93** [comment]
Hello @CuppaLabs Thanks a lot for the angular2-multiselect-dropdown this is advancing my life a lot, I would like my colleagues to select this feature by group, I tried to understand the angular2-multiselect-dropdown core to implement the functionality but I could not do it unhappily I do not have the same level of maturity that you, I would like to know if you have any date to implement the functionaldiade? Thanks in advance.

**Comment by CuppaLabs** [comment]
Feature available in v3.2.1. please update your packages.
