### ISSUE TITLE
Add data Display Field to Settings

### ISSUE THREAD

**Issue by code-inspired** [CuppaLabs/angular2-multiselect-dropdown#70]
The field shown on the list should be in settings too, just like the groupBy field.

Thanks

**Comment by spa9999** [comment]
Yes, right now its only accepting the data which have id, itemName as property names. It would be great if you (CuppaLabs) can work on this and provide us this settings where we can specify the property name. 

Thanks

**Comment by Mridul16** [comment]
I am trying to use two multiselect-dropdowns but it gives me error "Error trying to diff '[object Object]'. Only arrays and iterables are allowed
    at DefaultIterableDiffer.webpackJsonp.../../../core/@angular/core.es5.js.DefaultIterableDiffer.diff (core.es5.js:6844)".
How can I add  multiple multi-select-dropdowns

**Comment by CuppaLabs** [comment]
fixed. v2.0.0. Please use template feature to have custom field names.
