### ISSUE TITLE
groupBy is not working in 1.3.4

### ISSUE THREAD

**Issue by spa9999** [CuppaLabs/angular2-multiselect-dropdown#71]
I downloaded the latest release and I cannot use the groupBy dropdownSettings!

Data is not being populated when I use 'groupBy' and if I take of that setting from Code, data is being populated!. 

Please fix it. Thank you

**Comment by CuppaLabs** [comment]
Are you sure ? that it is not working ?

**Comment by spa9999** [comment]
Yes. I did the basic testing. the same code is working fine when I am using 1.3.2 or 1.3.3 but When I update it to 1.3.4, its not displaying the data when using groupBy setting

**Comment by spa9999** [comment]
Update:

Actually issue is, its populating the data but still not displaying in the dropdown. When I select 'Select All' option, its showing all of the fields in the input box!. 
![2017-10-23 14_33_52-ortam web](https://user-images.githubusercontent.com/14339940/31906761-ebb61fa2-b7ff-11e7-8cbe-cdc6d9da1258.png)
![2017-10-23 14_36_57-ortam web](https://user-images.githubusercontent.com/14339940/31906765-ee214d34-b7ff-11e7-8dd8-9daf45af01ca.png)

**Comment by CuppaLabs** [comment]
Tested in Local v1.3.4 is working as expected.  Please clear your cache, update the package properly.
**Warning !!** - @spa9999 - Please do not raise issues without thorough testing. 
![image](https://user-images.githubusercontent.com/3957664/31907103-7c3b7112-b850-11e7-9620-32063ff2fa94.png)

Hence closing.

**Comment by spa9999** [comment]
Without testing, I think no developer will raise a issue! I have clearly posted the images of the issue which I am encountering. By the way, before raising the issue, I did the basic or initial testing by clearing cache, updating the packing and also check the data with and without using 'groupBy'

This is rude by giving a **Warning!** .

**Comment by CuppaLabs** [comment]
You are missing the point. This is open source and one should be careful before raising the issue, as it would adversely impact other developers/collaborators from getting notified unnecessarily. Hope you understand. If the issue still persists reopen the issue with proper screenshots of all the steps you followed to install the component.

**Comment by CuppaLabs** [comment]
Also, you are welcome for a Pull Request. If you could catch the bug, I appreciate you contribute to this repository. This is open source and its for mutual benefit.
