### ISSUE TITLE
Data grouping re-render on data update

### ISSUE THREAD

**Issue by Honoo** [CuppaLabs/angular2-multiselect-dropdown#73]
Currently, `groupBy` is only checked in `ngOnInit`. Hence if new options are subsequently added, they will not be grouped and will not even show up in the dropdown. Hence, `groupBy` should be checked subsequently to account for new data.

**Comment by Honoo** [comment]
The specific use case I had was dynamically pushing new options to `data` in a for-loop.

**Comment by Singularity222** [comment]
Also ran into this issue today myself. Any possibility of a fix soon?

**Comment by CuppaLabs** [comment]
fixed. available in v2.0.0
