### ISSUE TITLE
Can't able to change default fields

### ISSUE THREAD

**Issue by rishabh-jain389** [CuppaLabs/angular2-multiselect-dropdown#86]
I can't able to default field (id and itemsName) with my own field in a object ([data]="dropdownList"). If it is done by groupBy then how it can be changed. Example : 

this.dropdownList = [
                              {"cid":1,"countryName":"India"},
                              {"cid":2,"countryName":"Singapore"},
                              {"cid":3,"countryName":"Australia"},
                              {"cid":4,"countryName":"Canada"},
                              {"cid":5,"countryName":"South Korea"},
                              {"cid":6,"countryName":"Germany"},
                              {"cid":7,"countryName":"France"},
                              {"cid":8,"countryName":"Russia"},
                              {"cid":9,"countryName":"Italy"},
                              {"cid":10,"countryName":"Sweden"}
                            ];

**Comment by CuppaLabs** [comment]
Feature to be soon implemented. Please wait for this sunday release.

**Comment by CuppaLabs** [comment]
Fixed available in v2.0.0. Use the template feature to use custom field names.
