### ISSUE TITLE
How to use angular2-multiselect-dropdown in the form tag

### ISSUE THREAD

**Issue by phienngo** [CuppaLabs/angular2-multiselect-dropdown#87]
I want to use "angular2-multiselect-dropdown" in the <form>..</form>
Please help me to resolved it,
form>
angular2-multiselect [data]="dropdownList" [(ngModel)]="selectedItems" 
    [settings]="dropdownSettings" 
    (onSelect)="onItemSelect($event)" 
    (onDeSelect)="OnItemDeSelect($event)"
    (onSelectAll)="onSelectAll($event)"
    (onDeSelectAll)="onDeSelectAll($event)">/angular2-multiselect

</form>
Error: 
vendor.bundle.js:80244 ERROR Error: If ngModel is used within a form tag, either the name attribute must be set or the form
      control must be defined as 'standalone' in ngModelOptions.

BUT:
form>
angular2-multiselect [data]="dropdownList" name="selectedItems" 
   #selectedItems="ngModel" ngModel
    [settings]="dropdownSettings" 
    (onSelect)="onItemSelect($event)" 
    (onDeSelect)="OnItemDeSelect($event)"
    (onSelectAll)="onSelectAll($event)"
    (onDeSelectAll)="onDeSelectAll($event)">/angular2-multiselect>

/form>

It still not working....

**Comment by CuppaLabs** [comment]
Its simple. Example coming soon..

**Comment by CuppaLabs** [comment]
Please refer to this example https://cuppalabs.github.io/angular2-multiselect-dropdown/#/usinginform

**Comment by phienngo** [comment]
Thanks for your support @CuppaLabs
