### ISSUE TITLE
How to change key from ListItem object of multiselect.model.ts?

### ISSUE THREAD

**Issue by riteshdv5** [CuppaLabs/angular2-multiselect-dropdown#88]
As i want `itemName` should be `name` and  'id' should be 'uid` which is alphanumeri. How could i handle this.If i change the key name which i want from multiselect.model.ts then on every  npm install, it's got changed to it ,which i don't want, there should be flexibility of changing the json object from setting.

**Comment by CuppaLabs** [comment]
'id' property is mandatory. Custom property names are not allowed except in the template mode. When you provide data to dropdown you need to change the property names to id and itemName. However, you can add additional properties as per your convenience and use them in the template mode. Closing the issue.

**Comment by CuppaLabs** [comment]
Also, changing the library in itself will not get the latest changes on update. Should never be editing the library directly.
