### ISSUE TITLE
Including angular2-multiselect-dropdown package in app.module.ts is giving error.

### ISSUE THREAD

**Issue by chaisangam** [CuppaLabs/angular2-multiselect-dropdown#89]
I copy pasted the package.json as mentioned in the example and installed all the packages. My app.module.ts is as follows.

import { NgModule, ModuleWithProviders }      from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { FormsModule } from '@angular/forms';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { HttpModule } from '@angular/http';
import { AngularMultiSelectModule } from 'angular2-multiselect-dropdown/angular2-multiselect-dropdown';
import { RouterModule, Routes } from '@angular/router';
import { NgbModule, NgbPaginationConfig } from '@ng-bootstrap/ng-bootstrap';
import { NotifierModule, NotifierOptions } from 'angular-notifier';
//import { MultiSelectModule } from 'primeng/primeng';

// Our components and services for THM
import { AppComponent } from './components/app/index';
import { SearchComponent } from './components/search/index';

import 'jquery';
import 'materialize-css';

// Routes for routing

const appRoutes: Routes = [
    { path: '**', redirectTo: './components/app/index' }
];

const routes: ModuleWithProviders = RouterModule.forRoot(appRoutes);

// custom optiosn for the notifier
const customNotifierOptions: NotifierOptions = {
    position: {
        horizontal: {
            position: 'right',
            distance: 12
        },
        vertical: {
            position: 'top',
            distance: 12,
            gap: 10
        }
    },
    theme: 'material',
    behaviour: {
        autoHide: 5000,
        onClick: false,
        onMouseover: 'pauseAutoHide',
        showDismissButton: true,
        stacking: 4
    },
    animations: {
        enabled: true,
        show: {
            preset: 'slide',
            speed: 300,
            easing: 'ease'
        },
        hide: {
            preset: 'fade',
            speed: 300,
            easing: 'ease',
            offset: 50
        },
        shift: {
            speed: 300,
            easing: 'ease'
        },
        overlap: 150
    }
};

@NgModule({
    imports: [
        AngularMultiSelectModule,
        BrowserModule,
        FormsModule,
        BrowserAnimationsModule,
        HttpModule,
        routes,
        NgbModule.forRoot(),
        NotifierModule.forRoot(customNotifierOptions),
        
    ],
    declarations: [
        AppComponent,
        SearchComponent
    ],
    providers: [
       
        NgbPaginationConfig
    ],
  bootstrap:    [ AppComponent ]
})
export class AppModule { }

I am getting the below mentioned on application start
Error: (SystemJS) Unexpected token <
	SyntaxError: Unexpected token <
	    at eval (<anonymous>)
	    at Object.eval (http://localhost:51599/src/app/app.module.js:14:39)
	    at eval (http://localhost:51599/src/app/app.module.js:99:4)
	    at eval (http://localhost:51599/src/app/app.module.js:100:3)
	Evaluating http://localhost:51599/angular2-multiselect-dropdown/angular2-multiselect-dropdown
	Evaluating http://localhost:51599/src/app/app.module.js
	Evaluating http://localhost:51599/src/main.js
	Error loading http://localhost:51599/src/main.js
	    at eval (<anonymous>)
	    at Object.eval (http://localhost:51599/src/app/app.module.js:14:39)
	    at eval (http://localhost:51599/src/app/app.module.js:99:4)
	    at eval (http://localhost:51599/src/app/app.module.js:100:3)
	Evaluating http://localhost:51599/angular2-multiselect-dropdown/angular2-multiselect-dropdown
	Evaluating http://localhost:51599/src/app/app.module.js
	Evaluating http://localhost:51599/src/main.js
	Error loading http://localhost:51599/src/main.js

Is there anything wrong the way I am including the package?

**Comment by CuppaLabs** [comment]
Please create a plinker and send. Will check.

**Comment by CuppaLabs** [comment]
This is not an issue with the component. It might be with the code from your project. Kindly do not raise an issue here if it is not related to the component. Hence closing the issue. Refer to examples. Further any support, would be through emails. Hope you understand.

**Comment by chaisangam** [comment]
https://plnkr.co/edit/ZlNJfgayZq4xZmYANA8K?p=info


Here is the plunker. Please help.

**Comment by chaisangam** [comment]
https://plnkr.co/edit/ZlNJfgayZq4xZmYANA8K?p=info


Here is the plunker, please help.

Thanks,
Chaitra S

**Comment by chaisangam** [comment]
Hi Pradeep,

I am doing the same thing. As soon as I install and import the package in
app module I am getting error. I am currently using angular 4.0 it should
be okay right. I am really stuck on this not able to proceed further.

**Comment by maitreek** [comment]
Facing similar kind of issue with different error on starting the app. I'm using angular version 6.

Following is the error stack:

ERROR in ./src/app/app.module.ts
Module not found: Error: Can't resolve 'angular2-multiselect-dropdown/angular2-multiselect-dropdown' in 'D:\Projects\Gosnow\src\gosnow_admin\src\app'
i ｢wdm｣: Failed to compile.

Can someone guide me on the same?
