### ISSUE TITLE
How about lazy loading

### ISSUE THREAD

**Issue by phienngo** [CuppaLabs/angular2-multiselect-dropdown#90]
I want to apply lazy loading for options

Please give your idea ?

**Comment by CuppaLabs** [comment]
Lazy loading feature now available in v2.3.0

**Comment by santoshkumarsuru** [comment]
I am not able to find the example for angular2-multiselect-dropdown **lazyloading** concept, please someone guide me on this

**Comment by FirassKoubaa** [comment]
how to implement it

**Comment by gonmedtara** [comment]
Add  callback (onOpen) to add the Scroll listner
```
<div>
<angular2-multiselect [data]="dropdownList" [(ngModel)]="selectedItems" 
    [settings]="dropdownSettings" 
    (onSelect)="onItemSelect($event)" 
    (onDeSelect)="OnItemDeSelect($event)"
    (onSelectAll)="onSelectAll($event)"
    (onDeSelectAll)="onDeSelectAll($event)"
    (onOpen)="addScrollListner()"
></angular2-multiselect>
</div>
```
bind _onScroll_ function to read element parametres. i get _ul_ tag, but i recommend to use _lazyContainer_ class name : 

> getElementsByClassName("lazyContainer")

```
  addScrollListner() {
    this.el.nativeElement
      .getElementsByTagName("ul")[0]
      .addEventListener("scroll", this.onScroll.bind(this));

  onScroll($event: Event): void {
    let pos = $event.srcElement.scrollTop + $event.srcElement["offsetHeight"];
    let max = $event.srcElement.scrollHeight;
    if (pos == max) {
          MyDataService.fetchData(from,numberOfObjects);
    }
  }
```
you can use REST  parametres :_offset_ as _from_ and _limit_ as _numberOfObjects_.
 [https://www.moesif.com/blog/technical/api-design/REST-API-Design-Filtering-Sorting-and-Pagination/](url)

and  in your response , you have just to concat the response 

```
   response => {
     dropdownList = dropdownList.concat(response)
  }

```
