### ISSUE TITLE
Integrating jenkins for angular 4 project

### ISSUE THREAD

**Issue by policz** [CuppaLabs/angular2-multiselect-dropdown#91]
i'm trying to create the jenkins.js file which performs the tasks like build and Sonar, i have an experience to create this jenkins.js file with gulp (AngularJS) , but i'm new to the Angular. Is there any particular proceess f how to build and configure the jenkins job in Angular project.

**Comment by CuppaLabs** [comment]
This issue is not to be raised here. No relevance.
