### ISSUE TITLE
How can I use this in table?

### ISSUE THREAD

**Issue by idevN** [CuppaLabs/angular2-multiselect-dropdown#92]
I am quite new at angular and I am having trouble figuring out how to implement this properly in a table.

What I am trying to do is to implement it in a table. But When I make change in dropdown in one of the row, it is reflected in all the other rows as well.

Here is a issue i'm facing: https://stackblitz.com/edit/angular-sv7tj8

What do I need to do so that change in dropdown of one row won't have any effect in other row?

**Comment by CuppaLabs** [comment]
The ngModel of dropdown should be different for different rows. Please write a mail for any consulting purposes for your project. Would be happy to help. Thanks.
