### ISSUE TITLE
Dropdown disable/enable based on condition

### ISSUE THREAD

**Issue by goutame** [CuppaLabs/angular2-multiselect-dropdown#96]
Hi I am using this module in our project.Everything works fine.
But based on condition if I disable the dropdown and enable it again,I get an error 
Cannot read undefined of firstChange.

Can someone help in fixing this

**Comment by CuppaLabs** [comment]
Please update to latest version. This is fixed.

**Comment by CuppaLabs** [comment]
Fix available in v2.1.2. Hence closing.

**Comment by goutame** [comment]
I am using the latest version.
Can you please let me know how to disable in the settings

ngOnInit() {
	this.selectSettings = {
      text: "Select",
      enableCheckAll: true,
      selectAllText: 'Select All',
      unSelectAllText: 'UnSelect All',
      disabled: false,
      showCheckbox:true
    };
}

if(this.disable) {
	this.selectSettings = {
      text: "Select",           
      enableCheckAll: true,
      selectAllText: 'Select All',
      unSelectAllText: 'UnSelect All', 
      **disabled: false,**
      showCheckbox:true
    };
}else {
	this.selectSettings = {
        text: "Select",
        enableCheckAll: true,
        selectAllText: 'Select All',
        unSelectAllText: 'UnSelect All',
        disabled: true,
        showCheckbox:true
      };
}

Is this right?

**Comment by CuppaLabs** [comment]
yes that's right.

**Comment by sivailangos** [comment]
Does it work on Reactive Forms?

**Comment by crazyfortechsid** [comment]
But it doesn't work in case of deSelectAll
