### ISSUE TITLE
Angular always reports this component as untouched

### ISSUE THREAD

**Issue by ryanmagits** [CuppaLabs/angular2-multiselect-dropdown#98]
You can see this in the chrome inspector even in the examples section. The dirty/pristine works fine but the component always reports untouched even after changes. This has caused some issue with validation on touched.  I hope this makes sense. Thanks.

**Comment by CuppaLabs** [comment]
@ryanmagits : Yes as of now only required and dirty/preistine are supported on this component. Touched and untouched are queued for next release. Also, I would appreciate if you would raise pull request for fixing this.

**Comment by CuppaLabs** [comment]
fixed. Fix available in v2.1.4
