### ISSUE TITLE
Webpack --env.prod Compile error

### ISSUE THREAD

**Issue by s-leonard** [CuppaLabs/angular2-multiselect-dropdown#99]
Hi

This component works well in development but as soon as I try and build in production, I'm getting compile errors. 

`node node_modules/webpack/bin/webpack.js --env.prod
Hash: b247ef423e062dc227d9a0e2a90fc0eaebe4448e
Version: webpack 2.5.1
Child
    Hash: b247ef423e062dc227d9
    Time: 54268ms
             Asset     Size  Chunks                    Chunk Names
    main-client.js  1.34 MB       0  [emitted]  [big]  main-client
    
    ERROR in ./$$_gendir/~/angular2-multiselect-dropdown/angular2-multiselect-dropdown/multiselect.component.ngfactory.ts
    Module parse failed: C:\@git\Apps\AngularApp2\$$_gendir\node_modules\angular2-multiselect-dropdown\angular2-multiselect-dropdown\multiselect.component.ngfactory.ts Unexpected token (17:46)
    You may need an appropriate loader to handle this file type.
    | import * as i6 from 'angular2-multiselect-dropdown/angular2-multiselect-dropdown/list-filter';
    | import * as i7 from 'angular2-multiselect-dropdown/angular2-multiselect-dropdown/clickOutside';
    | export const AngularMultiSelectModuleNgFactory:i0.NgModuleFactory<i1.AngularMultiSelectModule> = i0.╔Ácmf(i1.AngularMultiSelectModule,
    |     ([] as any[]),(_l:any) => {
    |       return i0.╔Ámod([i0.╔Ámpd(512,i0.ComponentFactoryResolver,i0.╔ÁCodegenComponentFactoryResolver,
     @ ./$$_gendir/ClientApp/app/components/components/components.component.ngfactory.ts 11:0-152
     @ ./$$_gendir/ClientApp/app/app.module.browser.ngfactory.ts
     @ ./ClientApp/boot.browser.ts
    
    ERROR in ./$$_gendir/~/angular2-multiselect-dropdown/angular2-multiselect-dropdown/menu-item.ngfactory.ts
    Module parse failed: C:\@git\Apps\AngularApp2\$$_gendir\node_modules\angular2-multiselect-dropdown\angular2-multiselect-dropdown\menu-item.ngfactory.ts Unexpected token (11:17)
    You may need an appropriate loader to handle this file type.
    | import * as i0 from '@angular/core';
    | import * as i1 from 'angular2-multiselect-dropdown/angular2-multiselect-dropdown/menu-item';
    | const styles_Item:any[] = ([] as any[]);
    | export const RenderType_Item:i0.RendererType2 = i0.╔Ácrt({encapsulation:2,styles:styles_Item,
    |     data:{}});
     @ ./$$_gendir/ClientApp/app/components/components/components.component.ngfactory.ts 13:0-140
     @ ./$$_gendir/ClientApp/app/app.module.browser.ngfactory.ts
     @ ./ClientApp/boot.browser.ts
Child
    Hash: a0e2a90fc0eaebe4448e
    Time: 54456ms
             Asset     Size  Chunks                    Chunk Names
    main-server.js  8.33 MB       0  [emitted]  [big]  main-server
    
    ERROR in ./$$_gendir/~/angular2-multiselect-dropdown/angular2-multiselect-dropdown/multiselect.component.ngfactory.ts
    Module parse failed: C:\@git\Apps\AngularApp2\$$_gendir\node_modules\angular2-multiselect-dropdown\angular2-multiselect-dropdown\multiselect.component.ngfactory.ts Unexpected token (17:46)
    You may need an appropriate loader to handle this file type.
    | import * as i6 from 'angular2-multiselect-dropdown/angular2-multiselect-dropdown/list-filter';
    | import * as i7 from 'angular2-multiselect-dropdown/angular2-multiselect-dropdown/clickOutside';
    | export const AngularMultiSelectModuleNgFactory:i0.NgModuleFactory<i1.AngularMultiSelectModule> = i0.╔Ácmf(i1.AngularMultiSelectModule,
    |     ([] as any[]),(_l:any) => {
    |       return i0.╔Ámod([i0.╔Ámpd(512,i0.ComponentFactoryResolver,i0.╔ÁCodegenComponentFactoryResolver,
     @ ./$$_gendir/ClientApp/app/components/components/components.component.ngfactory.ts 11:0-152
     @ ./$$_gendir/ClientApp/app/app.module.server.ngfactory.ts
     @ ./ClientApp/boot.server.ts
    
    ERROR in ./$$_gendir/~/angular2-multiselect-dropdown/angular2-multiselect-dropdown/menu-item.ngfactory.ts
    Module parse failed: C:\@git\Apps\AngularApp2\$$_gendir\node_modules\angular2-multiselect-dropdown\angular2-multiselect-dropdown\menu-item.ngfactory.ts Unexpected token (11:17)
    You may need an appropriate loader to handle this file type.
    | import * as i0 from '@angular/core';
    | import * as i1 from 'angular2-multiselect-dropdown/angular2-multiselect-dropdown/menu-item';
    | const styles_Item:any[] = ([] as any[]);
    | export const RenderType_Item:i0.RendererType2 = i0.╔Ácrt({encapsulation:2,styles:styles_Item,
    |     data:{}});
     @ ./$$_gendir/ClientApp/app/components/components/components.component.ngfactory.ts 13:0-140
     @ ./$$_gendir/ClientApp/app/app.module.server.ngfactory.ts
     @ ./ClientApp/boot.server.ts
`

Does anyone have any advice on what is causing this?

**Comment by CuppaLabs** [comment]
please use appropriate webpack loader to use the component .The component is packaged using angular 4 package format. So supports almost all the loader ways.

**Comment by israelvi** [comment]
Hi,
Which is the correct webpack loader?, I have the same issue (v1.3.4), I am using the following configuration (webpack.config.js):
```
module: {
            rules: [
                {
                    test: /\.ts$/,
                    include: /ClientApp/,
                    use: isDevBuild ? [
                        'awesome-typescript-loader',
                        'angular-router-loader',
                        'angular2-template-loader',
                        'source-map-loader',
                    ] : '@ngtools/webpack'
                },
                { test: /\.html$/, use: 'html-loader?minimize=false' },
                {
                    test: /\.css(\?|$)/,
                    use: extractCss.extract({ use: isDevBuild ? 'css-loader' : 'css-loader?minimize' })
                },
                {
                    test: /\.(png|jpg|gif|woff|woff2|ttf|svg|eot)$/,
                    loader: 'file-loader?name=assets/[name]-[hash:6].[ext]'
                }
            ]
        },
```
